### ISSUE TITLE
allowMultiple={false} and showHidden={true} doesn't work with ResourcePicker

### ISSUE THREAD

**Issue by alexissel** [Shopify/shopify-app-bridge#10]
## Describe the bug

I'm using the ResourcePicker component in my app and everything is working properly, less the `selectMultiple={false}` and `showHidden={true}` options. [According to docs](https://shopify.dev/tools/app-bridge/react-components/resourcepicker), you should be able to use these options...

### My Code

`<ResourcePicker`
`resourceType="ProductVariant"`
`selectMultiple={false}`
`showHidden={true}`
`open={active}`
`onSelection={(resources) => handleSelection(resources)}`
`onCancel={() => setActive(false)}`
`/>`

### Expected behaviour

When the Modal (ResourcePicker) is open, you should see all the products (Available and Unavailable) and select just one Variant.

### Packages and versions

- `@shopify/app-bridge-react` @ `^1.27.2`,
- `@shopify/koa-shopify-auth` @ `^3.1.70`,
- `@shopify/koa-shopify-graphql-proxy` @ `^4.0.2`,
- `@shopify/polaris` @ `^5.4.0`,
- `next` @ `^9.5.3`,
- `react` @ `^16.13.1`,

## Platform

- OS: MacOS
- OS Version: 10.15.7
- App: Chrome

**Comment by iainmcampbell** [comment]
Hi Alexis, I can’t reproduce this in a test app. Can you provide some more details about what isn’t working in your app?

**Comment by alexissel** [comment]
Please ignore the bug, I was using a the wrong prop.
I used `selectMultiple ` instead of `allowMultiple`

Everything is working fine now.

**Comment by iainmcampbell** [comment]
glad to hear it 👍
