### ISSUE TITLE
Feature Detection / Request for Cart fails on Android 10

### ISSUE THREAD

**Issue by jayesbe** [Shopify/shopify-app-bridge#105]
## Describe the bug

As per https://github.com/Shopify/shopify-app-bridge/issues/101

@henrytao-me  says permission is not required - however I am still not able to get a brutally simple implementation working.

### To Reproduce

Code example to reproduce the issue

```

<script type="text/javascript">

var AppBridge = window['app-bridge'];

var App = AppBridge.createApp({
    apiKey: 'redacted',
    host: 'redacted',
});

document.addEventListener('DOMContentLoaded', function() {

	App.error(function (data) {
		alert(data.message);
    });

	var cart = AppBridge.actions.Cart.create(App);

	cart.subscribe(AppBridge.actions.Cart.Action.UPDATE, function (payload) {
		alert('Fetched');
	});		    

	cart.dispatch(AppBridge.actions.Cart.Action.FETCH);

},false);

</script>
```

### Expected behaviour

I expect that based on the above example, an alert would be displayed with the text Fetched.  Instead I see an alert that says "Action is not permitted"

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

using dev package - https://unpkg.com/@shopify/app-bridge@2/umd/index.development.js

## Platform

- Android 10
- Shopify POS App

### Additional context

This is using the browser based package via vanilla javascript development.

**Comment by henrytao-me** [comment]
Hi @jayesbe 

In this [document](https://shopify.dev/apps/tools/app-bridge/actions/cart#feature-detection), we mention about Feature Detection which is required for accessing the Cart. Can you try below code? 

```js
var AppBridge = window['app-bridge'];

var App = AppBridge.createApp({
    apiKey: 'redacted',
    host: 'redacted',
});

document.addEventListener('DOMContentLoaded', function () {
    var cart = AppBridge.actions.Cart.create(App);
    cart.subscribe(AppBridge.actions.Cart.Action.UPDATE, function (payload) {
        alert('Fetched');
    });

    app.featuresAvailable(Group.Cart).then(function (state) {
        var _ref = state.Cart && state.Cart[Cart.Action.FETCH], Dispatch = _ref.Dispatch;

        if (Dispatch) {
            cart.dispatch(Cart.Action.FETCH);
        } else {
            var toastOptions = {
                message: 'Cart is not available',
                duration: 5000,
                isError: true
            };
            var toastError = Toast.create(app, toastOptions);
            toastError.dispatch(Toast.Action.SHOW);
        }
    });
}, false);
```

**Comment by jayesbe** [comment]
@henrytao-me 

Thank you for the reply.. I adjusted the code to match mine.. this produces a result of **Not Fetched**

```
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {

	App.error(function (data) {
		alert(data.message);
      });

	var cart = AppBridge.actions.Cart.create(App);

	cart.subscribe(AppBridge.actions.Cart.Action.UPDATE, function (payload) {
		alert('Fetched');	
	});		    

    App.featuresAvailable(AppBridge.actions.Group.Cart).then(function (state) {
        var _ref = state.Cart && state.Cart[AppBridge.actions.Cart.Action.FETCH], Dispatch = _ref.Dispatch;
    
        if (Dispatch) {
            cart.dispatch(AppBridge.actions.Cart.Action.FETCH);
        } else {
        	alert('Not Fetched');
        }
    });

},false);
</script>

```
Please advise

**Comment by jayesbe** [comment]
@henrytao-me any thoughts - as far as I am aware - this has always been an issue. I have personally revisited my android implementation 4 times since last January and this specific issue has existed ever since the new experience rolled out.

I've mentioned to clients to switch to iOS which is really not a solution at all. There is one client monitoring this particular thread.

**Comment by henrytao-me** [comment]
There is a race condition happens when the embedded app javascript is called before native layer sends cart features update. So, essentially we need to do both cart feature detection and feature update.
- https://shopify.dev/apps/tools/app-bridge/actions/cart#feature-detection
- https://shopify.dev/apps/tools/app-bridge/actions/features#cart

Below snippet should work

```js
var cart = AppBridge.actions.Cart.create(App);
cart.subscribe(AppBridge.actions.Cart.Action.UPDATE, function (payload) {
    alert('Fetched');
});

var cartFeaturesAvailable = new Promise((resolve) => {
    function checkCartFeatures() {
        return App.featuresAvailable(AppBridge.actions.Group.Cart).then(function (state) {
            var _ref = state.Cart && state.Cart[AppBridge.actions.Cart.Action.FETCH]
                , Dispatch = _ref.Dispatch;
            if (Dispatch) {
                resolve();
            }
            return Dispatch;
        });
    }

    checkCartFeatures().then(function (isCartAvailable) {
        if (isCartAvailable) return;
        App.subscribe(AppBridge.actions.Features.Action.UPDATE, function () {
            checkCartFeatures().then(function (isCartAvailable) {
                if (isCartAvailable) return;
                window.alert('Not fetched');
            });
        });
    });
});

cartFeaturesAvailable.then(function () {
    cart.dispatch(AppBridge.actions.Cart.Action.FETCH);
});
```
