### ISSUE TITLE
getSessionToken(app) does not resolve with the new admin domain url experience

### ISSUE THREAD

**Issue by ziemb** [Shopify/shopify-app-bridge#110]
Using the new admin domain url my apps does not load (stops) on resolving the function getSessionToken(app). This is what I do:

````
async function retrieveToken(app) {
  window.sessionToken = await getSessionToken(app)
}

window.app = createApp({
    apiKey: api,
    shopOrigin: shopOrigin,
    forceRedirect: true,
    host: host,
})

await retrieveToken(app)
````

It only does not resolve on the new url. On the old one it works fine.

It would be nice to have any feedback from GetSessionToken function, but as I said it doesn't return anything, just freezes. Would appreciate any help with this.

### Packages and versions

- @shopify/app-bridge-utils@1.29.0
- @shopify/app-bridge-react@1.30.0
- @shopify/polaris@4.27.0

**Comment by henrytao-me** [comment]
App Bridge 1.x doesn't work with new admin domain. The expectation is that the merchant will see a banner on the top asking to reload the page which redirects back to the *.myshopify.com after 5 seconds. In term of the embedded app, it posts the message to wrong origin (supposed to use host query param in App Bridge 2.x). So, I don't think there is anything we can do here other than upgrading the client to 2.x
