### ISSUE TITLE
APP::APP_ERROR::WINDOW_UNDEFINED ERROR

### ISSUE THREAD

**Issue by ertugrul59** [Shopify/shopify-app-bridge#111]
I can not use Modal for my app, my app crashes after opening modal for specified route. If i do not define a src it works as expected. What can be the issue, how can i solve it, thank you.

DOC: [https://shopify.dev/apps/tools/app-bridge/react-components/modal]

APP::APP_ERROR::WINDOW_UNDEFINED ERROR

**Error Code:**
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
[Error [AppBridgeError]: APP::APP_ERROR::WINDOW_UNDEFINED: State is only available on the client side.] {
  action: undefined,
  type: 'APP::APP_ERROR::WINDOW_UNDEFINED'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ertugrul59** [comment]
_app.js setup as specified from tutorials, do i need to make any changes in there? 


This is  my _app.js :


//////////////
import ApolloClient from "apollo-boost";
import { ApolloProvider } from "react-apollo";
import App from "next/app";
import { AppProvider } from "@shopify/polaris";
import { Provider, useAppBridge } from "@shopify/app-bridge-react";
import { authenticatedFetch } from "@shopify/app-bridge-utils";
import { Redirect } from "@shopify/app-bridge/actions";
import "@shopify/polaris/build/esm/styles.css";
import translations from "@shopify/polaris/locales/en.json";

function userLoggedInFetch(app) {
  const fetchFunction = authenticatedFetch(app);

  return async (uri, options) => {
    const response = await fetchFunction(uri, options);

    if (
      response.headers.get("X-Shopify-API-Request-Failure-Reauthorize") === "1"
    ) {
      const authUrlHeader = response.headers.get(
        "X-Shopify-API-Request-Failure-Reauthorize-Url"
      );

      const redirect = Redirect.create(app);
      redirect.dispatch(Redirect.Action.APP, authUrlHeader || `/auth`);
      return null;
    }

    return response;
  };
}

function MyProvider(props) {
  const app = useAppBridge();

  const client = new ApolloClient({
    fetch: userLoggedInFetch(app),
    fetchOptions: {
      credentials: "include",
    },
  });

  const Component = props.Component;

  return (
    <ApolloProvider client={client}>
      <Component {...props} />
    </ApolloProvider>
  );
}

class MyApp extends App {
  render() {
    const { Component, pageProps, host, shopOrigin } = this.props;
    return (
      <AppProvider i18n={translations}>
        <Provider
          config={{
            apiKey: API_KEY,
            host: host,
            forceRedirect: true,
          }}
        >
          <MyProvider
            Component={Component}
            {...pageProps}
            shopOrigin={shopOrigin}
            hosturl={hosturl}
          />
        </Provider>
      </AppProvider>
    );
  }
}

MyApp.getInitialProps = async ({ ctx }) => {
  return {
    shopOrigin: ctx.query.shop,
    host: ctx.query.host,
  };
};

export default MyApp;

**Comment by olavoasantos** [comment]
I don't see the Modal being used there. Do you have a snippet of how you're using the Modal?

**Comment by ertugrul59** [comment]
It is false by default, and index.js page works as expected there is no issue about loading, and Modal works as expected, however if i define src such as src="/addlocation"  it causes error , thanks.

```
function Index({ shopOrigin, hosturl }) {
  const [denemeModel1, setDenemeModel1] = useState(false);

  return (
    <div style={{ height: "250px" }}>
      <Frame>
        <Page title="Control Panel">
          {pagenitation ? (
            wholepage
          ) : (
            <Spinner accessibilityLabel="Spinner example" size="large" />
          )}
        </Page>
        <Modal title="My modal" message="Hello world!" open={denemeModel1}
        onClose={() => {
          setDenemeModel1(false);
        }}
        size="Medium"
        src="/addlocation"
         />
      </Frame>

    </div>
  );
}

```

**Comment by olavoasantos** [comment]
I copied over your code and couldn't reproduce the issue. Would you be able to share the code? if not, are you able to share a repo in which the error is reproducible? Also, which versions of the App Bridge libraries are you using?

**Comment by ertugrul59** [comment]
It does fails on any page, i am guessing issue with _app.js configuration, can you share the code? i can look at it to see difference, i had this issue for a year, before was just giving me error in Backend, now causes crash at BA, thank you


My package.json

```
{
  "cacheDirectories": [
    ".next/cache"
  ],
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "engines": {
    "node": "16.15.0"
  },
  "scripts": {
    "test": "jest",
    "dev": "cross-env NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js",
    "build": "NEXT_TELEMETRY_DISABLED=1 next build",
    "start": "cross-env NODE_ENV=production node ./server/index.js"
  },
  "author": "ERTUGRUL",
  "license": "MIT",
  "dependencies": {
    "@apollo/client": "^3.4.7",
    "@babel/core": "7.12.10",
    "@babel/polyfill": "^7.6.0",
    "@babel/preset-env": "^7.13.10",
    "@babel/register": "^7.13.8",
    "@koa/cors": "^3.1.0",
    "@shopify/app-bridge": "^3.0.0",
    "@shopify/app-bridge-react": "^3.0.0",
    "@shopify/app-bridge-utils": "^3.0.0",
    "@shopify/koa-shopify-auth": "^5.0.3",
    "@shopify/koa-shopify-webhooks": "^4.4.3",
    "@shopify/polaris": "^9.11.0",
    "@zeit/next-css": "^1.0.1",
    "apollo-boost": "^0.4.9",
    "apollo-link-http": "^1.5.17",
    "async": "^3.2.3",
    "axios": "^0.21.1",
    "bcryptjs": "^2.4.3",
    "clean-webpack-plugin": "4.0.0",
    "cors": "^2.8.5",
    "cross-env": "7.0.3",
    "crypto": "^1.0.1",
    "crypto-js": "^4.1.1",
    "cryptr": "^6.0.2",
    "dotenv": "^8.2.0",
    "graphql": "^14.5.8",
    "graphql-request": "^3.5.0",
    "isomorphic-fetch": "^3.0.0",
    "js-cookie": "^2.2.1",
    "jsonwebtoken": "8.5.1",
    "koa": "^2.13.1",
    "koa-body": "4.2.0",
    "koa-combine-routers": "^4.0.2",
    "koa-cors": "0.0.16",
    "koa-router": "^10.0.0",
    "koa-session": "^6.1.0",
    "koa-static": "^5.0.0",
    "lodash": "4.17.21",
    "moment": "2.29.2",
    "moment-timezone": "0.5.33",
    "mongoose": "^5.12.0",
    "next": "^10.0.4",
    "next-env": "1.1.1",
    "node-cron": "3.0.0",
    "node-fetch": "^2.6.1",
    "nodemailer": "6.6.3",
    "npm": "^8.5.5",
    "query-string": "^7.0.1",
    "react": "^16.8.0",
    "react-apollo": "^3.1.5",
    "react-dom": "^16.8.0",
    "react-router": "^6.0.2",
    "react-router-dom": "^6.0.2",
    "recharts": "^2.1.8",
    "redis": "^3.1.2",
    "store-js": "^2.0.4",
    "styled-jsx-css-loader": "0.3.0",
    "tawkto-react": "2.0.3",
    "typescript": "^4.4.4",
    "webpack": "^5.51.1"
  },
  "devDependencies": {
    "@babel/plugin-transform-runtime": "^7.13.10",
    "@babel/preset-stage-3": "^7.0.0",
    "babel-jest": "26.6.3",
    "babel-register": "^6.26.0",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.5",
    "husky": "^4.3.8",
    "jest": "26.6.3",
    "lint-staged": "^10.5.4",
    "nodemon": "^2.0.7",
    "prettier": "2.2.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,css,json,md}": [
      "prettier --write"
    ]
  },
  "keywords": []
}

```
