### ISSUE TITLE
ResourcePicker does not show products in Shopify POS 7.1.0 when keyboard open

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#117]
## Describe the bug

@henrytao-me 

In 7.1.0 when the iOS keyboard is open, you cannot see any products available to check. This is creating confusion for merchants, **the merchant is forced to drop the keyboard in order to see any products.**

Screenshot of ResourcePicker behavior with keyboard open prior to 7.1.0: 

![IMG_0013](https://user-images.githubusercontent.com/46724607/174678743-ee30158c-9cb4-4873-a7b7-93edb1e8b383.PNG)

Current behavior with keyboard open (the merchant must close the keyboard in order to see the products):

![IMG_0064](https://user-images.githubusercontent.com/46724607/174678799-fc665bbc-2a58-4199-aa47-b43fb0915dcb.PNG)

**Comment by samiulmonir06** [comment]
@derrickrc : We have reviewed the issue and currently working on it.

**Comment by vctrchu** [comment]
Fix should be available in the next release.

**Comment by derrickrc** [comment]
Thank you team!
