### ISSUE TITLE
Docs/guidelines for App-Bridge-Host on a local env

### ISSUE THREAD

**Issue by maxkostinevich** [Shopify/shopify-app-bridge#12]
### Describe the feature you’d like

Just found [ App-Bridge-Host](https://www.npmjs.com/package/@shopify/app-bridge-host) package and it seems like a great solution for local testing & development. However, I can't figure out how to setup and configure App Bridge Host correctly (there is a few examples in official Readme, however it is not clear how to integrate it with existing app built on React Polaris). So any examples or guidelines would be really helpful.

### Describe alternatives you've considered

At the moment, development and testing on local environment is "tricky", as refreshing a page inside of Shopify iFrame after every change is slow.

### Additional context

Conversation in Slack: https://shopifypartners.slack.com/archives/CKK8FHFDF/p1602087862014500

**Comment by iainmcampbell** [comment]
Additional context from Slack conversation:

> [app-bridge-host] allows setting up a host that replaces Shopify Admin which can load your app for testing. However, your app would still load inside an iframe. It would be hard to consume the app-bridge-host package and use it on your own. In the future we would like to release a test host for testing apps outside of Shopify Admin but there's no plans for that currently.
>
> …the idea is to help speed up development on the front end while using App Bridge. You won't need to set up an app or a development shop. You can get started right away with a test app and play around with App Bridge features on your local. The test host won't replace a real store though so it won't fully work for things that require real data. However, you can test things like showing a Toast, Modal, etc...we haven't fully planned how this could be rolled out publicly.

**Comment by marcusstenbeck** [comment]
@jDolba I'm also experiencing a lot of wasted time using the App Bridge. Did you figure out any way of improving your development experience? 

I'm especially interested in finding a way to develop components in isolation without needing the entire embedded App Bridge roundtrip.

**Comment by iwoodruff** [comment]
within the last year we've added a hot reload for embedded apps built with shopify CLI. tooling for easier local development is something we hear frequently & are tracking though. thanks for flagging!

**Comment by marcusstenbeck** [comment]
Hot reload doesn't solve this issue. Is there another issue open where we can track progress on this active issue? If not, this issue should not be closed since it is still an active open issue.
