### ISSUE TITLE
Issue with opening Custom App on POS

### ISSUE THREAD

**Issue by sunriseshoapeng** [Shopify/shopify-app-bridge#122]
## Describe the bug

In my custom app, it basically has two sides to the app. One for admin + one for POS. Depending on where the app is opened, we will direct the user to a different location. On the custom app itself when opening from POS, it will sometimes redirect to Admin and sometimes to POS. Why does this happen? 

Here is the code used to differentiate between admin and pos. I basically get the state from app bridge and if it contains pos.user and pos.location then redirect to POS. Is there a better way of doing this functionality?

```
app.getState().then((data) => {
          if (!data) {
            return;
          }
          // Direct user to location of app based on what is received
          if (data.pos?.user && data.pos?.location) {
           router.push("/pos");
          } else {
            router.push("/admin");
          }
        });
```

### To Reproduce

Steps to reproduce the behaviour:

1. Launch a custom app with this logic from POS

### Expected behaviour

When opening from POS, it redirects to POS directly.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `2.0.8`
- `@shopify/app-bridge-react` @ `2.0.2`
- `@shopify/polaris` @ `7.5.0`

## Platform

- OS: Windows
- App: Shopify POS

**Comment by henrytao-me** [comment]
Hi @sunriseshoapeng 

This happens possibly because POS sends user and location after your script is called. Our recommendation to determine if it's POS or Shopify Mobile is to use utils here https://shopify.dev/apps/tools/app-bridge/methods#platform-methods

Let me know if the utils work for you. I close this issue for now 🙇
