### ISSUE TITLE
POS embedded apps redirect to Shopify Admin page on initial session load (ongoing since version 7.x)

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#129]
## Describe the bug

Ever since Shopify POS 7.x, POS users are seeing sensitive Shopify Admin data on the first load of the day of the POS app. This bug has been going on for nearing 3 months now. 

### To Reproduce

This happens on the first load of the day typically, or after a merchant hasn't used Shopify POS / an app for a long time. 

## Contextual information

More discussion and screenshots: https://shopifypartners.slack.com/archives/C010HGLJHFY/p1653062084967679

## Platform

Shopify POS version 7.x (the image below is from a merchant today using 7.3.1). 

![Screen Shot 2022-07-26 at 7 50 52 AM](https://user-images.githubusercontent.com/46724607/181045130-33ec559f-d25a-4a10-a6bc-b767677dcdce.png)

**Comment by derrickrc** [comment]
Hi team we are approaching 4 months of since this bug was first reported and it is still impacting merchants. Is there any ETA on when this will be fixed? Thanks.

**Comment by derrickrc** [comment]
Hey @js-goupil, unfortunately we are still seeing this bug happen and receiving reports of it happening. I was on a FaceTime yesterday with a merchant troubleshooting an unrelated issue, and saw this happen with my own eyes. 

Shopify POS 8.1.0, iPad 9th generation. iOS 16.2. Happy to share the shop details as well if it's helpful - thanks and sorry about this!

**Comment by henrytao-me** [comment]
Hi @derrickrc, fyi POS team is pushing a fix for this in the next release. 🙇

**Comment by henrytao-me** [comment]
I believe the fix hasn't been merged yet.

**Comment by NathanJolly** [comment]
Hi @peter-visualsquares, thank you for the update. Would you send any videos or screenshots you have to app-bridge@shopify.com, please?

We're looking to deduce the issue, so any steps to reproduce the issue or any sort of consistency you can offer would be helpful. Thank you!

**Comment by henrytao-me** [comment]
Heads up: POS team has merged a change attempting to fix this issue. It should be available on the Apps Store for the upcoming release. We will ping here when it's live.

**Comment by vctrchu** [comment]
Version 8.7 of POS should live next monday. Please check for the fixes then. Thanks.

**Comment by derrickrc** [comment]
@vctrchu @henrytao-me unfortunately this issue does not appear to be fixed, any update?

**Comment by vctrchu** [comment]
@henrytao-me I believe this is being looked into. Any updates?

**Comment by henrytao-me** [comment]
I didn't have time to look into this last week. It's still on my list though 🙇
