### ISSUE TITLE
Cannot open scanner in POS App

### ISSUE THREAD

**Issue by jeffblake** [Shopify/shopify-app-bridge#130]
## Describe the bug

Using the sample code provided from https://shopify.dev/apps/tools/app-bridge/actions/scanner

The scanner does not open at all, and no errors are logged.

### To Reproduce

Using the following code:

```
import React from 'react';
import createApp from '@shopify/app-bridge';
import {Provider} from '@shopify/app-bridge-react';
import {Group, Scanner, Features} from '@shopify/app-bridge/actions';
import {AppProvider, Page} from '@shopify/polaris';
import '@shopify/polaris/build/esm/styles.css';

// window.addEventListener("error", (event) => {
//   alert(event.message);
// });

window.addEventListener("unhandledrejection", (event) => {
  alert(event.reason.message);
});

window.addEventListener("error", handleError, true);

function handleError(evt) {
    if (evt.message) { // Chrome sometimes provides this
      alert("error: "+evt.message +" at linenumber: "+evt.lineno+" of file: "+evt.filename);
    } else {
      alert("error: "+evt.type+" from element: "+(evt.srcElement || evt.target));
    }
}

function MyApp() {

  const container = document.getElementById('app');
  const data = container.dataset;
  const shopOrigin = data.shopOrigin;
  const host = data.host;

  const config = {
    apiKey: data.shopifyKey,
    //shopOrigin: shopOrigin,
    host: host
  };

  const app = createApp({
    apiKey: data.shopifyKey,
    host: host,
  });
  var scanner = Scanner.create(app);

  var features = Features.create(app);

  scanner.subscribe(Scanner.Action.CAPTURE, function(payload) {
    // The payload will contain `scanData`, a string representation of the data scanned.
  });
    
  const res1 = features.dispatch(Features.Action.REQUEST, {
    feature: Group.Scanner,
    action: Scanner.Action.OPEN_CAMERA //
  });
  setRes(res1)

  features.subscribe(Features.Action.REQUEST, function (payload) {
    alert(payload)
    if (payload.feature[Scanner.Action.OPEN_CAMERA]) {
      var available = payload.feature[Scanner.Action.OPEN_CAMERA].Dispatch;
      // If the Camera Scanner actions were enabled, open a Scanner
      if (available) {
        scanner.dispatch(Scanner.Action.OPEN_CAMERA)
      } else {
        alert('Camera not available')
      }
    }
  });
  
  let result = scanner.dispatch(Scanner.Action.OPEN_CAMERA);
  
  return (
    <AppProvider>
      <Provider config={config}>
        <Page narrowWidth title="Test">
        </Page>

      </Provider>
    </AppProvider>
  );
}
```

### Expected behaviour

The scanner appears or a useful error message is logged.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.1.4`
- `@shopify/app-bridge-react` @ `3.1.4`
- `@shopify/polaris` @ `9.22`

## Platform

- OS: iOS
- OS Version: 15.5
- App: Shopify POS

### Additional context

React 17

**Comment by jeffblake** [comment]
I've tried every possible combination of requesting feature access or not, pre-approving camera by tapping the icon next to search bar, etc

**Comment by jeffblake** [comment]
Any news on getting this fixed?

**Comment by jeffblake** [comment]
Any update on this? I've updated to the latest POS and App bridge versions, still no fix.

**Comment by henrytao-me** [comment]
Hi @jeffblake 

We identified the problem and working on the fix now. In the meantime, if merchant is asking for the a temporary workaround, you can tell them to enable camera permission 1st by pressing on the barcode scanner icon on the home screen top bar. Then, the embedded app should be able to use scanner action. 

We will post here when the fix is rolling out 🙇

**Comment by jeffblake** [comment]
Thanks @henrytao-me - much appreciated. That's odd though, because I did test that method before I posted the bug report and it still didn't work.

**Comment by jeffblake** [comment]
Any update?

**Comment by jeffblake** [comment]
@henrytao-me Any news? Eager to get this working.

**Comment by heltisace** [comment]
Hi @jeffblake. We looked into this again but couldn't find a problem, everything appears to function as expected. 

## Code
This is the scanner code I ran to test this. This is pretty much the same code from the documentation you are using. As you can see all the events are being fired correctly. 
<img width="915" alt="Screen Shot 2022-11-04 at 12 14 25 PM" src="https://user-images.githubusercontent.com/22798968/200024280-ce5af8a9-babb-4e5b-a5d9-d7250b0d501a.png">

## Result

Running that results in this screen for me, which is the desired behavior:
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-11-04 at 12 14 35](https://user-images.githubusercontent.com/22798968/200024293-19cd9c9d-d3ac-4b47-ab13-bc2b7ff09bab.png)

## Conclusion

Can you test just the Scanner functionality in a newly created app and make sure both your app's dependency and POS are up to date? Let me know if this is still broken for you after that.

**Comment by jeffblake** [comment]
Finally figured it out...

`Features.Action.REQUEST_UPDATE` is marked as deprecated, so I was using `Features.Action.UPDATE`, but only the deprecated one works.

Also needed to get the host parameter unmodified from Shopify, before I was base 64 encoding the shop domain myself.
