### ISSUE TITLE
WebVitals init fails in app bridge init, killing the init process

### ISSUE THREAD

**Issue by njokipal** [Shopify/shopify-app-bridge#145]
## Describe the bug

Using `3.3.x` versions of the `@shopify/app-bridge`, calling `createApp()` will throw `TypeError: web_vitals_1.onLCP is not a function` killing the app bridge init as we have the call inside a `try...catch` where catching an error will just display an error state.

App is created using `create-react` with manually added Shopify deps

### To Reproduce

Steps to reproduce the behaviour:

0. Have `@shopify/app-bridge` at `3.3.0`, 
1. Launch the app `$ npm run start`
2. Have `createApp()` inside `try...catch`

### Expected behaviour

If WebVitals isn't essential, no exceptions were thrown if the package cannot for some reason initialise it's internals. Just report a problem and continue.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.3.0`
- `@shopify/polaris` @ `10.3.3`
- `web-vitals` @ `3.0.2`

WebVitals is additionally registered by our own app. It makes no difference, if it is included or not to the error case

## Platform

- OS: Linux
- OS Version: (`uname -r`) 5.19.9-arch1-1

### Additional context

Node.js 16, React app created using create-react, manually added Shopify deps

**Comment by charlesdobson** [comment]
Hi @njokipal!

Could you please try this out with `v3.3.2` and let me know if you're still experiencing an issue?

**Comment by njokipal** [comment]
Excellent, `3.3.2` actually works. I'm fairly certain I tried all the `3.3.x` minors available before reporting the issue, but it might be that my `node_modules` or the React developer mode just didn't actually load the proper version.

Closing. Thanks @charlesdobson

**Comment by charlesdobson** [comment]
Nope, you were correct! I made a quick fix and published it in 3.3.2. Thanks for reporting the issue!

**Comment by mhaseebullah92** [comment]
@charlesdobson facing this issue on my local, using ngrok to debug the Shopify app locally. 

@shopify/app-bridge-react @ ^3.7.7
@shopify/polaris @ ^10.49.1
web-vitals @ ^2.1.4
react @ ^18.2.0 

NodeJS @ v18.16.0
OS: Windows 10

Error on the console: App-Bridge failed to initialize web-vitals TypeError: web_vitals_1.onLCP is not a function

**Comment by mhaseebullah92** [comment]
@charlesdobson facing this issue on my local, using ngrok to debug the Shopify app locally. I tried the above versions but it's not working. 

@shopify/app-bridge-react @ ^3.7.7
@shopify/polaris @ ^10.49.1
web-vitals @ ^2.1.4
react @ ^18.2.0 

NodeJS @ v18.16.0
OS: Windows 10

Error on the console: App-Bridge failed to initialize web-vitals TypeError: web_vitals_1.onLCP is not a function

**Comment by mhaseebullah92** [comment]
@rahul-adnabu now I am using @shopify/app-bridge-react @ 3.1.0 because this version is not dependent on web-vitals. but still facing the same issue on the latest version. This issue is closed now I am creating a new issue for it.

**Comment by rahul-adnabu** [comment]
@mhaseebullah92 isn't web vitals necessary for shopiify to track lcp, cls?

**Comment by mhaseebullah92** [comment]
I opened a new bug https://github.com/Shopify/shopify-app-bridge/issues/206 for this issue.

**Comment by mark-barrett** [comment]
Also having this issue. The app was working yesterday during development, but without changing anything, we are getting the same.

**Comment by 19-05-1999** [comment]
when i try to run my shopify app , i get this error in the console " TypeError: o.onLCP is not a function" , i try the google search but still not able to find the solution , plz help me if you can.

**Comment by BusyginArtem** [comment]
I have the same issue. Did anybody solve this issue?
