### ISSUE TITLE
useNavigate hook to a given Order won't work

### ISSUE THREAD

**Issue by mxp-qk** [Shopify/shopify-app-bridge#148]
## Describe the bug

The useNavigate hook should allow to
> Navigate to Shopify admin by using a section name and an optional resource ID.

The given exemple works well for a given collection but when trying to navigate to a given order the hook won't work
```jsx
// OK
<Link
  onClick={() =>
    navigate({ name: "Collection", resource: { id: "123" } })
  }
>
  Order Number
</Link>
<Link
  onClick={() =>
    navigate({ name: "Order" })
  }
>
  Order Number
</Link>

// NOK
<Link
  onClick={() =>
    navigate({ name: "Order", resource: { id: "123" } })
  }
>
  Order Number
</Link>
```

[Doc](Navigate to Shopify admin by using a section name and an optional resource ID.)

### To Reproduce

Steps to reproduce the behaviour:

1. Launch the app with a link to a given order
2. Click on the link
3. See error

### Expected behaviour

The link should navigate to the order page

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.1.0`
- `@shopify/app-bridge-react` @ `3.1.0`
- `@shopify/polaris` @ `9.11.0`

## Platform

- OS: MacOS
- OS Version: 12.4
- App:Shopify Admin on Chrome 105.0.5195.125

**Comment by charlesdobson** [comment]
Hi @mxp-qk!

Are you able to upgrade to the latest versions and try again? That's version `3.3.2`. I'm not currently able to reproduce the issue (I can navigate to an individual order page okay).

**Comment by mxp-qk** [comment]
Hi @charlesdobson,

I bootstrap the project with `npm init @shopify/app@latest` two days ago so I didn't check the latest version, my bad.

It didn't solve the issue but this did : 
```jsx
<Link
  onClick={() =>
    navigate({ name: "Order", resource: { id: id.toString() } })
  }
>
  Order Number
</Link>
```

In my example and working test the id was a primitive string but in my real use cas the id come from the API and was a number.
