### ISSUE TITLE
Mac Console debugging for App Bridge apps on iOS - broken since POS Next

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#149]
Please see: https://shopify.dev/apps/tools/app-bridge/debugging#debugging-app-bridge-apps-on-an-ios-device

This feature has been broken ever since POS Next, it would be helpful to get this feature back. Thank you.

**Comment by samiulmonir06** [comment]
Hello @derrickrc ,

We have released this feature with `version 7.9.0`.  Can you please update and verify if its working as expected.
