### ISSUE TITLE
App Bridge Cart action - add custom sale line item with no tax, or custom tax amount

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#15]
### Describe the feature you’d like

There is currently no way to add a custom sale line item using App Bridge Cart actions without the default tax applied. We would like to be able to add tax-exempt line items, or a tax override amount. 

### Describe alternatives you've considered

A hacky workaround for these cases is to create a moment-in-time shadow product variant (e.g., with taxable set to false) and add this to the cart; however, this necessitates later deleting the shadow variant. This hack also does not work on Android POS without an (unacceptable) built-in delay as the client can't pick it up quickly enough. 

### Additional context

Add any other context about the feature request here.

**Comment by andrewapperley** [comment]
That’s correct

**Comment by andrewapperley** [comment]
Fixed
