### ISSUE TITLE
Navigation on app title in side menu does not work on mobile

### ISSUE THREAD

**Issue by kaarelss** [Shopify/shopify-app-bridge#157]
## Describe the bug

Navigation on app title does not work on mobile in side navigation menu.

### To Reproduce

Steps to reproduce the behaviour:

1. Create a new Shopify bootstrap application, following your own tutorial: https://github.com/Shopify/shopify-app-template-ruby/blob/main/README.md
2. Open app in mobile, or toggle device toolbar in browser console
3. Navigate to 'Page name'
4. Navigate back to Home/Landing page clicking on App title in side navigation menu

<img width="368" alt="Screenshot at Oct 25 09-30-07" src="https://user-images.githubusercontent.com/11540218/197699297-3bb05fc4-178e-42db-b94a-abd43b01845f.png">

### Expected behaviour

It should navigate home when clicking on app title in side navigation menu on all devices.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `^3.1.0`
- `@shopify/app-bridge-react` @ `^3.1.0`
- `@shopify/app-bridge-utils` @ `^3.1.0`
- `@shopify/polaris` @ `^9.11.0`
- `react-router-dom` @ `^6.3.0`

## Platform

- OS: iOS
- OS Version: 15.6.1
- App: Safari

@itissible/matrixify

**Comment by henrytao-me** [comment]
I tested again on production. This issue is fixed. Feel free to reopen if it is not the case 🙇
