### ISSUE TITLE
Optimized mobile loading - getSessionToken does not resolve when new token is about to be issued

### ISSUE THREAD

**Issue by galmis** [Shopify/shopify-app-bridge#163]
## Describe the bug

When optimized mobile loading is enabled, `getSessionToken` does not resolve if called at the end of token's life cycle (unless the `getSessionToken` function is called again when the token is available).

The issue affects the `authenticatedFetch` utility function, which I'm assuming, is relying on the `getSessionToken` under the hood.

### To Reproduce

Steps to reproduce the behaviour:

1. Enable ["Optimized loading on mobile devices".](https://shopify.dev/apps/tools/app-bridge/optimized-loading)
2. Open an embedded app in Shopify Admin mobile app.
3. Call `getSessionToken` at the end of token's life cycle (e.g. ~50+ seconds after it was issued). The following snippet and the attached console log highlight the issue.

```
  const app = useAppBridge();

  useEffect(() => {

    const intervalMs = 20000;

    const interval = setInterval(async() => {

      const requestTime = new Date().toISOString();
      // @ts-ignore
      console.log(`${requestTime} request session token`);

      try {
        const token = await getSessionToken(app);
        // @ts-ignore
        console.log(`${new Date().toISOString()} session token - ${token}, requestTime - ${requestTime}`);
      } catch(e) {
        console.error(`getSessionToken failed, requestTime - ${requestTime}`);
      }

    }, intervalMs)

    return () => {
      console.log(`clearing interval...`);
      clearInterval(interval);
    }
  }, [app]);
```
![Screenshot 2022-12-18 at 14 21 20](https://user-images.githubusercontent.com/7953238/208304768-a3d58530-3ac1-4e50-9a1b-b1163ab84aab.png)

### Expected behaviour

Ideally, `getSessionToken` should always resolve with a session token. At the very least, I'd expect `getSessionToken` to throw an error if the token can't be issued. 

### Packages and versions

- `@shopify/app-bridge-utils` @ `3.5.0`

## Platform

- OS: iOS, Android
- App: Shopify Mobile

### Additional context

Next.js embedded app created with Shopify cli 2. 

The issue isn't reproducible when the optimized mobile loading is disabled. I've mainly tested this on Android 11 but noticed the same side effects on iOS 16.1.1. I couldn't reproduce it on iPad 15.1, though.

**Comment by henrytao-me** [comment]
@janklimo @galmis can I know what version of Shopify Mobile you are using?

**Comment by henrytao-me** [comment]
I believe that the issue has been fixed in the latest version of Shopify Mobile 9.94.0. Feel free to reopen if necessary. Thanks for reporting this issue 🙇
