### ISSUE TITLE
Unexpected routing when the app is hosted behind a subfolder

### ISSUE THREAD

**Issue by bibiseb** [Shopify/shopify-app-bridge#166]
## Describe the bug

I host my dev app behind a subfolder like https://{someId}.eu.ngrok.io/shopify. When I click on the first item of the app menu it appends /shopify to the url and the app loads the NotFound.jsx page instead of the index.jsx.

If I click another menu item, let's say /about, it successfully loads the about.jsx page. But if I refresh the browser (CTRL+R) the app receives a 404 response from the server because Shopify tries to load https://{someId}.eu.ngrok.io/about instead of https://{someId}.eu.ngrok.io/shopify/about.

### To Reproduce

Steps to reproduce the behaviour:

1. Host a new app behind a subfolder like /shopify
2. Install it on your development store
3. Try to navigate in the app menu

### Expected behaviour

When you click on the first menu item of the app the index.jsx should be displayed.
When you refresh another page the app should load the appropriate url.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.5.0`
- `@shopify/app-bridge-react` @ `3.5.0`
- `@shopify/app-bridge-utils` @ `3.5.0`
- `@shopify/polaris` @ `9.24.0`

## Platform

- OS: MacOS
- OS Version: 10.15.7
- App: Chrome

### Additional context

Here is my BrowserRouter configuration:

`<BrowserRouter basename={"/shopify"}>
  <AppBridgeProvider>
    <QueryProvider>
      <NavigationMenu
        navigationLinks={[
          {
            label: "About",
            destination: "/about",
          },
        ]}
      />
      <Routes pages={pages} />
    </QueryProvider>
  </AppBridgeProvider>
</BrowserRouter>`

**Comment by henrytao-me** [comment]
@bibiseb this is expected. Regardless the path in application url, Shopify will only get the domain to construct absolute url for all menus. We don't have plan to change this behavior.

**Comment by slince** [comment]
hello everyone, 

i'm very sorry that I resurrected a long-dead issue. 
i also found the problem. If basename is set in react router, the url generated by`NavigationMenu` will not work as expected：

```javascript
<BrowserRouter basename="/shopify">
    <Routes>
    ...
     </Route>
</BrowserRouter>
```
The links generated by `NavigationMenu` will always have duplicate prefixes `/shopify/shopify/xxx`
but this is okay

```javascript
<BrowserRouter>
    <Routes>
        <Route path="/shopify">
         ...
        </Route>
    </Routes>
</BrowserRouter>
```
I think this is not elegant and flexible enough. Is there any other solution @henrytao-me  @kris-tremblay
