### ISSUE TITLE
Infinite scroll not working on product picker

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify-app-bridge#171]
## Describe the bug

In the Product Picker, when you reach the bottom of the list, it no longer loads additional products.

### To Reproduce

1. Open the Product Picker on any app that uses it (Shop codes, for example)
2. Scroll all the way down.
3. See how it no longer loads additional items (i.e. infinite scrolling).

### Expected behaviour

The product picker should be able to infinite scroll, so the user can view all items.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.5.0` +

## Platform

Web, Chrome.

### Additional context

Reported this bug today via Shopify Support and was advised to post here. This issue potentially affects all apps that use this picker. The issue was first reported to me, by a merchant.

**Comment by bratsos** [comment]
Hi @flavio-b and thanks for the report! This is an internal issue on Shopify - we're working on a fix. I'll let you know here about the progress. Thanks!

**Comment by discountninjaradu** [comment]
FYI: also affected by this issue. Tracking progress.

**Comment by jmiguelsamper** [comment]
We also reported this issue to Shopify Support one week ago. No response yet.

It happens to apps using the ResourcePicker but it **can also be reproduced directly in the Shopify Admin**, if you go to a manual collection and click the 'Browse' button to select products. Of course, you need a big number of products on your store, a couple of hundreds to reproduce it properly.

**Comment by flavio-b** [comment]
@jmiguelsamper, this one is taking too long. Usually these kinds of issues that affect many apps are resolved quickly. I'm not sure why it's been this long without a resolution. This is affecting all our customers.

**Comment by flavio-b** [comment]
It looks like the problem has been resolved, as of last night. I'll close the issue for now.
