### ISSUE TITLE
Scanner.Action.CAPTURE  not firing?

### ISSUE THREAD

**Issue by dgtlmonk** [Shopify/shopify-app-bridge#172]
## Describe the bug

Subscription to `Scanner.Action.CAPTURE` is not firing, while other Actions subscription like `Cart.Action.UPDATE` is working as expected.

### To Reproduce

Steps to reproduce the behaviour:

```js
  const app = useAppBridge();
  const scanner = Scanner.create(app);

  // THIS IS NOT FIRING :-/
  scanner.subscribe(Scanner.Action.CAPTURE, payload => {
    window.alert('scanner captured ', payload.scanData)  
  });

  scanner.dispatch(Scanner.Action.OPEN_CAMERA)
```

### Expected behaviour

subscription to `Scanner.Action.CAPTURE` event should trigger

## Contextual information
I have a simple POS extension app that utilizes [Scanner Action](https://shopify.dev/apps/tools/app-bridge/actions/scanner) to read barcode. The camera is opening fine and I can see the captured barcode value from the built-in Shopify Scanner functionality, but the "capturing" event subscription in my code is not being called. I tried other Actions like `Cart.Action.UPDATE` and I was able to receive the subscription event.

### Packages and versions
- `@shopify/app-bridge` @ `^3.1.0`
- `@shopify/app-bridge-react` @ `^3.1.0`
- `@shopify/polaris` @ `9.11.0`
- `react` @ `^17.0.2`
- `react-dom` @ `^17.0.2`
- `@shopify/app` @ `3.34.0`
- `@shopify/cli` @ `3.34.0`

## Platform
- OS: iOS / Android
- OS Version: iOS 16.1.2 / Android 12
- App:  Shopify POS

### Additional context

The app is purely created with shopify-cli no modifications (NodeJS/React)

**Comment by dgtlmonk** [comment]
Thank you @pramodparanthaman. This is a confirmed workaround

**Comment by henrytao-me** [comment]
@charles-tyler May I know what Shopify Mobile version and OS that you are using? 🙇

**Comment by henrytao-me** [comment]
Thanks @charles-tyler for more info. 

> The workaround app.subscribe was working for both Shopify Mobile and Shopify POS. This then got reported as not working well by our users when we upgraded to "Optimize loading on mobile" -> The scanner returned the payload multiple times.

👀  Let me investigate this


> We tried to turn off "Optimize loading on mobile" but this caused the Shopify Mobile app to crash when the scanner was opened on the most recent version of the Shopify Mobile app.

✅ We identified a bug with latest release of Shopify Mobile iOS when mobile optimize feature is OFF. The fix has been merged and should be available publicly in the next release.

> We then turned "Optimize loading on mobile" back on, and went back to scanner.subscribe which is working again as desired in Shopify Mobile. However on Shopify POS the payload is not returned as expected. A toast appears with the result instead of being usable.

👀 I will also investigate this `scanner.subscribe` should work UNLESS you dispatch and subscribe with different scanner object. There is an internal id for each app-bridge action. For example, below code won't work:

```ts

// This code won't work
var scanner = AppBridgeScanner.create(...);
scanner.subscribe(...)
scanner = AppBridgeScanner.create(...);
scanner.dispatch(...)

// This code will have race condition because you dispatch before subscribing
var scanner = AppBridgeScanner.create(...);
scanner.dispatch(...)
scanner.subscribe(...)

// This code should work (unless there is a bug on our side 🤞 => will look into it)
var scanner = AppBridgeScanner.create(...);
scanner.subscribe(...)
scanner.dispatch(...)
```

**Comment by pramodparanthaman** [comment]
Adding a 500ms delay between calls to the app-bridge scanner fixed this on iOS Shopify POS in my app.
https://apps.shopify.com/picklist
