### ISSUE TITLE
Please fix npmjs.com links and publish change logs

### ISSUE THREAD

**Issue by pgib** [Shopify/shopify-app-bridge#173]
### Describe the feature you’d like

1. The Repository (`@shopify/app-bridge` and `@shopify/app-bridge-react`) and Homepage (`@shopify/app-bridge-react` only) links in the published npm packages are broken. [@shopify/app-bridge](https://www.npmjs.com/package/@shopify/app-bridge) [@shopify/app-bridge-react](https://www.npmjs.com/package/@shopify/app-bridge-react)
2. You don't publish any change log, so it's impossible to know fixes or surprises lie in store should we update!

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/13967/214709098-3890089c-ea9c-4864-b420-b9988a3614c3.png">

### Describe alternatives you've considered

I don't see any alternatives here.

### Additional context

Please put yourself in the shoes of developers of your platform who do not work at Shopify.

**Comment by darrynten** [comment]
if there was a changelog i wonder if it would mention or explain what happened to app-bridge-utils and what we need to use instead now that it's deprecated

**Comment by jzazove** [comment]
This is fixed.
