### ISSUE TITLE
admin.shopify.com change causing hostOrigin to be the same across all stores

### ISSUE THREAD

**Issue by gil--** [Shopify/shopify-app-bridge#177]
## Describe the bug

Unable to retrieve the myShopify url via hostOrigin on latest app bridge as Shopify now returns https://admin.shopify.com for all stores. Can we fix this or introduce a new parameter to assist with retrieval of the shop url.

### To Reproduce

Steps to reproduce the behaviour:

Use `@shopify/app-bridge-react` and:

```jsx
    const app = useAppBridge();
    const redirect = Redirect.create(app);
    const hostOrigin = redirect.hostOrigin;
```

hostOrigin will be https://admin.shopify.com.

![image](https://user-images.githubusercontent.com/3484527/218329956-2370f655-abc2-4f16-9374-ecc3400da0cb.png)

### Expected behaviour

I'd expect host origin to be the shop's url. Otherwise, please surface myshopify as a new parameter.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.7.2`
- `@shopify/app-bridge-react` @ `3.7.2`
- `@shopify/polaris` @ `^10.27.2`

## Platform

- OS: [for example MacOS, Windows, iOS, Android]
- OS Version: [for example 10.15.5]
- App: [for example Shopify Mobile, Shopify POS, Chrome, Safari, Firefox]

### Additional context

Add any other context about the problem here, such as your app’s configuration (Node, Next.js, Rails).

**Comment by joeyfreund** [comment]
Hi @gil-- , thanks for bringing it up.

The `hostOrigin` property wasn't meant to be part of App-Bridge's public API. Unfortunately, we didn't make it explicit.      
([Hyrum's Law](https://medium.com/se-101-software-engineering/what-is-the-hyrums-law-and-why-should-software-engineers-care-9bd98fbe74da#:~:text=The%20law%20says%20that%3A,be%20depended%20on%20by%20somebody.) never gets old).

In any case, There are multiple ways to get the myshopify.com domain:

 1. When your app loads, Shopify sends it as the `shop` query string parameter.
 2. From [the session token](https://shopify.dev/docs/apps/auth/oauth/session-tokens#payload) (you'll need to decode the token first, [`jwt-decode`](https://www.npmjs.com/package/jwt-decode) or any similar library will do the trick)


Please let me know if this solves your problem.

**Comment by joeyfreund** [comment]
Closing this. 
@gil-- , if you have any follow-up questions, please feel free to re-open this issue.

**Comment by henrytao-me** [comment]
@CodaemonHaroon Can I have the app id? I can take a look. It's not a sensitive info but if you don't want to send it here, you can ping me on partners slack.

**Comment by henrytao-me** [comment]
I don't have experience with the PHP library. I am afraid that I cannot help much here.
