### ISSUE TITLE
Improved debugging / logging when using mobile optimized loading?

### ISSUE THREAD

**Issue by ascherkus** [Shopify/shopify-app-bridge#178]
### Describe the feature you’d like

The old WebView-based container for embedded apps was easier to debug. For example, on Android you could use adb logcat to see console logs and errors. With the new Unframed Frameless Shopify Mobile user agent I'm finding it much more of a black box development experience (e.g., nothing shows up in adb logcat) and I'm relying on alert() statements.

I'm also not seeing the Settings > Partner > WebView Debugging setting anymore on v9.98.1 as referenced in https://shopify.dev/docs/apps/tools/app-bridge/debugging

### Describe alternatives you've considered

I've tried adb logcat and Chrome Remote Debugging for Android. The former doesn't show anything, and the latter doesn't work since the Unframed Frameless Shopify Mobile user agent isn't part of Chrome and/or I can't find a way to enable WebView Debugging.

**Comment by henrytao-me** [comment]
The fix is merged. It should be available in the next release. I close this for now and re-open if needed 🙇
