### ISSUE TITLE
Feature Detection - Issue with fetching cart on both Android and IOS.

### ISSUE THREAD

**Issue by michalkuchtapl** [Shopify/shopify-app-bridge#180]
HI!

We can't fetch cart in our POS app. It says: APP::ERROR::PERMISSION.

I tried solution from #105 and the app loads infinitely without issue, it's waiting for **Features.Action.UPDATE**. I waited 5 minutes and nothing happend.

### To Reproduce

This is the code that I used:

`
   useEffect(() => {
        cart.subscribe(Cart.Action.UPDATE, function (cart) {
            console.log(cart);
        });

        var cartFeaturesAvailable = new Promise((resolve) => {
            function checkCartFeatures() {
                return app.featuresAvailable(Group.Cart).then(function (state) {
                    var _ref = state.Cart && state.Cart[Cart.Action.FETCH]
                        , Dispatch = _ref.Dispatch;
                    return Dispatch;
                });
            }

            checkCartFeatures().then(function (isCartAvailable) {
                if (isCartAvailable) return resolve();
                app.subscribe(Features.Action.UPDATE, function () {
                    checkCartFeatures().then(function (isCartAvailable) {
                        if (isCartAvailable) return resolve();
                        console.log('Not fetch yet');
                    });
                });
            });
        });

        // This can be call multiple times whenever you need to fetch cart because the cartFeaturesAvailable promise is resolved
        cartFeaturesAvailable.then(function () {
            cart.dispatch(Cart.Action.FETCH);
        });
    }, []);
`

### Expected behaviour

I expect to see cart content in the console log, or at least "Not Fetched yet" message.
### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@sentry/react` @ `7.33.0`
- `@shopify/app-bridge` @ `3.7.2`
- `@shopify/app-bridge-react` @ `3.7.0`
- `@shopify/app-bridge-utils` @ `3.5.0`
- `@shopify/polaris` @ `10.23.0`
- `react` @ `18.2.0`

## Platform

- OS: Android
- OS Version: 13
- App: Shopify POS

**Comment by michalkuchtapl** [comment]
Hi!

This is the application minimum:

```
export default function MyApp() {
    const app = useAppBridge();
    const cart = Cart.create(app);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        setLoading(true);
        loadData();
    }, []);

    const loadData = () => {
        cart.subscribe(Cart.Action.UPDATE, function (cart) {
            setLoading(false);
            console.log(cart);
        });

        var cartFeaturesAvailable = new Promise((resolve) => {
            function checkCartFeatures() {
                return app.featuresAvailable(Group.Cart).then(function (state) {
                    var _ref = state.Cart && state.Cart[Cart.Action.FETCH]
                        , Dispatch = _ref.Dispatch;
                    return Dispatch;
                });
            }

            checkCartFeatures().then(function (isCartAvailable) {
                if (isCartAvailable) return resolve();
                app.subscribe(Features.Action.UPDATE, function () {
                    checkCartFeatures().then(function (isCartAvailable) {
                        if (isCartAvailable) return resolve();
                        console.log('Not fetch yet');
                    });
                });
            });
        });

        // This can be call multiple times whenever you need to fetch cart because the cartFeaturesAvailable promise is resolved
        cartFeaturesAvailable.then(function () {
            cart.dispatch(Cart.Action.FETCH);
        });
    }
}
```

**Comment by henrytao-me** [comment]
@michalkuchtapl Can you give me the appId, dev and prod store? You can dm me on partners slack if you don't want to share here 🙇

**Comment by michalkuchtapl** [comment]
We found a solution and the source of the issue.

Basically, I tried to open the app by going to Setting -> All apps -> MyApp
That was not working, because apps listed in that list dosen't have permissions to cart.

The solution for that is just to open our app by tile on the home screen.
