### ISSUE TITLE
Breaking change to scanner functionality 

### ISSUE THREAD

**Issue by charles-tyler** [Shopify/shopify-app-bridge#181]
## Describe the bug

We are still facing an issue with the POS scanner that it is not returning the barcode value as expected. 

**Plus** a new issue seems to have arisen with the App Bridge scanner mid-last week (seems to be in line with version 9.99.0).

When scanning a UPC-A barcode with 12 characters the Scanner feature seems to convert this to an EAN13 barcode (adding an extra leading character) - but only for the App bridge version of the scanner (?!). 
It doesn’t add this for the scanner accessed within Shopify Mobile POS or Shopify Mobile app for Shopify functions.

This is a **breaking change** and is costing users time because the value received from the App bridge scanner is different from what it was previously.

Please contact me for videos highlighting this issue.
An example UPC-A barcode for reference.
![example product barcode](https://user-images.githubusercontent.com/61411262/221945188-a570b95e-a9ac-4dc2-8f4a-546ccad1386a.jpeg)

<img width="863" alt="074261041218" src="https://user-images.githubusercontent.com/61411262/221947339-5de6c2e4-0ec7-45ec-8089-33fd1d64c3ce.png">

### To Reproduce

1. Launch Shopify mobile app
2. Click "Products"
3. Select a product
4. Select a variant
5. Click "More" next to **Inventory**
6. Click the barcode symbol next to "Barcode (ISBN, UPC, etc.)"
7. Scan UPC-A barcode 
8. Value returned is as expected `074261041218`

**Bug**
1. Open an app using the App Bridge scanner
2. Scan the same barcode above
3. Value returned is `0074261041218` (extra leading zero)

### Expected behaviour

The returned value should be what the barcode represents! There shouldn't be extra characters introduced. 

### Packages and versions

- `@shopify/app-bridge` @ `3.7.0`
- `@shopify/app-bridge-react` @ `3.7.0`
- `@shopify/polaris` @ `6.2.0`

## Platform

- OS: iOS
- OS Version: 9.100.0
- App: Shopify Mobile and Shopify POS

### Additional context

Happy to share videos of the process - let me know!

**Comment by charles-tyler** [comment]
@avaz-shopify Please could you let me know when this is going to be implemented?

We have users that are not able to use the scanner and were using it in their work flow previously.

At the very least please can we learn about the logic you are referring to? Then we can add it as well.

**Comment by avaz-shopify** [comment]
> @avaz-shopify Please could you let me know when this is going to be implemented?
> 
> We have users that are not able to use the scanner and were using it in their work flow previously.
> 
> At the very least please can we learn about the logic you are referring to? Then we can add it as well.

The retail-succeed-build team that works on these extensions has taken this issue over. @heltisace, do you have any updates on this issue?

**Comment by ychahdoura** [comment]
@charles-tyler, since the appBridge using a third party barcode scanner different than the one that Shopify Admin app using, my approach is to unify the usage of the barcode scanner and make appBridge use the same barcode scanner as Shopify Admin app which will also solve this issue of the extra leading zero being returned for the UPC-A barcodes. This is the PR for the fix and please feel free to review and tested, let me know if you have any questions. This is the PR that fix the issue for the `AppBridge` Barcode Scanner.
