### ISSUE TITLE
App Bridge is causing all apps to hang - Server side issue?

### ISSUE THREAD

**Issue by TheSecurityDev** [Shopify/shopify-app-bridge#184]
## Describe the bug

App Bridge seems to be currently experiencing an issue where clicking on the navigation menu item for the app, or clicking Cancel on a Resource Picker causes the entire page to freeze. I reproduced this in multiple browsers and in multiple apps.

The entire page freezes up, and you can't run commands in the dev console. I think some kind of infinite loop is going on, or something else with the postMessage commands.

I suspect it's a server-side issue due to the fact that apps that were working before are experiencing the same issue, even in a different browser.

### To Reproduce

1. Open an embedded app.
2. Try to click a side navigation menu item, or
3. Open a Resource Picker and then click Cancel

Interestingly, those are the only things that I've noticed are broken. Other app bridge functionality seems to be working still.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.7.4`
- `@shopify/app-bridge-react` @ `3.7.4`

- `@shopify/app-bridge` @ `3.4.3`
- `@shopify/app-bridge-react` @ `3.4.3`

It started happening right after I upgraded app bridge, but then I tested it on my production app that has an older version that previously worked, and it still wasn't working. Then I tried a completely different app (Judge.me) and still experienced the issue. I tried in a separate browser that wasn't even signed in before and it still didn't work.

## Platform

- OS: Windows
- OS Version: 10
- App: Chrome, Firefox

### Additional context

NextJS app with React.

I should note that I've also been noticing an issue where the Shopify mobile app navigation menu items don't always work when you click on them, and it's very frustrating. I'm wondering if the issue is related.

**Comment by jfdha** [comment]
We are also seeing this on all our stores, though we noticed it with our app (which hasn't had code changes pushed to it in 3 weeks) it seems to be affecting all apps on the stores.

**Comment by jsanders92** [comment]
We are also seeing this in our stores due to the NavigationMenu component. Any workarounds to resolve this issue?

**Comment by jsanders92** [comment]
> Got this from Shopify support chat:
> 
> > i have looked into this for you, and yes, there appears to be an ongoing incident right now with exactly what you are experiencing. our technical team is currently on this as we speak and i will provide an update to you the soonest we have any resolutions for our merchants.
> 
> So it sounds like it's being worked on.

Thanks for looking into this with the shopify support and updating us!

**Comment by charlesdobson** [comment]
Hi folks! 👋🏼

We've identified the cause and shipped a fix to production for this.
Please let me know if you're still experiencing any issues! Closing this out for now.
