### ISSUE TITLE
Searching for products in the Resource Picker doesn't always work

### ISSUE THREAD

**Issue by tylerpharand** [Shopify/shopify-app-bridge#19]
## Describe the bug

Occasionally, when searching for products in the Resource Picker using the search bar, I'm unable to find the corresponding product. However, if I manually scroll down I'm able to find the product in question.

### To Reproduce

Steps to reproduce the behaviour:

1. Search for product the Resource Picker search bar
2. Note that the product doesn't show up
3. Able to find the product manually by scrolling down

### Expected behaviour

Should be able to consistently find the product being searched for.

### Packages and versions

- `@shopify/app-bridge` @ `1.27.2`
- `@shopify/app-bridge-react` @ `1.27.3`
- `@shopify/polaris` @ `5.8.2`

## Platform

- OS: MacOS
- App: Chrome (Shopify embedded application)

### Additional context

This is not consistently reproducible, but has been noticed several times by my team members.

**Comment by iainmcampbell** [comment]
Hi Tyler, could you provide more specific examples so we can reproduce the bug? We’d need the search string and the product it should find, for a specific shop. Also, whether you’re using the `initialQuery` option or not.

**Comment by tylerpharand** [comment]
Unfortunately I'm not able to reproduce to provide a solid example. I'll note that we aren't use the `initialQuery` option. I'll close this issue for now. Thanks!
