### ISSUE TITLE
Resourcepicker: How do I display all variants of a given ProductId?

### ISSUE THREAD

**Issue by Jarvie789** [Shopify/shopify-app-bridge#197]
### Describe the feature you’d like
`// How do I display all variants of a given ProductId? Thanks in advance!`
`<Resourcepicker resourceType="ProductVariant" initialQuery="productId:'gid://...'" ... />`
`// Dont Work...`

**Comment by dmhenry** [comment]
@Jarvie127 

I believe I was able to achieve you're desired result. The `id`s in `initialQuery` are the individual variant ids.
```java
<ResourcePicker
  open
  resourceType="ProductVariant"
  selectMultiple
  initialQuery="id:40255900844122 OR id:40255900876890 OR id:40255900909658"
/>
```

**Comment by charlesdobson** [comment]
Closing as stale. Please reopen if you're still having an issue!
