### ISSUE TITLE
Issue accessing Provider config in index.js or other files.

### ISSUE THREAD

**Issue by Iciren93** [Shopify/shopify-app-bridge#2]
## Describe the bug

Hello everyone,
New shopify developer, looking for some help, I am having an issue related to not being able to access global config value in my index.js assigned to <Provider> in _app.js.

Would appreciate it if anybody can point me in the right direction. Thank you

### To Reproduce

Steps to reproduce the behaviour:
Follow the tutorial below till you reach the index.js part and try to access Provider config in index.js
https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris

### Expected behaviour
Based on forum posting, those config values should be available in app-react-bridge context.

### Packages and versions
I am currently building a public embedded shopify app.

- `@shopify/app-bridge-react` @ `1.24.0`
- `@shopify/polaris` @ `4.26.1`

I would also like to point out that polaris syntax in the tutorial and documentation are quite different. Why is that so? It can be very confusing for someone new to shopify like me. Some are even marked deprecated, so how should we be using it going forward?
Let me know if you guys would need more information or is there something I have missed.

**Comment by iainmcampbell** [comment]
hi Iciren93, the global config values are loaded using the `dotenv` node package. this isn't a problem with the App Bridge library, so I’m going to close this issue (this repo is for App Bridge specifically). Double check that you’ve set up dotenv and your env file, and that you can load values from your global config file in other files. Try posting your code in the developer forum if it’s still giving you trouble.

> I would also like to point out that polaris syntax in the tutorial and documentation are quite different. Why is that so? It can be very confusing for someone new to shopify like me. Some are even marked deprecated, so how should we be using it going forward?

Could you give some examples of Polaris syntax differing between the tutorial and the documentation? Some Polaris features are deprecated because they'll be removed in Polaris 5, which is coming soon. I don’t know the exact timeline, but Polaris v4 will continue to be supported for quite a while.

**Comment by Iciren93** [comment]
> hi Iciren93, the global config values are loaded using the `dotenv` node package. this isn't a problem with the App Bridge library, so I’m going to close this issue (this repo is for App Bridge specifically). Double check that you’ve set up dotenv and your env file, and that you can load values from your global config file in other files. Try posting your code in the developer forum if it’s still giving you trouble.
I was not referring to that global CONSTANTS (NOT CONFIG) in `dotenv`, I have no issue with that.
What I am referring to is this:
![image](https://user-images.githubusercontent.com/33504497/88002583-78e1f180-cb35-11ea-95ee-10c55c46ca96.png)

How I get this config values in other files? Since it is a shared global settings based on this:
![image](https://user-images.githubusercontent.com/33504497/88003008-6f0cbe00-cb36-11ea-8292-c00ff18f5946.png)

> Could you give some examples of Polaris syntax differing between the tutorial and the documentation? Some Polaris features are deprecated because they'll be removed in Polaris 5, which is coming soon. I don’t know the exact timeline, but Polaris v4 will continue to be supported for quite a while.
Well, here is the link : https://polaris.shopify.com/components/structure/app-provider#navigation
Tutorial link: https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris
Screenshot of difference in the tutorial: 
![image](https://user-images.githubusercontent.com/33504497/88003693-09213600-cb38-11ea-85c2-d57c848ddfb5.png)

**Comment by GherghelAndrei** [comment]
@Iciren93 so basically you need shopOrigin in another?

**Comment by ivorpad** [comment]
@GherghelAndrei You don't need that. You just need to use the `useAppBridge` hook to get an instance of the `app`.

```javascript
const app = useAppBridge();
ResourcePicker.create(app, {
  resourceType: ResourcePicker.ResourceType.Product
});
```
