### ISSUE TITLE
Renaming POS Link label results in "Unknown Tile" error on Shopify POS smart grid

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#205]
Currently if an app developer renames a POS Link tile, then it breaks the tile resulting in "Unknown tile" forcing merchants to re-add it to the smart grid. This can be incredibly disruptive for merchants. 

![PXL_20230515_233801870](https://github.com/Shopify/shopify-app-bridge/assets/46724607/0475132f-e803-4d77-a0bb-5b86d87675a5)

**Comment by derrickrc** [comment]
@henrytao-me @vctrchu just checking in - we are nearing the launch of our first POS UI Extension and want to be able to rename one of our existing POS Link tiles to better distinguish the tiles without breaking functionality. Are you able to help with this issue? Thank you.

**Comment by vctrchu** [comment]
@derrickrc Currently taking a look. and will report back with details when I find anything.
