### ISSUE TITLE
web_vitals_1.onLCP is not a function

### ISSUE THREAD

**Issue by mhaseebullah92** [Shopify/shopify-app-bridge#206]
## Describe the bug

using the @3.7.7 version of @shopify/app-bridge-react, on initializing the app as Shopify Embedded APP throwing an error on the console web_vitals_1.onLCP is not a function.

### To Reproduce

Steps to reproduce the behaviour:

Versions of libraries: 
@shopify/app-bridge-react @ ^3.7.7
@shopify/polaris @ ^10.49.1
react @ ^18.2.0

### Expected behaviour

The APP should not throw a console error. 

### Packages and versions

Versions of libraries: 
@shopify/app-bridge-react @ ^3.7.7
@shopify/polaris @ ^10.49.1
react @ ^18.2.0

## Platform

- OS: Windows
- OS Version: Windows 11
- App: Shopify Embedded APP

### Additional context

Node.js 16, React app created using visual studio.

**Comment by rahul-adnabu** [comment]
@mhaseebullah92 i am also facing the same issue and because of my that i  think my lcp and cls values on the app insights are also not updating, do you face the same ?

**Comment by bratsos** [comment]
Hi @mhaseebullah92 and @rahul-adnabu ! The `console.error` is just a reporting thing that we added recently to get more visibility on why web-vitals is failing to load. The fact that you get this error means that web-vitals was failing to load in older versions - we just didn't explicitly logged it.

Seeing the `web_vitals_1.onLCP is not a function` message makes me think that you fall into [this issue](https://github.com/Shopify/shopify-app-bridge/issues/193) - can you double check that and see if any of the workarounds actually fixes the issue?

Thanks, and keep us posted!

**Comment by rahul-adnabu** [comment]
Hey @bratsos , yes i am not getting the lcp cls data in partner dashboard as well, i tried reverting to 3.7.3 also still not getting.
I upgraded react scripts to v5 and webpack to v5.

**Comment by bratsos** [comment]
The CRA5 issue that I linked [here](https://github.com/Shopify/shopify-app-bridge/issues/193) seems unresolved, so I doubt updating dependencies will fix this.

Have you tried implementing the workarounds I suggested? I see that some peeps had success with this by following my example on that issue.

**Comment by rahul-adnabu** [comment]
i tried that workaround today, stopped getting the errors but as the metrics would be shown tommorrow by shopify.
Thanks for helping.

**Comment by rahul-adnabu** [comment]
@19-05-1999 hey try this https://github.com/Shopify/shopify-app-bridge/issues/193, it worked for me
