### ISSUE TITLE
Installed apps are always rendered on admin's full page refresh regardless of route

### ISSUE THREAD

**Issue by pnmcosta** [Shopify/shopify-app-bridge#207]
## Describe the bug

If you have apps installed on your store, and you visit your /admin's homepage, a request is made to the apps embedded URL straight away, this also happens on any other page like /products, /discounts, etc.

Seems to be related to the navigation, however when the app actually loads an initial request gets cancelled and another one triggered which was the source of my investigation into it.

Full thread discussion [here](https://github.com/Shopify/polaris/discussions/9194)

### To Reproduce

Steps to reproduce the behaviour:

1. See above description

### Expected behaviour

See link above

### Packages and versions

Any it's not directly related to the app, but the shopify host (admin.shopify.com)

## Platform

Any browser.

**Comment by pnmcosta** [comment]
Thank you @MitchLillie yup that's correct, unpinning does not prefetch, I now handle `prefetch=1` differently. But I wonder is there any point to have the react app load for the admin's performance, or should my app's backend just 200 OK without any HTML content/app instead?

**Comment by MitchLillie** [comment]
@pnmcosta It's really up to you as the developer to determine what you want to serve. For example, if you make many fetch requests inside the body of your React components, you may want to allow the React app to load so some of those requests can be prefetched. If you tend to gather the data you need on the server side before returning anything, you might want to not allow your entire React tree to render.

I'm going to close this as completed, but feel free to keep the conversation going here.

**Comment by pnmcosta** [comment]
Hi @MitchLillie got it, thank you. That works quite well for me, as I do need to do some token exchange on app render. I'm now doing that on `prefetch=1`.

However, I'm still noticing a cancelled request when I fully refresh the app's page (where prefetch is not included) that gets cancelled (2nd one):

![failed-requests](https://github.com/Shopify/shopify-app-bridge/assets/550684/044294d3-948b-48df-ba65-2a67827facfa)

Any idea why that might be?
