### ISSUE TITLE
Getting the merchant's app.hostOrigin

### ISSUE THREAD

**Issue by matija2209** [Shopify/shopify-app-bridge#208]
## Describe the bug

app.hostOrigin always returns https://admin.shopify.com

### To Reproduce

`const app = useAppBridge();
`

### Expected behaviour

Instead of https://admin.shopify.com receive https://store-name.myshopify.com

**Comment by joeyfreund** [comment]
> app.hostOrigin always returns https://admin.shopify.com/

This is not a bug, it is the expected behaviour whenever a store is served from `admin.shopify.com` (aka unified admin).
There's [more info here](https://www.shopify.com/partners/blog/whats-new-2021#unified-admin).
