### ISSUE TITLE
ExcludeIds from RessourcePicker 

### ISSUE THREAD

**Issue by psppro26** [Shopify/shopify-app-bridge#21]
It would be very important to have a props to exclude ids from the picker. 
Like initialSelectionIds but the excludeIds will not display the ressource when the id is in {excludeIds} so the user cant select them.

**Comment by iainmcampbell** [comment]
You can use Shopify API search syntax in the Resource Picker `initialQuery` prop: https://shopify.dev/concepts/about-apis/search-syntax

There’s a `NOT` operator that seems like it should do what you’re looking for.

**Comment by psppro26** [comment]
Well the user can touch it , and how do i do if i want to exclude product with specific metafield ?

**Comment by iainmcampbell** [comment]
in that case, you’d need to build your own UI inside your app and use the Admin API to make the specific queries you want.

**Comment by isaac** [comment]
@iainmcampbell

The ability to exclude a list of product IDs would also be very useful for an app I am working on.
