### ISSUE TITLE
Locale parameter changed / broke in latest Shopify POS for embedded apps

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#211]
We have a merchant based in Belgium using our Shopify POS embedded app. Previously the locale included in the query string parameter was "en-BE". As of the latest update, now it's simply "en". For Belgian merchants, they only round prices to the nearest 5 cents, so this is proving challenging. Thank you.

**Comment by henrytao-me** [comment]
I confirmed the issue and flag this to the team 🙇
