### ISSUE TITLE
<NavigationMenu /> component no longer rendering 

### ISSUE THREAD

**Issue by Stef733** [Shopify/shopify-app-bridge#212]
## Describe the bug

The <NavigationMenu /> React component is no longer rendering routes on the Shopify admin navigation. I have confirmed that this is the case for other applications as well

### To Reproduce

Steps to reproduce the behaviour:

1. Launch an app using the <NavigationMenu /> React component
2. See the lack of routes rendering

<img width="254" alt="Screenshot 2023-06-20 at 17 21 06" src="https://github.com/Shopify/shopify-app-bridge/assets/15696423/64071103-7a99-4ce8-b559-0d142027503e">

### Expected behaviour

Expect to see a list of routes listed as props in the component on the admin navigation.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.4.3`
- `@shopify/app-bridge-react` @ `3.4.3`
- `@shopify/polaris` @ `11.0.1`

## Platform

- OS: MacOS
- OS Version: 13.4
- App: Chrome

**Comment by raphael-p43** [comment]
Hi!
May I ask how the issue was resolved?
Because we currently have the same problem ...
