### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').

### ISSUE THREAD

**Issue by Michael-Gibbons** [Shopify/shopify-app-bridge#215]
## Describe the bug

Getting these errors in Chrome, found another issue stating the problem was fixed in 3.1, however I'm using 3.7 and the issue persists. It appears to be coming from a sub-module app-bridge-core?

![image](https://github.com/Shopify/shopify-app-bridge/assets/13829417/2da9fe13-a414-423a-a841-3db738077fdf)
![image](https://github.com/Shopify/shopify-app-bridge/assets/13829417/2965cd0d-df0e-4457-9d8a-809c984e0d50)
![image](https://github.com/Shopify/shopify-app-bridge/assets/13829417/f7266737-ceb9-4e6c-a83e-a8ccce764708)

- `@shopify/app-bridge` @ `3.7.0`
- `@shopify/app-bridge-react` @ `3.7.0`
- `@shopify/polaris` @ `10.23.0`

## Platform

- OS: Windows 11
- OS Version: 10.0.22621
- App: Chrome

**Comment by henrytao-me** [comment]
Hi @Michael-Gibbons, can you add more details on how to reproduce this? What url did you open?

**Comment by Michael-Gibbons** [comment]
@henrytao-me The base app url in the shopify admin. Shopify Admin > Apps > YOUR_APP

**Comment by henrytao-me** [comment]
Can I have the app id for testing? The screenshot that you sent shows Online Store url, not your app. So, not sure if we are looking into the correct issue.

**Comment by Michael-Gibbons** [comment]
@henrytao-me it is not app specific, here are the errors on the theme access app
![image](https://github.com/Shopify/shopify-app-bridge/assets/13829417/a89ec3dc-28f4-4e4c-b651-d8125cf8b994)

**Comment by Michael-Gibbons** [comment]
I would attempt to debug further but the code is not open source so good luck

**Comment by henrytao-me** [comment]
@Michael-Gibbons This happens because these apps are using older version of App Bridge. We fixed this error log since App Bridge 3.5.1. It shouldn't be a blocker to load your app.
