### ISSUE TITLE
Docs - shopify.dev  - naming and structure. What is app bridge library , what is app bridge? 

### ISSUE THREAD

**Issue by PaulNewton** [Shopify/shopify-app-bridge#220]
There's two names for the same system?

There is "app bridge" https://shopify.dev/docs/api/app-bridge
and now "app bridge **library**" https://shopify.dev/docs/api/app-bridge-library

Confusingly both pages use a description for the other instead of describing the context of itself.
/api/app-bridge:

> the App Bridge library provides APIs that enable Shopify apps to render UI in the Shopify [embedded app home](https://shopify.dev/docs/apps/admin/embedded-app-home) surface
emphasis "library"

/api/app-bridge-library:

> App Bridge is the JavaScript SDK for [Embedded Apps](https://shopify.dev/docs/apps/admin/embedded-app-home), providing access to data and UI rendering within the Shopify Admin
emphasis no mention of "library"

One is about the overall system? and the other _seems_ like it would be about a ready made UI components reference the way it presents the [reference](https://shopify.dev/docs/api/app-bridge-library/reference) like it's visual demo gallery of a component 
 UI library though most are simplified calls/messaging for shopify-side rendering no "component" needed.

The  /api/app-bridge-library/reference has read-only actions/endpoints mixed in the gallery-esque UI reference , some that are replacing previous javascript/react-hooks.
Some of the old actions say you should used the new version but point to the [/api/bridge-library](https://shopify.dev/docs/api/app-bridge-library) page with no further info, such as [appstate](https://shopify.dev/docs/api/app-bridge/previous-versions/actions/app-state) , or ones like the previous version [resource-picker](https://dev.shopify.com/docs/api/app-bridge-library/reference/resource-picker) which just directs to shopify.dev because it points to **dev.shopify.com** instead of **shopify.dev** broken Link: https://dev.shopify.com/docs/api/app-bridge-library/reference/resource-picker , correct link https://shopify.dev/docs/api/app-bridge-library/reference/resource-picker 

Navigation structure - clicking the reference link in the nav sidebar from /api/app-bridge goes to the /api/app-bridge-library docs which gets it's own empty navigation sidebar implying appbridge and app-bridge-library are separate systems, see image

![image](https://github.com/Shopify/shopify-app-bridge/assets/47228209/67d62600-c25b-4b16-8ab7-09e2862cd485)

**Comment by charlesdobson** [comment]
Thanks for your feedback!

"App Bridge" and "App Bridge Library" are one and the same. The top-level page ([`/api/app-bridge`](https://shopify.dev/docs/api/app-bridge)) is more of a product/marketing explainer of what App Bridge is, where the [`/api/app-bridge-library`](https://shopify.dev/docs/api/app-bridge-library) page is the API reference that dives deeper into technical information.

I've fixed the broken links that you've pointed out - that should go out today or tomorrow.

I'll take the rest of your feedback back to the team.
