### ISSUE TITLE
Resource Picker won't return anything when user has no permissions

### ISSUE THREAD

**Issue by daviareias** [Shopify/shopify-app-bridge#224]
## Bug description

When you try to open the resource picker inside an embedded app, but the user doesn't have the necessary permission (e.g. "view products"), the promise created by shopify.resourcePicker will never be resolved or rejected, app bridge will also not return any further information.

### Steps to reproduce the behaviour:

1. Create a store user with limited permissions (remove the products checkbox permission)
2. Open your shopify embedded app that uses the latest Shopify app bridge from cdn
3. Try calling the shopify.resourcePicker function like this:

```
shopify.resourcePicker({
  type: "product", 
  query: "", 
  selectionIds: [], 
  action: "select", 
  multiple: false, 
})
```

### Expected behaviour

Resource picker should reject the promise or throw an error telling the present user doesn't have the necessary permissions

### Packages and versions

Using latest app bridge version from this link:
https://cdn.shopify.com/shopifycloud/app-bridge.js

### Additional info
This is also a common problem caused by the fact that there's no mechanism for embedded apps to check the logged in user permisions

**Comment by henrytao-me** [comment]
Thanks for reporting. We are on it. 🙇

**Comment by Alagaesia93** [comment]
Any updates here?

**Comment by FA-VuongNQ** [comment]
Almost a year and I have this issue on some store merchant, too. Any update here ???

> Thanks for reporting. We are on it. 🙇
