### ISSUE TITLE
Request - App Bridge access to Socket Mobile Bluetooth Scanner payload

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#23]
I have a barcode scanning app on the Shopify App Store that solves a specific unmet need: https://apps.shopify.com/scan-price-embedded-barcodes

I frequently receive emails and feedback from merchants interested in using my app that being limited to using the built-in mobile device's camera for barcode scanning (as provided by App Bridge) is a deal-breaker, as it results in a suboptimal in-store merchant user experience. 

Is it possible to grant developers access to the barcode payload from the paired Socket Mobile scanner? When I focus on the Search field in the main POS screen and then scan a barcode, for example, the barcode string appears there. Is it possible so the embedded POS browser also receives this payload? I have also spoken with Socket Mobile who were surprised developers didn't have access to this, and said it's up to Shopify to grant this. Thank you. 

**Edit: mPOP as well**

**Comment by derrickrc** [comment]
@andrewapperley just bumping this request - thank you.

**Comment by msadlows** [comment]
Would love this as well!

**Comment by derrickrc** [comment]
@andrewapperley sorry to be a broken record, any update or acknowledgment of this request? Here are some screenshots of a subset of inquires from literally just this past week alone. 

![Screen Shot 2021-01-28 at 7 42 05 AM](https://user-images.githubusercontent.com/46724607/106161981-7394dd80-613c-11eb-812d-bf87e5934af8.png)

![Screen Shot 2021-01-28 at 7 41 50 AM](https://user-images.githubusercontent.com/46724607/106161989-77286480-613c-11eb-99a0-ebb8f852daf5.png)

![Screen Shot 2021-01-28 at 7 40 55 AM](https://user-images.githubusercontent.com/46724607/106162008-7b548200-613c-11eb-9876-5a63d3d1ab6c.png)

![Screen Shot 2021-01-28 at 7 43 42 AM](https://user-images.githubusercontent.com/46724607/106162229-ba82d300-613c-11eb-8150-caefb3af190e.png)

**Comment by pramodparanthaman** [comment]
Hi,
I have exactly the same issue with my stocktaking app. Merchants need to switch their Socket Mobile devices to Keyboard HID mode every time they need to use my app and switch back to iOS application mode if they want to use Shopify POS. This is very inconvenient for the merchants, they want things to work out of the box. Shopify's own Stocky app also has the same issue, i.e. users need to change modes on the scanner to use it with Stocky and switch modes to use it with POS. 
Please help. 
Thanks.

**Comment by galmis** [comment]
Having exactly the same problem, merchants don't seem to be willing to use their mobile cameras.

**Comment by pklitscher** [comment]
Plus one for this feature. We support all HID based scanners but can't use the Socket scanner merchants have attached to their POS. The camera scanner works ok but does not come close to the speed of a laser-based scanner and our merchants are scanning large volumes of barcodes.

**Comment by derrickrc** [comment]
I believe it's available now with POS UI extensions.

**Comment by derrickrc** [comment]
@andrewapperley always appreciated the amazing work you and your team did - your original Scanner component was what inspired us to build our first Shopify POS app. You're a real one and I hope everything is well!

For others, Bluetooth handheld scanner access for third party Shopify POS apps is now available via POS UI Extensions: https://shopify.dev/docs/api/pos-extensions/ui-extensions-reference/api/scanner

I'm going to close this issue for now given that our feature request was specifically for POS and it's now addressed.

**Comment by pklitscher** [comment]
> I believe it's available now with POS UI extensions.

Thank you @derrickrc for that info. Unfortunately, I don't think POS Ui Extensions will work with our app. But I haven't explored POS UI extensions in detail so I will investigate. 

@andrewapperley Thank you so much for advocating for the Bluetooth scanner support, and your amazing work with App Bridge. Saddened we are unlikely to see it included. I can only hope one day it gets up as a feature.
