### ISSUE TITLE
Contextual Save Bar 'Discard' crashes with 'Illegal Invocation' on textarea

### ISSUE THREAD

**Issue by rikbrown** [Shopify/shopify-app-bridge#230]
## Describe the bug

The contextual save bar's `Discard` button crashes if there's a text area.

### To Reproduce

Create a form with a text area using the contextual save bar, modify it, then try to discard.

<img width="591" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/2906188/4b063b0b-9ef9-4259-bcb0-fb75c8d1c164">
<img width="346" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/2906188/5cc4a959-57fc-421a-9107-e3e17d2bb954">

This appears (based on my debugging only) to be because it's trying to use this code to reset it: `const c = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value");`.

### Expected behaviour

Textarea is reset.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

```
"@shopify/app": "3.48.3",
"@shopify/app-bridge-types": "^0.0.2",
"@shopify/cli": "3.48.3",
"@shopify/polaris": "12.0.0-beta.0",
"@shopify/polaris-icons": "^7.8.1",
"@shopify/shopify-app-remix": "^1.0.3",
"@shopify/shopify-app-session-storage-prisma": "^1.0.0",
```

app bridge via cdn

## Platform

Remix/Chromium

**Comment by rikbrown** [comment]
General meta point: we should have some control over what this button does for more complex form experiences.

**Comment by rikbrown** [comment]
Actually [older versions](https://shopify.dev/docs/api/app-bridge/previous-versions/actions/contextualsavebar) seemed to support that. Maybe I'll go back to those.

**Comment by developit** [comment]
Sorry about that! I just deployed a fix that removes the crash.

FWIW, I believe we'll be adding direct save bar control at some point, but for now if you need explicit control over it you should be able to use a hidden form:

```js
function SaveBar({ dirty = false, loading = false, onSave, onReset }) {
  const ref = useRef();
  useEffect(() => {
    ref.current.value = +dirty;
  }, [dirty]);
  return (
    <form data-save-bar={loading?'loading':''} onSubmit={onSave} onReset={onReset}>
      <input initialValue="0" ref={ref} />
    </form>
  );
}
```

**Comment by rikbrown** [comment]
Sorry for the late reply @developit  - and thanks for fixing that.

Any update on the direct save control?

Your approach works though (with some questions - see below). To answer your question of why I need to do this: I have some complex form data maintained using React Hook Form. In particular, there's some data (a JSON blob) which I use to render components (which in turn modify that data)... but they're not traditional form elements. I suppose I could put the data into a hidden input or something like that as an interim, but that's effectively what your hack does.

Back to some of my questions:
1. In your example you set `data-save-bar="loading"`... this isn't documented but I'm guessing it's a way to trigger the "Save" button to show a loading state. This doesn't seem to work though. Is this an upcoming feature?
2. I'm finding the data-save-bar stuff doesn't handle saves/resets very well: I'm saving using an async post (to my Remix app's action). So once the save happens the form is no longer dirty. I'm not sure that the data-save-bar stuff is able to be aware of that... subsequent updates don't seem to re-trigger the save bar to appear. Is there some way to handle this?

All in all I like the idea of having this as a built-in part of the form... but the "magic" doesn't seem to be quite there compared to the older version where you just explicitly told the bar to appear.

**Comment by rikbrown** [comment]
Oh actually re-reading your sample, I'm realising the `initialValue` might be the key for the "dirty-determination" - I'll give that a go. Thanks again for your help btw.

**Comment by rikbrown** [comment]
That seems to work although React isn't very happy:

```
React does not recognize the `initialValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
