### ISSUE TITLE
Overlap between app bridge and Polaris page layout? 

### ISSUE THREAD

**Issue by da-amo** [Shopify/shopify-app-bridge#234]
Hello, 

We are working to implement Built for Shopify guidelines within our app layout. We're using the Polaris page layout, which includes an element for page title and allows for primary and secondary actions.

https://polaris.shopify.com/components/layout-and-structure/page

However, the title-bar component of the app bridge seems duplicative. This also sets a page title, and allows for primary and secondary actions. We'll have page title in two places, with action buttons available in each.

https://shopify.dev/docs/api/app-bridge-library/reference/title-bar

The title-bar component seems like it is required if we want to implement the ui-nav-menu element, to display our navigation in the Shopify side bar.

Can you please clarify if the title-bar component is required, or if there is a way to implement the app bridge ui-nav-menu element without it in a way that satisfies Built for Shopify guidelines?

Shopify support suggested I raise the issue in this repository

Thank you

**Comment by belalsj** [comment]
Hi [da-amo](https://github.com/da-amo),

There is another way to add Navigation Items for your app. On the App's page on your Partners account:

1. Navigate to **App Setup**.
2. In the **Embedded App** section > click **Manage**
3. In the **Navigation** section > click **Configure**

Give this a go and let us know if that covers your use case.

**Comment by MitchLillie** [comment]
@da-amo Thanks for the context. This might be related to a bug we're currently working on. If your app sets `document.title`, app-bridge interprets that the same as if you were using the title bar component. 

In any event, glad to hear you have things working. Let us know if you need anything else.
