### ISSUE TITLE
Resource Picker totalVariants field

### ISSUE THREAD

**Issue by meandillar** [Shopify/shopify-app-bridge#235]
### Describe the feature you’d like

When using the Resource Picker with the "Product" resource a `totalVariants` field is needed to determine whether all variants have been selected or a subset. Currently there is no way to find this out from the resource picker response, other than by making an additional request after making a selection.

### Describe alternatives you've considered

Current workaround is to make an additional request to the graphql admin api after making a selection from within the resource picker.

### Additional context

We have an app displaying a table of products that can be bundled together for a discount. Beside each product in the table we need to list a subset of variant names that apply to the bundle, or simply show "All variants" if any variant can be used.

**Comment by henrytao-me** [comment]
Close. There is a workaround without having to perform extra graphql request. See here for context https://github.com/Shopify/shopify-app-bridge/issues/268#issuecomment-1904119647
