### ISSUE TITLE
What happend to Modal App Bridge

### ISSUE THREAD

**Issue by aimproxy** [Shopify/shopify-app-bridge#238]
Modal in App Bridge is no longer supported in the most recent version. I feel like modals are an important part of shopify admin and avoid a lot of back and forward page navigation!...

**Comment by charlesdobson** [comment]
It's currently being worked on and will be released soon! I'll update here when it's out

**Comment by aimproxy** [comment]
Any workaround I can get it don right now? Perhaps old version of App Bridge I can use?

**Comment by resistorsoftware** [comment]
> Looking forward to it. Missing Modal is deal breaker for App Bridge 3 > 4 upgrade at the moment.

ARGGGGG... if I had know this library was unusable like this, I would never have adopted it for my latest updates. I feel ripped off and have wasted hours. Grrrrr...

**Comment by charlesdobson** [comment]
@darrynten The App Bridge from npm `Button` was only used to create the contract for Modal and TitleBar buttons. You can just use a regular HTML `button` now when you use things like the Title Bar. Did you have a usage for it outside of that?

**Comment by charlesdobson** [comment]
We added Modals with custom DOM content! Check it out: https://shopify.dev/docs/api/app-bridge-library/reference/modal

**Comment by mgill404** [comment]
I am having issues using ui-modal in a Remix app. 

My react components seem to not call their interaction callbacks with this modal. Buttons don't call onClick for example. Any advice on how to address this issue?


for a brief example, here is a Remix route

```
import { Button } from "@shopify/polaris";
import { useEffect } from "react";

export default function Modal() {
  function handleOnClick(e) {
    console.log("received click event"); // does not log
  }

  useEffect(() => {
    document.getElementById("test-modal").show();
  }, []);

  return (
    <ui-modal id="test-modal" variant="max">
      <Button onClick={handleOnClick}>A Button</Button>
    </ui-modal>
  );
}
```

**Comment by daviareias** [comment]
> I am having issues using ui-modal in a Remix app.
> 
> My react components seem to not call their interaction callbacks with this modal. Buttons don't call onClick for example. Any advice on how to address this issue?

This is because they are using webcomponents, but for some reason Polaris uses React, the only way that I managed to fix this is this to wrap the <ui-modal>  around a ref, can probably also give a ref to ui-modal, but typescript will indicate an error:

```
export default function Modal() {
    const ref = useRef < HTMLDivElement > null;
    const handleOnClick = () => {
        console.log("received click event");
    };

    return (
        <div ref={ref}>
            <ui-modal id="test-modal" variant="max">
                <Button onClick={handleOnClick}>A Button</Button>
            </ui-modal>
        </div>
    );
}
```

**Comment by coderlinbb** [comment]
> > 我在 Remix 应用程序中使用 ui-modal 时遇到问题。
> > 我的反应组件似乎没有用这个模式调用它们的交互回调。例如，按钮不会调用 onClick。关于如何解决这个问题有什么建议吗？
> 
> 这是因为他们使用的是 web 组件，但由于某种原因 Polaris 使用 React，我设法解决这个问题的唯一方法是将“ui-modal”包裹在 ref 周围，也可以给 ui-modal 提供引用，但打字稿会提示错误：
> 
> ```
> export default function Modal() {
>     const ref = useRef < HTMLDivElement > null;
>     const handleOnClick = () => {
>         console.log("received click event");
>     };
> 
>     return (
>         <div ref={ref}>
>             <ui-modal id="test-modal" variant="max">
>                 <Button onClick={handleOnClick}>A Button</Button>
>             </ui-modal>
>         </div>
>     );
> }
> ```
Still can't

**Comment by kaczors** [comment]
@charlesdobson hi :)
Is there somewhere working example - the best using standard remix/polaris template?
For example how to call
```
shopify.modal.show('modal-id')
```
or how to not get VS error
```
Property 'ui-modal' does not exist on type 'JSX.IntrinsicElements'
```

**Comment by tylerhellner** [comment]
The modal component itself works well and seems to be using native Browser APIs under the hood (good), but I am flabbergasted why they would build a Modal with its own internal API for state. This completely breaks how React conceptualizes state, and it's incompatible with other Polaris components. What was the reason behind the change?

**Comment by Michael-Gibbons** [comment]
@tylerhellner to "increase friction" to prevent "incorrect usage" https://github.com/Shopify/polaris/issues/11460

**Comment by ivorpad** [comment]
I'm astounded by the choice to eliminate Modal support in the newest release. Modals play a key role in improving user experience and simplifying navigation. It's disheartening that this functionality has been phased out without offering a clear substitute.

**Comment by muchisx** [comment]
I have then now resorted to using the `Modal` from `@shopify/app-bridge-react`, which doesn't work perfectly as it works with routes, not with children and I get this strange error while working with the `remix` template.
https://github.com/Shopify/shopify-app-template-remix/issues/541

But so far is the only way I can have a modal and stay within the React system.

**Comment by CodeChd** [comment]
Does anyone have a workaround for this yet? I'm facing the issue that callbacks are not working for me.

**Comment by dungfv** [comment]
I noticed that many Polaris components cannot work in the new modal:
- Popover
- Tooltip
- Drop zone

Additionally, drag & drop behaviors are also blocked in the new app bridge modal.
This breaks my current application.

**Comment by agustinlaurito** [comment]
> I noticed that many Polaris components cannot work in the new modal:
> 
> * Popover
> * Tooltip
> * Drop zone
> 
> Additionally, drag & drop behaviors are also blocked in the new app bridge modal. This breaks my current application.

Any update regarding this issue? I'm attempting to utilize the datepicker within the modal's popover, but it's not functioning correctly. Instead, the popover appears on the page behind the modal.

**Comment by shatishdesai202** [comment]
https://github.com/Shopify/shopify-app-bridge/issues/331
this one is also an issue with the new app-bridge version (v 4.1.2)

**Comment by noelgoodday** [comment]
> > I noticed that many Polaris components cannot work in the new modal:
> > 
> > * Popover
> > * Tooltip
> > * Drop zone
> > 
> > Additionally, drag & drop behaviors are also blocked in the new app bridge modal. This breaks my current application.
> 
> Any update regarding this issue? I'm attempting to utilize the datepicker within the modal's popover, but it's not functioning correctly. Instead, the popover appears on the page behind the modal.

We're experiencing the same issues with drag & drop in the new AppBridge modal. I opened a dedicated issue here: https://github.com/Shopify/shopify-app-bridge/issues/364
