### ISSUE TITLE
App Bridge React 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify-app-bridge#24]
When I do the typical code to instantiate an instance, it works. 

    import createApp from '@shopify/app-bridge';
    var data = document.getElementById('shopify-app-init').dataset;
    window.app = createApp({
      apiKey: data.apiKey,
      shopOrigin: data.shopOrigin,
    });

I can see a functional window.app object that works for my purposes. 

But if I try the fancier new useAppBridge hook, I get errors. What am I doing wrong? 

    import { Provider, TitleBar, useAppBridge } from '@shopify/app-bridge-react';
    function MyApp() {
      const app = useAppBridge();

Generates the error: 

    Uncaught Error: No AppBridge context provided. Your component must be wrapped in an AppBridge <Context> component.

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `1.27.2`
- `@shopify/app-bridge-react` @ `1.27.2`
- `@shopify/polaris` @ `5.2.1`

## Platform

- MacOS
- OS Version:  10.15.6

**Comment by iainmcampbell** [comment]
That error should be more specific. You need to wrap your React components in the `<Provider>` component from App Bridge React. See https://shopify.dev/tools/app-bridge/react-components#getting-started

**Comment by resistorsoftware** [comment]
The component is part of a Provider based App.. 

    <AppProvider i18n={enTranslations}>
      <Provider config={config}>
        <TitleBar title="Dashboard" />
        <Page fullWidth>

**Comment by resistorsoftware** [comment]
I see. I moved the logic into a component that is a child of Provider. And that worked, OK... 

Thanks

**Comment by TheSecurityDev** [comment]
> What's the best way to wrap every component in a Provider component without duplicating that logic everywhere? Can't use the `children` pattern because the Provider must render first.

Just wrap your entire app with the Provider.

**Comment by hrdwdmrbl** [comment]
@TheSecurityDev So you're suggestion that I do just repeat the logic everywhere?

**Comment by TheSecurityDev** [comment]
> @TheSecurityDev So you're suggestion that I do just repeat the logic everywhere?

I'm assuming you have some kind of top level or root component, like _app.tsx in NextJS. As long as the component has the Provider as an ancestor somewhere it will work. Maybe I'm misunderstanding the question though.
