### ISSUE TITLE
App Bridge 4 clicking on Navigation Menu causes app reload

### ISSUE THREAD

**Issue by kirillplatonov** [Shopify/shopify-app-bridge#240]
## Describe the bug

When clicking on any link in Navigation Menu the app is fully reloaded to open new page. It starts loading from scratch with splash screen, token fetching, etc. This slows down loading dramatically and just looks weird for users.

### To Reproduce

Steps to reproduce the behaviour:

1. Define Navigation Menu with at least two pages:
```html
<ui-nav-menu>
  <a href="/first-page">First page</a>
  <a href="/second-page">Second page</a>
</ui-nav-menu>
```
2. Launch app
3. Click on "First page" link
4. Click on "Second page" link
5. Notice full app reloading

https://github.com/Shopify/shopify-app-bridge/assets/839922/c521a87d-2492-4f3c-8901-55c025e11755

### Expected behaviour

App Bridge should treat Navigation Menu clicks as in-app navigation. Same as navigating relative link within app: https://shopify.dev/docs/api/app-bridge-library/reference/navigation#example-navigating-to-routes-within-your-app

If this is not possible then at least we should have a way to add event handler and override Navigation Menu behaviour. This is how we've done it with App Bridge 3: https://github.com/kirillplatonov/shopify-hotwire-sample/blob/main/app/javascript/shopify_app/navigation.js#L25

### Packages and versions

- `App Bridge 4` from CDN

## Platform

- App: Chrome, Safari, Firefox

### Additional context

Tech stack:
- Rails
- Hotwire
- Polaris ViewComponents

**Comment by Rafi993** [comment]
I can see this issue too.

**Comment by MitchLillie** [comment]
Hello, thanks for your report.

Can you try specifying your app's root path as the first item in the nav menu, and adding `rel="home"` to that link? This is what [our docs](https://shopify.dev/docs/api/app-bridge-library/reference/navigation-menu) specify.

For example: 

```javascript
<ui-nav-menu>
  <a href="/" rel="home">Home</a>
  <a href="/first-page">First page</a>
  <a href="/second-page">Second page</a>
</ui-nav-menu>
```

**Comment by Rafi993** [comment]
> Hello, thanks for your report.
> 
> Can you try specifying your app's root path as the first item in the nav menu, and adding `rel="home"` to that link? This is what [our docs](https://shopify.dev/docs/api/app-bridge-library/reference/navigation-menu) specify.
> 
> For example:
> 
> ```js
> <ui-nav-menu>
>   <a href="/" rel="home">Home</a>
>   <a href="/first-page">First page</a>
>   <a href="/second-page">Second page</a>
> </ui-nav-menu>
> ```

That doesn't seem to work. I think the page has to be cached like it was done in the previous app bridge

**Comment by Rafi993** [comment]
> Use react `Link to=""` instead of `<a href=""`

Thanks. This actually works!!

**Comment by bithaolee** [comment]
> Use react `Link to=""` instead of `<a href=""`

Thank you very much. It really works.
![image](https://github.com/Shopify/shopify-app-bridge/assets/6301977/d66711ab-ba4f-4566-9d96-b0ed302cc017)

**Comment by kirillplatonov** [comment]
This doesn't solve the problem for non-react apps. We still need a proper way to make it work with normal links without hacks. Same way as `Navigation` component works: https://shopify.dev/docs/api/app-bridge-library/reference/navigation#example-navigating-to-routes-within-your-app

**Comment by paweltatarczuk** [comment]
You can do this in plain JavaScript. The key is to prevent browser's default behaviour with `event.defaultPrevent()`. Something like this should work:

```
<ui-nav-menu>
  <a href="/" rel="home" onclick="navigate">Home</a>
  <a href="/first-page" onclick="navigate">First page</a>
  <a href="/second-page" onclick="navigate">Second page</a>
</ui-nav-menu>

<script>
function navigate(event) {
  event.preventDefault();
  history.pushState({}, null, event.target.href);
}
</script>
```

**Comment by kirillplatonov** [comment]
Yeah, it's true. We doing something similar for `Turbo` as well. But it's still broken out of the box and needs to be fixed.

**Comment by awd** [comment]
> You can do this in plain JavaScript. The key is to prevent browser's default behaviour with `event.preventDefault()`. Something like this should work:
> 
> ```
> <ui-nav-menu>
>   <a href="/" rel="home" onclick="navigate">Home</a>
>   <a href="/first-page" onclick="navigate">First page</a>
>   <a href="/second-page" onclick="navigate">Second page</a>
> </ui-nav-menu>
> 
> <script>
> function navigate(event) {
>   event.preventDefault();
>   history.pushState({}, null, event.target.href);
> }
> </script>
> ```

Is this actually working for you? I've just tested it out and there isn't any difference. The AppBridge navigation is still sending unauthenticated requests into the app - causing page reloading.

It's definitely a hack and behaviour could easily break if not part of AppBridge by default - so I would not advise caution to anyone reading into this.

@kirillplatonov has the right sentiment here - AppBridge should send these requests with the Bearer token provided, so the app can simply load the view without reloading/redirecting.

**Comment by paweltatarczuk** [comment]
Yes, it works for me and no, it's not a hack. This is what React Router `Link` is doing under the hood.

**Comment by kirillplatonov** [comment]
This code only updates browser URL without navigating to specific page:
```js
history.pushState({}, null, event.target.href);
```
![CleanShot 2023-10-15 at 08 23 58@2x](https://github.com/Shopify/shopify-app-bridge/assets/839922/cbe092b8-5153-458b-9e62-f3b85cdef0f4)

It's suitable as a fix for #242 when you need to keep focus on the right menu element. But not as a fix for navigation itself.

**Comment by paweltatarczuk** [comment]
I incorrectly assumed that the example app is an SPA. In this case dynamic links won't help as they would require some kind of router that would update the page accordingly.

Maybe it would be possible to workaround this issue with View Transitions API but it's just a guess. I hope app bridge gets a fix for static links in the Navigation component.

**Comment by awd** [comment]
Hi @henrytao-me 

I've tried adding the click event listener, and have confirmed the `ui-nav-menu` is found in the DOM, but the click event is not firing. I suspect the version on this CDN is not the latest?

- What version is being served through: `https://cdn.shopify.com/shopifycloud/app-bridge.js` ?
- How do we check for the latest version? (the global shopify object does not appear to have this info)
- Is there a way to reference a specific version on the Shopify CDN?

**Comment by PhiloNL** [comment]
Hi @henrytao-me 

I'm having trouble with the event listener as well. It only seems to trigger when clicking back and forth.

https://github.com/Shopify/shopify-app-bridge/assets/1133950/b82011f7-e794-47c9-9a2d-668aef965e5c

**Comment by sebastianpisula** [comment]
https://polaris.shopify.com/components/utilities/app-provider?example=app-provider-with-link-component

**Comment by jbeladiya** [comment]
> Vue 3 example:
> 
> ```
> <script setup lang="ts">
> import { useRouter } from 'vue-router'
> import { ref, watch } from 'vue'
> import { useI18n } from 'vue-i18n'
> 
> const router = useRouter()
> const { t } = useI18n()
> 
> function navigate(event: MouseEvent) {
>   const pathname = (event.target as HTMLAnchorElement).pathname
>   history.pushState({}, '', pathname)
>   router.replace(pathname)
> }
> 
> // Re-render ui-nav-menu on route change
> const key = ref(0)
> watch(router.currentRoute, () => key.value++)
> </script>
> 
> <template>
>   <ui-nav-menu :key="key">
>     <a href="/" rel="home" @click.prevent="navigate">{{ t('home') }}</a>
>     <a href="/page-1" @click.prevent="navigate">{{ t('page-1') }}</a>
>     <a href="/page-2" @click.prevent="navigate">{{ t('page-2') }}</a>
>   </ui-nav-menu>
> </template>
> ```

Hi @tobiasdalhof,
The solution provided doesn't work for me. Additionally, I have a React app, and my code is as follows:

`
import { NavMenu } from "@shopify/app-bridge-react";
import { useNavigate } from "react-router-dom"; // v6

const navigate = useNavigate();

const pageRedirect = useCallback((e) => {
    e.preventDefault();
    window.history.pushState({}, '', e.target.href);
    navigate(e.target.pathname);
  }, [navigate]);
  
<NavMenu>
        {Object.values(shopifyNavigation).map((i, index) => {
          return (
            <a
              href={i.destination}
              key={index}
              onClick={pageRedirect}
            >
              {i.label}
            </a>
          );
        })}
      </NavMenu>
`

Here, I'm loading all nav-items dynamically

**Comment by umutnacak** [comment]
Hi @jbeladiya If you didn't already solve your issue here is a code snippet for you to try:
```typescript
import { NavMenu } from "@shopify/app-bridge-react";
import { useMemo } from "react";
import { useLocation, Link } from "react-router-dom";

const location = useLocation();
const navMenu = useMemo(() =>
<NavMenu key={location.key}>
  {Object.values(shopifyNavigation).map((i, index) => {
    return (
      <Link to={i.destination}>
        {i.label}
      </Link>
    );
  })}
</NavMenu>, [location, shopifyNavigation]);

{ navMenu }
```
I didn't test with dynamic values so am not sure if it works like this, but here is a simple snippet that I already use in production:

```typescript
import { NavMenu } from "@shopify/app-bridge-react";
import { useMemo } from "react";
import { useLocation, Link } from "react-router-dom";

const location = useLocation();
const navMenu = useMemo(() =>
<NavMenu key={location.key}>
  <Link to="/" rel="home">
    Home
  </Link>
  <Link to="/page1">
    Page1
  </Link>
  <Link to="/page2">
    Page2
  </Link>
</NavMenu>, [location]);

{ navMenu }
```

Hope this helps future readers.

**Comment by jbeladiya** [comment]
> Hi @jbeladiya If you didn't already solve your issue here is a code snippet for you to try:
> 
> ```ts
> import { NavMenu } from "@shopify/app-bridge-react";
> import { useMemo } from "react";
> import { useLocation, Link } from "react-router-dom";
> 
> const location = useLocation();
> const navMenu = useMemo(() =>
> <NavMenu key={location.key}>
>   {Object.values(shopifyNavigation).map((i, index) => {
>     return (
>       <Link to={i.destination}>
>         {i.label}
>       </Link>
>     );
>   })}
> </NavMenu>, [location, shopifyNavigation]);
> 
> { navMenu }
> ```
> 
> I didn't test with dynamic values so am not sure if it works like this, but here is a simple snippet that I already use in production:
> 
> ```ts
> import { NavMenu } from "@shopify/app-bridge-react";
> import { useMemo } from "react";
> import { useLocation, Link } from "react-router-dom";
> 
> const location = useLocation();
> const navMenu = useMemo(() =>
> <NavMenu key={location.key}>
>   <Link to="/" rel="home">
>     Home
>   </Link>
>   <Link to="/page1">
>     Page1
>   </Link>
>   <Link to="/page2">
>     Page2
>   </Link>
> </NavMenu>, [location]);
> 
> { navMenu }
> ```
> 
> Hope this helps future readers.

Hi @underwoodsimon it's work for me. Thanks.
But other side browser back not working properly when I click on browser back two or three time then after it's redirect to previous route. If you have also solution for it let me know.

**Comment by umutnacak** [comment]
@jbeladiya I also faced that issue during development, most likely because react renders twice in strict mode.  So probably there are multiple entries of the same location in the browser history and you need to click twice or more on the back button. You need to test on production to see if there is a difference.

**Comment by kuus** [comment]
to me is still not clear what is the solution with `react-router-dom`..
This was closed so when it was fixed? In which version?

**Comment by ericute** [comment]
It is 2025 and this is still not working out of the box. What worked for me is this (I am using Next.js):

```
import { NavMenu } from '@shopify/app-bridge-react'
import Link from 'next/link'

const SideNavigation = () => (
  <NavMenu>
    <Link href="/" rel="home">
      Link 1
    </Link>
    <Link href="/bookings/calendar">Link 2</Link>
    <Link href="/products">Link 3</Link>
  </NavMenu>
)

export default SideNavigation

```

**Comment by DeskmozUser** [comment]
@ericute, could you please provide a sample of your layout.tsx file, specifically how you're setting up the NavMenu? Also, could you share the version of @shopify/app-bridge-react you're using? I'm currently facing an issue in my Next.js project.

**Comment by BMoatDev** [comment]
> I am using the workflow the same as in shopify remix template for my remix app:
> 
> routes/app.tsx
> 
> ```
> import { Link, Outlet, useLoaderData, useRouteError } from "@remix-run/react";
> import { AppProvider } from "@shopify/shopify-app-remix/react";
> import { NavMenu } from "@shopify/app-bridge-react";
> 
> 
> ...
> 
> 
> export default function App() {
>   const { apiKey } = useLoaderData<typeof loader>();
> 
>   return (
>     <AppProvider isEmbeddedApp apiKey={apiKey}>
>       <NavMenu>
>         <Link to="/app" rel="home"> Home </Link>
>         <Link to="/app/settings" rel="settings">Settings</Link>
>         <Link to="/app/additional" rel="additional">Additional</Link>
>       </NavMenu>
>       <Outlet />
>     </AppProvider>
>   );
> }
> ```
> 
> An experiencing the same problem with scree blinking before redirection to menu item in the admin. Is there any solution?
> 
> The trick with import { useLocation, Link } from "react-router-dom" did not work for me

Did you figure this out? on the same boat
