### ISSUE TITLE
App Bridge CDN Navigation UX Lag

### ISSUE THREAD

**Issue by panzacoder** [Shopify/shopify-app-bridge#242]
## Describe the bug

In an app bridge app using the latest tool of our choice NextJS 13.5 (App Router) and Shopify App Bridge (CDN), there is a UX bug when navigating between routes using the App Bridge Navigation links.

--

By digging into the app-bridge-remix starter repo, I found that you were using Remix Router `Link` components instead of plain `<a/>` tags as I had assumed was required. This provided a huge benefit! Where the plain html required a full page reload on every navigation (and loading a bounce page to obtain the bearer token), whereas navigation inside of the iframe was able to do router-based navigation, which is obviously much faster.

However, this bug is a side-affect. I will provide a screen recording, as that is the only good way to show what I mean. It should be noted that navigating within the iframe still populates the side-bar nav active link styling, but navigating from the actual sidebar has the styling lagging behind. My guess is that this is some sort of listener that exits too early, but I can't see your code for app bridge so ¯\_(ツ)_/¯ .

### To Reproduce

> I currently cannot provide a minimal repro due to the code being private, but I will try to provide one shortly if it is helpful.

### If applicable, add screenshots to help explain your problem.

https://github.com/Shopify/shopify-app-bridge/assets/29257545/5d19a1f9-adf2-48d6-9027-6409811432dc

### Expected behaviour

Navigation should be both quick and keep active nav styling in sync, as it does with iframe routing otherwise.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/polaris` @ `11.25.0`
- `next` @ `13.5.3`
- `@shopify/app-bridge-types` @ `0.0.3`
```shell
➜ cloudflared -v
cloudflared version 2023.8.2 (built 2023-08-31-1503 UTC)
```

## Platform

- OS: MacOS
- OS Version: Sonoma `14.0`
- App: Arc Browser Version `1.10.1)`
  - Chromium Engine Version `117.0.5938.132`

**Comment by bithaolee** [comment]
I'm experiencing the same problem, when I open my app directly through the app link or refresh the whole app, it triggers this effect and I need to double-click to select the menu, but if I'm clicking through the app directory to enter the app, it doesn't trigger the bug, this problem exists for a month or two now, and I don't know how to resolve it

**Comment by paweltatarczuk** [comment]
I experienced the same issue with Vue Router. A workaround is to ensure that the `pushState` happens synchronously.

A working example in Vue:

```vue
<template>
  <ui-nav-menu>
    <a href="/" rel="home" @click.prevent="navigate($event, '/')">Home</a>
    <a href="/page" @click.prevent="navigate($event, '/page')">Page</a>
  </ui-nav-menu>
</template>

<script setup lang="ts">
import { useRouter } from "vue-router";

const router = useRouter();

function navigate(event: MouseEvent, to: string) {
  history.pushState({}, "", to);
  router.replace(to);
}
</script>
```

**Comment by paweltatarczuk** [comment]
Yes, that's a correct equivalent. In Vue `@click.prevent` binds an event listener and prevents the default browser action (`event.preventDefault()`).

**Comment by tommypepsi** [comment]
I managed to make it work using @panzacoder idea. Though the prevent default was simply preventing the navigation altogether. Removing the prevent default was working but causing a full page refresh with just the `router.push("...")`. So I changed that for `history.pushState(null, "", "/")` and it worked perfectly! There's still a little flash of the navigation but now it at least highlight the right menu in the end.

Here's what worked in the end for me:
```jsx
<ui-nav-menu>
  <Link 
    to="/app" 
    rel="home"
    onClick={() => {
        history.pushState(null, "", "/app");
    }}
  >
    {t("menu.home")}
  </Link>

  <Link 
    to="/app/settings"
    onClick={() => {
        history.pushState(null, "", "/app/settings");
    }}
  >
    {t("menu.settings")}
  </Link>

  <Link 
    to="/app/setup"
    onClick={() => {
        history.pushState(null, "", "/app/setup");
    }}
  >
    {t("menu.how_to_setup")}
  </Link>

  <Link 
    to="/app/general-info"
    onClick={() => {
        history.pushState(null, "", "/app/general-info");
    }}
  >
    {t("menu.general_information")}
  </Link>
</ui-nav-menu>
```

**Comment by panzacoder** [comment]
@tommypepsi Thanks for the bump! I was actually able to achieve this with pretty much the same code, although I also deduplicated a bit. Feel free to take it!


```typescript
'use client';

import NextLink, { LinkProps } from 'next/link';

function Link({ href, onClick, ...props }: LinkProps & { children: React.ReactNode; rel?: string }) {
  return (
    <NextLink
      href={href}
      onClick={(e) => {
        history.pushState(null, '', href.toString());
        onClick?.(e);
      }}
      {...props}
    />
  );
}
export default function Navigation() {
  return (
    <ui-nav-menu>
      <Link href="/" rel="home">
        Home
      </Link>
      <Link href="/page-1">Page One</Link>
      <Link href="/page-2">Page Two</Link>
      <Link href="/page-3">Page Three</Link>
    </ui-nav-menu>
  );
}
```

I'll leave this thread open for visibility, but if the App Bridge team thinks this is an acceptable solution, that's cool. I think at this point the ask would just be some additional documentation that if your router and app bridge isn't in sync, you'll need to manually call `history.pushState()`.

**Comment by atinder** [comment]
@henrytao-me

1. we are using app bridge React 4
2. navigation is properly highlighted by the end.
3. But there is a flash when switching from one link to another. It jumps between the 2 links quickly, back and forth. And then settle on the correct one.

**Comment by tobiasdalhof** [comment]
> [@henrytao-me](https://github.com/henrytao-me)
> 
> 1. we are using app bridge React 4
> 2. navigation is properly highlighted by the end.
> 3. But there is a flash when switching from one link to another. It jumps between the 2 links quickly, back and forth. And then settle on the correct one.

Same here:

https://github.com/user-attachments/assets/f7f3ab12-3337-434c-9e04-ab7fccfee710
