### ISSUE TITLE
Provide npm versioned releases of App Bridge 4.x

### ISSUE THREAD

**Issue by darrynten** [Shopify/shopify-app-bridge#255]
### Describe the feature you’d like

Versioned npm releases of App Bridge 4.x

### Describe alternatives you've considered

Having a single, unversioned package that's always overwritten with the newest version is like using `dev-main` in your dependencies which we all know is a big no-no.

What is the reason for moving to CDN-only for 4.x instead of continuing to provide npm installable packages?

Surely this is just going to lead to massive amounts of broken apps over time as Shopify release breaking changes, or remove core functionality like we're seeing now with the Button and Modal actions. How can we lock apps at a certain version of a CDN available App Bridge?

Providing a CDN-only release also creates a development dependency of having to be online to do any work, and also breaks all frontend unit and integration testing workflows if there's no network connection.

Switching to CDN-only going into 2024 feels like a massive step backwards and makes me worried about the future of the platform.

Please help us understand, why have you done this?

**Comment by daviareias** [comment]
Supported
