### ISSUE TITLE
App Bridge 3.7.9 Still Blow up on App took too long to load. Legacy blah

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify-app-bridge#259]
It is still a thing a year later? This stupid internal Shopify bug about App Bridge not loading so let's scare the merchant and open two tabs and lalalalalala.

Way to go Javascript team Shopify! I do hope this effort earns some rewards. Awesome stuff there. Wonderful. See you in 2024 for the same old same old I bet. As we migrate ever so slowly to admin.shopify.com/stores and all our nice Apps puke over and over and over again on App Bridge! A bridge too far!

**Comment by henrytao-me** [comment]
@resistorsoftware May I have your appId please?

**Comment by henrytao-me** [comment]
Hi @resistorsoftware, your app should be good now. The banner is gone.

For context, there are handful of apps that aren't compatible with the new admin which is why the banner is shown. After fixing the compatibility issue, partner needs to contact support team to resolve it unfortunately. 

I am so sorry for the inconvenient. 🙇

**Comment by faridmovsumov** [comment]
@henrytao-me, we have the same problem. The app id is 4222617. Could you please help?

**Comment by wissem** [comment]
@henrytao-me we have the same issue, could you please help? Issue is appearing on old created apps, but newly created one doesn't have it (although same code and same configuration). Our staging App ID: 5005323.
Our live app id isn't embedded yet but you can enable this setting if it doesn't affect current functionality. Live App ID: 1870886

Thanks!

**Comment by wissem** [comment]
@henrytao-me this is working now, thank you 🙏 
What about my live app? It's non-embedded right now, but we plan to make it embedded in a few weeks. In case enabling the flag woudln't break existing functionality for users, can you enable it for the live app too? App ID: 1870886

**Comment by Praveen2106** [comment]
Hey, we recently moved to an embedded app. Both App Bridge & React components are the latest ones. 

We still see this issue on admin.shopify.com stores. App ID: 1851063

Is anything required from our end? Please let us know.
