### ISSUE TITLE
Modal variant="max" (Full screen)  breaks other UI components

### ISSUE THREAD

**Issue by michaelhaessig** [Shopify/shopify-app-bridge#264]
## Describe the bug

We are in the process of migrating from app bridge 3.x to 4.x since now the Full-screen mode seems to be supported.

**Issue:** we are now seeing that the Modal variant="max" is creating a completely new iframe, which seems to contain a copy of the previous page with the Modal element.  

Apps that have other UI elements, for example a custom dropdown component, will still have the reference to the original body, which then causes the dropdown contents to be added to the original document body and not the copied one inside the modal.  (Very common that dropdowns add the contents to the body). This copy behavior breaks a lot of UI components. 

**Is there any way to prevent the creation of a second iframe?**  The previous 3x version Full-screen mode also did not create a new iframe and everything is working fine. 

### To Reproduce

Original embeded app:
![CleanShot 2023-12-21 at 16 40 22@2x](https://github.com/Shopify/shopify-app-bridge/assets/1331733/3e1e8fc7-b238-4e1e-813e-448f7864a247)

Second Iframe for modal:
![CleanShot 2023-12-21 at 16 39 33@2x](https://github.com/Shopify/shopify-app-bridge/assets/1331733/da243b17-e4a0-4937-b9c6-d13bab2fdaf6)

### Expected behaviour

The current page is kept and the modal is opened with the contents provided.   App bridge v3 Fullscreen mode works without any issues. 

### Packages and versions

App bridge v4

**Comment by henrytao-me** [comment]
Hi @michaelhaessig 

> Apps that have other UI elements, for example a custom dropdown component, will still have the reference to the original body, which then causes the dropdown contents to be added to the original document body and not the copied one inside the modal. (Very common that dropdowns add the contents to the body). This copy behavior breaks a lot of UI components.

When the 2nd iframe is loaded, it will suppress all the DOM element on the page. None of the existing elements are shown if you have App Bridge CDN defined on the <head> tag.

Hi @oxxn 

> Seconding this. Many UI components inside this modal iframe are broken. For example, I can't get a button to work inside it. (I might be doing something else wrong, but it seems to be the same issue).

For React usage of this custom modal content, you need to setup React Portal https://react.dev/reference/react-dom/createPortal for the ui-modal children. We are working on a new App Bridge React library that makes it easier for React consumer.

**Comment by michaelhaessig** [comment]
@henrytao-me i'm not sure i understand your comment or how this can be helpful in making other components work again.

For example, the page can have top level components with their JS logic attached, when app bridge extracts to full Modal content into a new iframe, all logic around the Modal is lost. (There are many JS frameworks that have top level controllers - breaking all these frameworks does not seem like a good dev expirience). 

Furthermore, components inside the modal still seem to have the references to the main document node, and for example a dropdown component that adds new elements to the DOM is not workin. (Many dropdown components work like this - child elements are added to the `<body>` and are absolutely positioned.

May I ask why this decision of a new iframe was made?  In app bridge v3 everything works well without the need for a new iframe.

**Comment by nullndr** [comment]
Any news about this? Has been already a month...

**Comment by irahulranjan** [comment]
Any updates on this?

**Comment by dungfv** [comment]
https://github.com/Shopify/shopify-app-bridge/issues/301

**Comment by irahulranjan** [comment]
Thanks for the update @jzazove. This fix would help us migrate the WYSIWYG editor into the max modal.

**Comment by forsbergplustwo** [comment]
Unfortunately due to the design of the new fullscreen modals in App Bridge v4 we've decided to simply not use them. It results in a slightly inferior experience for users, but this library requires too much bending over backwards to make them worth it in it's current design.

<img width="598" alt="CleanShot 2024-03-07 at 11 27 06@2x" src="https://github.com/Shopify/shopify-app-bridge/assets/1411883/446619fd-f9a1-403e-9b9f-d6e6a61da130">

I know the team are working on trying to improve this (and sorry if this is de-motivating 💚), but IMHO the fundamental design of how these modals work is neither intuitive, stable or documented. Hopefully we can revisit this in the future.

**Comment by rockposdev** [comment]
Is there any news on this issue? we can't make it works even with src

**Comment by jzazove** [comment]
@rockposdev could describe what isn't working?  Using the `src` attribute or even using an `iframe` inside the content should allow developers to really build anything now.

**Comment by rockposdev** [comment]
@jzazove I've wonder if we use this component is ok for the newest require from Shopify https://shopify.dev/docs/api/app-bridge-library/react-components/modal?

**Comment by henrytao-me** [comment]
@rockposdev Modal src should have same origin as your main app origin.

**Comment by gmays** [comment]
Another example: In our app the calendar using DatePicker within a Popover is displayed BEHIND the max modal, thus making it unusable.

![Screenshot 2024-05-24 at 9 15 23 AM](https://github.com/Shopify/shopify-app-bridge/assets/6279639/45366c26-0d42-45e6-9465-39254f13eba5)

This is when I delete the max modal from the dom while having focus on the date field.

![Screenshot 2024-05-24 at 9 15 03 AM](https://github.com/Shopify/shopify-app-bridge/assets/6279639/e03bbc8f-71ef-4921-b036-de473725af94)

**Comment by gmays** [comment]
> @gmays are you using the `src` attribute with the modal API?

Thanks, will try that!

**Comment by danyn** [comment]
This is making things hard for people to use

**Comment by TemurbekRuziyev** [comment]
Hello
@jzazove Can you please provide the example of `src` attribute usage?
It's very poor documented in the Shopify docs

**Comment by vividviolet** [comment]
This is fixed. See the docs [here](https://shopify.dev/docs/api/app-bridge/using-modals-in-your-app#react-components-using-react-portals).
