### ISSUE TITLE
POS Action Return Details

### ISSUE THREAD

**Issue by msadlows** [Shopify/shopify-app-bridge#27]
Would love to see additional details added to the POS action in App Bridge:

- Dark/Light mode - This will allow us to properly style our app interface to reflect the option of that device. Currently there is no work around, we have to manually ask the user to set it in a settings panel.
- Currency - Tis will allow us to properly set the format of currency based on what the POS is in. Right now we have to query the admin API to get the shop details and get the formatting from there.

Thanks!

**Comment by iwoodruff** [comment]
Hey @msadlows thanks for the suggestions – i particularly appreciate that you included where there are / aren't workarounds. i'm adding these thoughts to an inspo board
