### ISSUE TITLE
Can I get some help from the technical team at Shopify?

### ISSUE THREAD

**Issue by conraddecker** [Shopify/shopify-app-bridge#29]
I apologize in advance for this as I realize it is probably not the right place for what I'm looking for but I've had absolutely zero luck getting a response from anyone on the technical team at Shopify for the past 4 months and I've been told to try posting here by members of the forums as well as Shopify support personnel because it might get more visibility. I figured I'd give it a shout.

I started this thread back in August (https://community.shopify.com/c/Shopify-APIs-SDKs/Shopify-POS-Cart-Extension/td-p/857212) in relation to the cart extension functionality that has been made available. While it's not directly correlated to the Shopify App Bridge (the functionality doesn't require the App Bridge at all) I guess it's somewhat similar in nature. 

Honestly, I'm just trying to get some information from someone who might be able to tell me if what I'm seeing is the expected functionality or if there is anything on the roadmap that will improve this functionality. For a more detailed explanation of my use, you can head directly to this comment: https://community.shopify.com/c/Shopify-APIs-SDKs/Shopify-POS-Cart-Extension/td-p/857212

Again, my apologies for dropping this here. If someone on the Shopify team is willing to help point me in the right direction I would certainly be most appreciative.

Cheers!

**Comment by dave-pelletier** [comment]
Hi Conrad, I just responded to your forum thread here: https://community.shopify.com/c/Shopify-APIs-SDKs/Shopify-POS-Cart-Extension/m-p/1043190/highlight/true#M61882
