### ISSUE TITLE
Contextual save bar is not working in the React

### ISSUE THREAD

**Issue by khronosleung** [Shopify/shopify-app-bridge#291]
## Describe the bug

My UI interaction process involves dragging files to the `DropZone` component, then reading and outputting the file content to the `TextField` component. I have used the native HTML `form` and set the `data-save-bar` attribute, but the `Contextual Save Bar` ultimately did not display.

### To Reproduce

```jsx
import { useState, useCallback } from "react";
import {
  Page,
  Layout,
  FormLayout,
  DropZone,
  BlockStack,
  Card,
  TextField,
} from "@shopify/polaris";

export default function ProductFrom() {
  const [newInputValue, setNewInputValue] = useState('');

  const handleDropZoneDrop = useCallback((_dropFiles, acceptedFiles, _rejectedFiles) => {
    const reader = new FileReader();
    reader.onload = event => {
      const content: string = event.target.result || '';
      if (typeof content === 'string' && content.length > 0) {
        setNewInputValue(content);
      }
    };
    reader.readAsText(acceptedFiles[0]);
  }, [newInputValue]);

  const handleFileDialogClick = useCallback(() => {
    return false;
  }, []);

  const handleFormChange = useCallback(async (e) => {
    console.log('handleFormChange', e);
  }, []);
  const handleFormSave = useCallback(async (e) => {
    e.preventDefault();
    console.log('handleFormSave', e);
    const formData = new FormData(e.target);

    const values = {};
    for (const [key, value] of formData.entries()) {
      values[key] = value;
    }

    console.log('values', values);
  }, []);
  const handleNewInputChange = useCallback((newValue: string)=> {
    setNewInputValue(newValue);
  }, []);

  return (
    <Page>
      <Layout>
        <Layout.Section>
          <BlockStack gap="500">
            <Card>
              <BlockStack gap="200">
                <form
                  data-save-bar
                  onChange={handleFormChange}
                  onSubmit={handleFormSave}
                >
                  <FormLayout>
                    <DropZone
                      dropOnPage
                      allowMultiple={false}
                      outline={false}
                      accept="text/csv,text/plain"
                      errorOverlayText="File type must be .csv or .txt"
                      type="file"
                      onClick={handleFileDialogClick}
                      onDrop={handleDropZoneDrop}
                    >
                      <TextField
                        label="content"
                        labelHidden
                        multiline={5}
                        maxHeight={130}
                        autoComplete="off"
                        name="content"
                        value={newInputValue}
                        onChange={handleNewInputChange}
                      />
                    </DropZone>
                  </FormLayout>
                </form>
              </BlockStack>
            </Card>
          </BlockStack>
        </Layout.Section>
      </Layout>
    </Page>
  );
}
```

### Expected behaviour

After changing the value of the `TextField` component through the setState method, the `Contextual Save Bar` can be displayed.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app` @ `3.56.2`
- `@shopify/cli` @ `3.56.2`
- `@shopify/polaris` @ `12.16.0`
- `@shopify/shopify-api` @ `9.3.2`

## Platform

- OS: MacOS
- OS Version: 14.3.1
- App: Chrome

### Additional context

https://shopify.dev/docs/api/app-bridge-library/reference/contextual-save-bar#example-subscribe-to-discard

https://polaris.shopify.com/components/selection-and-input/text-field?example=text-field-multiline

https://polaris.shopify.com/components/selection-and-input/drop-zone

**Comment by bakura10** [comment]
I did some experiment with that and indeed the new Contextual Save Bar is too limited. Knowing if a form is dirty or not can only really be known by the consumer app (you might have hidden input that needs to be used by the app, that should not contribute to the status of the data-save-bar but that are still taken into account by App bridge). Ultimately I think the data-save-bar should accept a boolean that would be tracked by Shopify to show/hide the bar.

**Comment by jzazove** [comment]
We are looking into this issue.

**Comment by geongeorge** [comment]
@jzazove I do not want to question the company decisions but making the app bridge open source would make it much easier for us to at least figure out what is going on. I cannot make the save bar show no matter how many change event I fire.

**Comment by ramvyr** [comment]
> There's a `SaveBar` React component in `@shopify/app-bridge-react@4.1.0` too if you'd prefer to use that: https://shopify.dev/docs/api/app-bridge-library/react-components/savebar

It's a great solution, but I want to draw the user's attention about what it leaves - shake as it works in shopify admin, but the shake control is not there

**Comment by Zn4rK** [comment]
It also seems like the SaveBar is blocking the address bar from being updated whenever a remix action is doing a redirect.

The remix app is redirected correctly, but the redirect is not reflected in the address bar.

Removing the saveBar, it works as expected.

**Comment by Zn4rK** [comment]
> Given that shopify admin blocks transitions when the save-bar is in show state, in our app we should also block transitions for this state. This is easy to use with useBlocker

Sure. If it's applicable. In this case, it's a route that handles either a new or an existing entity. Creating a new entity redirects in a remix action to the newly created entity. In response to the form being submitted. It's just the address bar that doesn't get the new url. The app is redirected correctly, and behaves as one would expect.

The only thing that's not working is the address bar. Which is problematic, and feels like a bug, since the correct UI action would be to show the save bar, but if we can't redirect in actions, it can only be used for so much.

I ended up writing a SaveBar-helper that waits for the "leaveConfirmation"-promise, and then manually updating the navigation state, with help of "history.pushState / replaceState".
