### ISSUE TITLE
Contextual save bar is not working properly when fields are updated programatically

### ISSUE THREAD

**Issue by bakura10** [Shopify/shopify-app-bridge#293]
Hi,

It looks like the new `data-save-bar` attribute is listening to the `change` event, from what I can understand from the minified app bridge code:

<img width="412" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/1198915/302a0427-26ec-4603-b363-1cf7f398f8c6">

The issue with this approach is that it won't catch up fields whose value change programmatically, as the `change` event is only triggers when the user explicitly use the keyboard.

For instance, imagine a `<TextField>` Polaris component that acts as an activator of a Color Picker. If the component updates the color when the color picker changes, the change event won't be triggered and, as a consequence, the contextual save bar won't show up.

Here is a minimum example reproducing the issue:

```
export default function Color() {
  const [selectedColor, setSelectedColor] = useState('');
  const [value, setValue] = useState('');
  const [isPickerOpen, setIsPickerOpen] = useState(false);

  useEffect(() => {
    if (selectedColor) {
      setValue(hsbToHex(selectedColor));
    }
  }, [selectedColor]);

  const activator = (
    <TextField
      label={'Color'}
      value={value}
      onFocus={() => setIsPickerOpen(true)}
      onChange={(value) => setValue(value)}
      type={"text"}
    />
  );

  return (
    <Popover active={isPickerOpen} activator={activator} onClose={() => setIsPickerOpen(false)}>
      <ColorPicker color={selectedColor} onChange={(selectedColor) => setSelectedColor(selectedColor)} />
    </Popover>
  );
}
```

Here, the selectedColor is updated when a color is picked, and the associated textfield value is updated with the hex code. But as this change is not triggered by an actual change on the input, the event is not triggered, and the contextual save bar won't catch up.

I don't think there is any way to solve this cleanly, so I think ultimately Shopify should let the developer decide by adding a new `shopify.contextualSaveBar.show()/hide()` and give the control to the developer.

**Comment by adamwooding** [comment]
+1 - We are having the same issue. The solution offered by @bakura10 would be very helpful.

**Comment by rex-empowerdigital** [comment]
+1 - I am having the same issue.

**Comment by noelgoodday** [comment]
+1 same issue here. Would prefer there to be an API to show/hide the bar so we can use our own form logic.
@rightgeek thanks for providing a workaround for this.

**Comment by khronosleung** [comment]
+1 - having the same issue

**Comment by jzazove** [comment]
We are looking into this issue.

**Comment by mirceapiturca** [comment]
> I fully support the idea of manual control of the component (as it was in the previous version), it is the most reliable mechanism.

Agree! The rest of components have simple declarative APIs, like `shopify.toast.show('Message sent')`. This one is inconsistent. Wrapping everything in a form doesn't work in many real app use cases.

**Comment by charlesdobson** [comment]
Hi all,

We added a new `ui-save-bar` element for you to manually control the state of the contextual save bar (including `disabled` and `loading` buttons) if that works better for you: https://shopify.dev/docs/api/app-bridge-library/web-components/ui-save-bar

There's a `SaveBar` React component in `@shopify/app-bridge-react@4.1.0` too if you'd prefer to use that: https://shopify.dev/docs/api/app-bridge-library/react-components/savebar

Thanks for the feedback!

**Comment by kirillplatonov** [comment]
@charlesdobson this is awesome news! Thank you! 👏

**Comment by adamwooding** [comment]
Thank you so much @charlesdobson !!
