### ISSUE TITLE
ui-modal height not fit content

### ISSUE THREAD

**Issue by quocdatPTIT** [Shopify/shopify-app-bridge#295]
## Describe the bug

The new `<ui-modal />` component always renders with full height

### To Reproduce

Steps to reproduce the behaviour:

1. Add `<ui-modal />` into code

2. Open the modal

![image](https://github.com/Shopify/shopify-app-bridge/assets/38630622/fff3a183-f453-480f-b56b-c92663971922)

### Expected behaviour

ui-modal height fit content
![image](https://github.com/Shopify/shopify-app-bridge/assets/38630622/a5bb0eee-ae26-4104-bb6b-01d47ee0ba4a)

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge-utils` @ `3.5.1`
- `@shopify/app-bridge-react` @ `4.0.0`
- `@shopify/polaris` @ `12.19.2`

**Comment by coderlinbb** [comment]
Me too.

**Comment by hamzasgd** [comment]
This is what causing the issue 
![modal issue](https://github.com/Shopify/shopify-app-bridge/assets/12862136/87def440-6b3e-4ccb-b0ad-2f5c1aadf1cb)
