### ISSUE TITLE
Contextual Save Bar React components- for App Bridge React 

### ISSUE THREAD

**Issue by keidarcy** [Shopify/shopify-app-bridge#3]
### Describe the feature you’d like

It would be nice to add Contextual Save Bar to @shopify/app-bridge-react
Simply implement like
```
import {Provider, ContextualSaveBar} from '@shopify/app-bridge-react';
```

### Describe alternatives you've considered

It's possible to use @shopify/polaris' one, however, for the embedded app the position of save bar isn't sweet.

**Comment by iainmcampbell** [comment]
It’s on our to do list!

In the meantime, [this implementation by a Shopify Partner](https://community.shopify.com/c/Shopify-APIs-SDKs/Contextual-Save-Bar-React-component/m-p/651224#M44142) might help you out?

**Comment by keidarcy** [comment]
Thanks! Currently, I will try that!

**Comment by axis80** [comment]
I also would very much like to see this.  To show my support, I'm "liking" the top-level comment by @keidarcy.  I encourage others to do the same.

**Comment by charlesdobson** [comment]
The `@shopify/app-bridge-react` library now supports 2 methods of using the Contextual Save Bar action!

It can be used through the `useContextualSaveBar` hook or through the `ContextualSaveBar` React component. Check them out here: https://shopify.dev/apps/tools/app-bridge/react-components/contextual-save-bar
