### ISSUE TITLE
Modal Toggle Trigger 401 Unauthorized Error After 1 Minute On The Page

### ISSUE THREAD

**Issue by hamzasgd** [Shopify/shopify-app-bridge#310]
**Describe the bug**
When the shopify.modal.toggle('earnModal') function is triggered after waiting for 1 minute on the page, it results in a 500 internal server error. This error appears in the console and is associated with the same route where the modal is added. The route is automatically triggered upon showing the modal.

[https://imgur.com/Mclu9wR](url)

**To Reproduce**

Add a modal to a page using the Modal component from @shopify/app-bridge-react.
Navigate to the page where the modal is added.
Wait for 1 minute on the page without interacting with it.
Trigger the modal by executing shopify.modal.toggle('earnModal').
Observe a 500 internal server error in the console related to the route where the modal is added.

**Expected behaviour**
Triggering the modal with shopify.modal.toggle('earnModal') after waiting on the page should not cause any server errors. Instead, the modal should display as expected without any issues or errors in the console.

**Contextual information**
Packages and versions
@shopify/app-bridge @ 4.0.0
@shopify/app-bridge-react @ 4.0.0
@shopify/polaris @ 12.0.0

**Platform**
App Template: shopify-app-template-remix
Modal Component: Used from @shopify/app-bridge-react
Additional context
This issue seems to be related to the handling of modal triggers after a specific idle time on the page. It suggests there might be an unhandled exception or a timeout issue within the app bridge or the server setup that is not correctly managing the modal's state or the route's state after a period of inactivity.

**Comment by yuvrajharod** [comment]
Facing a similar issue on our end, it shows a 500 internal server error on our existing projects and a 401 when tried on a fresh template.

**Comment by hamzasgd** [comment]
This is a serious issue. When the modal is triggered, it initiates a GET request that returns a 401 error. If you spend 1 minute on the page, you will not be able to display the modal due to the error.

![app bridge modal](https://github.com/Shopify/shopify-app-bridge/assets/12862136/af91ae33-a158-41d6-bcb9-e4618025ce32)

**Comment by hamzasgd** [comment]
@charlesdobson please look into this thanks

**Comment by henrytao-me** [comment]
It is fixed. Can you try again and let me know please? Thanks 🙇

**Comment by hamzasgd** [comment]
@henrytao-me I will also test this on a new template.
