### ISSUE TITLE
Content Of Popover Appears Below Modal Instead of Within It

### ISSUE THREAD

**Issue by toilahuong** [Shopify/shopify-app-bridge#316]
## Describe the bug
When clicking on the activator, the content of popover appears below the modal instead of within it.
![image](https://github.com/Shopify/shopify-app-bridge/assets/76516959/3dff6234-a9cb-481c-adf0-aa1df0177966)

### To Reproduce
Steps to reproduce the behaviour:

Launch the app from '...'
Click on the activator
See error
Screenshot

### Expected behaviour
The content should appear within the modal when the activator is clicked.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge-react` @ `4.1.1`
- `@shopify/polaris` @ `12.0.0`

## Platform

- OS: MacOS 
- OS Version: 13.3.1
- App: [Chrome]

**Comment by meecrobe** [comment]
It's [recommended](https://github.com/Shopify/shopify-app-bridge/issues/301#issuecomment-1997669310) to use an `src` prop but it's [impossible](https://github.com/Shopify/shopify-app-bridge/issues/315#issuecomment-2006349252) to use many oh the app bridge's features inside a modal in that case.

**Comment by noelgoodday** [comment]
Same problem here. This is cross-posted here: https://github.com/Shopify/polaris/issues/11954

**Comment by Kaniwong** [comment]
Same issue here, I try to put a [combobox](https://polaris.shopify.com/components/selection-and-input/combobox?example=combobox-with-multi-select) into modal 
![image](https://github.com/Shopify/shopify-app-bridge/assets/46040581/5480c364-b146-4e60-a424-5a7ee4068673)

**Comment by FarrisIsmati** [comment]
Same thing happens with bulk actions, or any popover really. 😢

**Comment by bakura10** [comment]
This is really surprising that this is still not fixed. It's been months that App Bridge v4 has been released, and no sign of this being fixed. It makes it impossible for apps using modals to upgrade to v4. @henrytao-me sorry for insisting on this one, but when is this supposed to be fixed? :/

**Comment by bakura10** [comment]
@charlesdobson , I don't think this is a good solution though. The problem with `src` over directly using the modals:

* You can't take advantage of the routing system of Remix where one route would be the modal itself.
* It makes it extremely hard to work to pass parameters to a modal baked by a `src`. For instance, imagine that you have a list of items that you would like to edit in a modal, each of those items might not be identified by a ID or whatever to build its own URL.
* This makes the whole experience way slower, especially for an experiences involving a lot of different models.

Please re-consider this. Polaris components **must** be supported as part of modals.

**Comment by DeskmozUser** [comment]
@vividviolet I am facing similar issue  as I have mentioned in this comment can u look into this as I have tried the provided code
[https://github.com/Shopify/polaris/issues/11954#issuecomment-2270453604](url)

**Comment by traianturcu** [comment]
@MitchLillie I am still seeing the issue in 13.9.0 when using IndexFilters inside of a Modal - the sort popup and the search & filter tooltip still show outside of the modal..

**Comment by vividviolet** [comment]
Yes, you need the wrap the content of the modal in an AppProvider as documented [here](https://shopify.dev/docs/api/app-bridge/using-modals-in-your-app#react-components-using-react-portals).

**Comment by magecomp-shopify-team** [comment]
You must be using Polaris 13.19.x or higher for the Polaris App Provider to contextualize components built with React Portals.
