### ISSUE TITLE
The custom products feature missing in App Bridge 4.x.x.

### ISSUE THREAD

**Issue by WidgetCharmer** [Shopify/shopify-app-bridge#323]
Hello. Most of our apps add custom line items to the card via AppBridge. It is possible to do in AppBridge 3, but there is no such functionality in AppBridge 4. We double-checked that. Shopify sometimes calls it **“Quick Sale”**, **”Custom Line Item”**, or **“Custom Sale”**, but we really need it in our apps to be able to migrate. Here is our second attempt to ask you to pay attention to it, here the previous - https://github.com/Shopify/shopify-app-bridge/issues/319#issuecomment-2013126193.

And again. Here is the reference in the AppBridge 3 - https://shopify.dev/docs/api/app-bridge/previous-versions/actions/cart#add-line-item. 

<img width="786" alt="Screenshot 2024-03-21 at 6 34 41 PM" src="https://github.com/Shopify/shopify-app-bridge/assets/48135518/6af1cf56-f591-40f0-8554-a3a756d21763">

As you can see, the old version of SDK allows us to add a product with a custom name and a custom price. The new SDK allows us to add existing item variants only.

We really need the following method in AppBridge 4 to be able to migrate. **It’s critical**. 

Thanks!

**Comment by WidgetCharmer** [comment]
@vctrchu 
Hello. Did it was fixed in the latest release? Thanks!

**Comment by WidgetCharmer** [comment]
Hello @henrytao-me,
Did it was fixed in the latest release? Thanks!

**Comment by khallmark** [comment]
Resolved in 9.9

**Comment by WidgetCharmer** [comment]
> Resolved in 9.9

Hello @khallmark @vctrchu,

Can we check it somehow? The AppBridge docs seem to have the old version, and there are no updates in NPM. 

Thanks!

**Comment by henrytao-me** [comment]
@WidgetCharmer We will update the docs next week. It is being blocked by a back stack fix PR right now.
