### ISSUE TITLE
 Contextual Save Bar is hidden when opening ui-modal(react version)

### ISSUE THREAD

**Issue by DamirAid** [Shopify/shopify-app-bridge#324]
## Describe the bug

Contextual Save Bar is hidden when opening ui-modal(react version) 

When I open the ui-modal, the Contextual Save Bar disappears, I tried to trigger the opening of the save bar on the onShow event of the ui-modal to show CSB again, but it didn't help

UPD: 
if the contextual save bar cannot be shown together with an open ui-modal, then it would be nice to be able to open it again immediately after closing the modal (but it is still impossible to open it on the onHide event of the ui-modal)

```jsx
    <Modal
          id="my-modal"
          variant="max"
          onShow={() => {
            saveBar.show('my-save-bar');
          }}
        >
          <LivePreviewWrapper />
        </Modal>
```
### To Reproduce

Steps to reproduce the behaviour:

1. Trigger Contextual Save Bar 
<img width="1464" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/37047822/b1f3f0b0-ced1-418e-9b02-8bc411f4e965">

2. Open ui-modal 
<img width="1459" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/37047822/0e36141d-6511-4987-975d-d67891f85137">

3. Contextual Save Bar Hiding

### Expected behaviour

Contextual Save Bar should remain

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- @shopify/app-bridge-react@4.1.1
- `@shopify/polaris@12.12.1

## Platform

- OS: MacOS

- App: Google Chrome

**Comment by henrytao-me** [comment]
This is fixed on AB CDN. No changes required for your app.
