### ISSUE TITLE
Modal text is now big

### ISSUE THREAD

**Issue by bakura10** [Shopify/shopify-app-bridge#329]
Hi,

On the new app bridge modals, only the input text used to be bigger and did not respect Polaris style guide. Still, a few days ago, all the content became huge (even plain <Text> elements), giving merchants a very inconsistent visual experience whenever interacting with modals.

It would be great for all the Polaris styles to also be applied on modals. The issue seems to be coming from the fact that because all font sizes are styled in REM, they are based on the <html> font size. Unfortunately, on modal iframe, no font is set on the root so it uses the default browser.

Thanks.

**Comment by henrytao-me** [comment]
Hi @bakura10, if you use the new modal custom content, you can set classname for content element. All stylesheet in the main app iframe are copied to the modal iframe automatically.

**Comment by bakura10** [comment]
The issue is apparently fixed, so I am closing this.
