### ISSUE TITLE
App-bridge CDN modal only works on some stores

### ISSUE THREAD

**Issue by noahbaron91** [Shopify/shopify-app-bridge#332]
For some stores the app bridge modal doesn't load any content when .show() is called. I noticed this issue using both the ui-modal web-component and the @shopify/app-bridge-react Modal component. I've also cleared my browser cache, and still notice this problem.

This issue affects all variants of the ui-modal.

https://github.com/Shopify/shopify-app-bridge/assets/32229274/656f06e9-754a-4781-9aac-9e06e5c987b1

I looks like the div with modal-content-(random string) is not being forwarded.

Steps to reproduce the behaviour:

1.  Trigger .show() on a ui-modal web-component. The 
2. Go to a different development store
3. Trigger

### Expected behaviour

Should consistently forward the modal content.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge-react` @ `^4.1.2`

- OS: MacOS [for example MacOS, Windows, iOS, Android]
- OS Version: Ventura 13.4.1
- App: Chrome

Add any other context about the problem here, such as your app’s configuration (Node, Next.js, Rails).

Client side rendered React app with Node JS backend.

This was working properly until last night. Perhaps there was some bug that is being rolled out to the app bridge CDN right now.

**Comment by darrynten** [comment]
@noahbaron91 we asked for this and the request was denied

https://github.com/Shopify/shopify-app-bridge/issues/255

welcome to `@dev-main` life

**Comment by noahbaron91** [comment]
Yeah it's very scary knowing that one bad update from the Shopify team could wipe out your entire app functionality with nothing you can do about it. 

We've fully built our page builder app and invested thousands of dollars and man hours building it. We were in the process of submitting to the Shopify app store and then this bug hits us.

I can only imagine how it would feel once we have a sizeable customer base for our app and we're faced with an issue like this.

It's unreasonable to expect Shopify to ship updates to to app bridge with 0 bugs, and if we had a versioned system we could test out new releases before deploying to production.

I hope the Shopify team reconsiders their stance on having a unversioned, closed-source mandatory CDN script for their entire app ecosystem. Definitely seems like a potential single point of failure on Shopify's end.

**Comment by henrytao-me** [comment]
@noahbaron91 can you share what you see in the browser console when it doesn't load?

**Comment by noahbaron91** [comment]
@henrytao-me here is a recording of the console:

https://github.com/Shopify/shopify-app-bridge/assets/32229274/c8198451-57df-494d-b27a-0a6d92f26210

**Comment by henrytao-me** [comment]
@noahbaron91 looks like your app works now. However, there are a lot of javascript are injected before App Bridge CDN script which is an issue (maybe a different one because I didn't see any related error in console of your video). Can you make sure App Bridge CDN script is injected first before any other scripts?

**Comment by noahbaron91** [comment]
@henrytao-me On my browser the issue hasn't been resolved yet. Could you please point me to the additional javascript we're loading? We do load other CDN scripts but we make sure to do that after loading the app bridge CDN.

On the development server I think vite adds some additional scripts for hot reloading, however in our production environment it still breaks with nothing before the app bridge script:
<img width="1512" alt="Screenshot 2024-04-08 at 2 49 37 PM" src="https://github.com/Shopify/shopify-app-bridge/assets/32229274/cd8c2062-3b12-42de-bc61-117b41c03d78">
   

Here is the index.html:
<img width="1512" alt="Screenshot 2024-04-08 at 2 43 22 PM" src="https://github.com/Shopify/shopify-app-bridge/assets/32229274/82e50996-1c84-49f5-9e41-74bc9cd20a18">

The %VITE_SHOPIFY_API_KEY% is replaced with env variables:
https://vitejs.dev/guide/env-and-mode.html#html-env-replacement

**Comment by henrytao-me** [comment]
@noahbaron91 Try to swap `setSelectedPageId` like below. However, I still don't see why the order matter. Let me know how it goes.

```ts
  const handleSelectPage = async (pageId: string) => {
    setSelectedPageId(pageId);
    await shopifyModalRef.current?.show();
  };
```

**Comment by noahbaron91** [comment]
Hi, unfortunately that change didn't work for me. I'll work on creating a minimally reproducible example for you right now so it's easier to find the root cause.
