### ISSUE TITLE
App-Bridge ui-modal does not support some Polaris web-components.

### ISSUE THREAD

**Issue by AgneshV** [Shopify/shopify-app-bridge#343]
## Describe the bug

I've opened the modal using the App-Bridge ui-modal and tried to add some Polaris buttons and links into the modal body. But they do not support any of these Polaris web-components

1. Code

` <ui-modal id="test-modal">
    <Box as="div" padding="400">
      <TextContainer>
        <Button variant="tertiary" onClick={() => bundleProductQty()}> View Qty </Button>
      </TextContainer>
    </Box>
    <ui-title-bar title="Important Note">
      <button onClick={() => shopify.modal.hide('test-modal')}>Cancel</button>
      <button variant="primary" onClick={() => ChangePlan()}>Confirm</button>
    </ui-title-bar>
  </ui-modal>`

2. Shopifi app-bridge cdn
    
    <script src="https://cdn.shopify.com/shopifycloud/app-bridge.js" preload></script>

3. See error

https://www.awesomescreenshot.com/video/27251219?key=ce3e04e0832a6ed9cc05e567424bdbff

Does anyone have a solution for this kind of problem?

### Packages and versions

List the relevant packages you’re using and their versions. For example:

- `@shopify/app-bridge` @ `3.7.9`
- `@shopify/polaris` @ `12.15.0`

**Comment by charlesdobson** [comment]
Hi @AgneshV 👋,

If you want to use the Polaris React components, you need to use the [App Bridge React](https://www.npmjs.com/package/@shopify/app-bridge-react) `Modal` component as it sets up the React Portal for you: https://shopify.dev/docs/api/app-bridge-library/react-components/modal.

Please reopen if that doesn't solve the problem.
