### ISSUE TITLE
shopify.resourcePicker displays variants despite choosing type="product"

### ISSUE THREAD

**Issue by ybouane** [Shopify/shopify-app-bridge#348]
## Describe the bug

When calling:
```
const selection = await shopify.resourcePicker({
  type		: 'product',
  multiple		: true,
});
```
The modal that shows up allows selecting both products and variants which is undesired. I only want the user to select products, not specific variants.

### To Reproduce

Use the code provided and you'll get a window like this:
<img width="615" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/14046002/16bd01cb-79da-44a4-afeb-75d8625289e8">

### Expected behaviour

Variants should be selectable when type == variant not product.

## Contextual information
"@shopify/app-bridge-react": "^4.1.3",
"@shopify/polaris": "^12.0.0",
"@shopify/app-bridge-types": "^0.0.13",

### Additional context
Using the remix template.

**Comment by fabregas4** [comment]
Add
`filter: { variants: false }`
to the config

**Comment by MitchLillie** [comment]
@fabregas4 is correct. @ybouane let us know if this solves your issue.
