### ISSUE TITLE
Error after sent the session token

### ISSUE THREAD

**Issue by eternalparquet** [Shopify/shopify-app-bridge#36]
Hello I am trying to authenticate with session token but after I've sent the token to the backend with a post ajax request I get this error message when I reload the page with app bridge:
`"Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://shop.myshopify.com') does not match the recipient window's origin ('https://my.ngrok.io')."`

The shopOrigin doesn't match with the redirect url because If I redirect to url in admin page with the ajax request I get this error:
```
Access to XMLHttpRequest at 'https://shop.myshopify.com/admin/auth/session' from origin 'https://my.ngrok.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I followed the documentation.

This is the code to get token and post token:
```
     const app = AppBridge.createApp({
          apiKey: "{{ api_key }}",
          shopOrigin: "{{ shop }}"
      });
const sessionToken = utils.getSessionToken(app);
                    sessionToken.then((successSessionToken) => {
                        if (successSessionToken) {
                            var xhttp = new XMLHttpRequest();
                            xhttp.open("POST", "{{ session_uri }}", true);
                            xhttp.setRequestHeader('Content-Type', 'application/json')
                            xhttp.setRequestHeader("Access-Control-Allow-Origin", '*');
                            xhttp.setRequestHeader("Authorization", 'Bearer ' + successSessionToken);
                            xhttp.onreadystatechange = function() {
                                if (this.readyState == 4 && this.status == 200) {
                                    newpermissionUrl = this.responseText;
                                    Redirect.create(app).dispatch(Redirect.Action.ADMIN_PATH, newpermissionUrl);
                                }
                            };
                            xhttp.send();
```
Python flask for the backend.

**Comment by lukashambsch** [comment]
@eternalparquet I'm running into the same issue. Did you figure out the problem?

**Comment by rsbowers** [comment]
How is there no one from the Shopify team responding to this?  It's been over a year, and no one cares to reply?  This issue is littered all over the Shopify forums, and there is zero help from the team.  It's a shame that we can't get actual support here.

**Comment by kirkkhua** [comment]
Experiencing the same on @shopify/app-bridge 3.2.2 (tried this as an alternative to using unpkg CDN). It seems that we can't use this yet for embedded apps, unfortunately. Getting back to CDN based setup.

**Comment by amoallim15** [comment]
Experiencing the same issue on @Shopify/app-bridge 3.1.0.
It is a harmless issue, but still, an issue to be resolved.
Shopify team, please take a look.

**Comment by henrytao-me** [comment]
@amoallim15 Can you please share your setup, specifically how you initialize App Bridge and obtain the sessionToken?

Few things could go wrong in the original post:
- `AppBridge.createApp` needs to provide `host` instead of `shopOrigin`
- `https://shop.myshopify.com/admin/auth/session` What is this url? It's invalid imo.

**Comment by charlesdobson** [comment]
Closing as stale. Please reopen if needed!

**Comment by PoptropicaSahil** [comment]
++ same issue!
