### ISSUE TITLE
App Bridge 3 migration

### ISSUE THREAD

**Issue by Crunchyman-ralph** [Shopify/shopify-app-bridge#360]
# Issue summary

Write a short description of the issue here ↓

- Shopify App Bridge 3 migration, ExitIframe doesn't work with the new history.pushState

## Expected behavior

What do you think should happen?

- Should redirect outside of the iframe

## Actual behavior

- Redirects outside the iframe, but doesn't take the query params with it

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. 1. 1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case.

## Specifications

- Browser:
- Device:
- Operating System:

**Comment by lizkenyon** [comment]
Hi there 👋 

I am going to move this issue the App Bridge Repository.

**Comment by charlesdobson** [comment]
Hi @Crunchyman-ralph,

Which page are you trying to redirect to? In the new App Bridge, you can just use `window.open` to navigate to another page in the Shopify Admin. That looks something like this:

```
open('shopify://admin/products?foo=bar', '_top');
```

**Comment by Crunchyman-ralph** [comment]
Works like a charm, why isn't this documented ?

**Comment by charlesdobson** [comment]
We've added a few examples here: https://shopify.dev/docs/api/app-bridge-library/apis/navigation#example-navigating-to-pages-in-the-shopify-admin

Would it be helpful if we added an example with query params?

---

Going to close this issue out as completed but feel free to keep chatting about docs here!
