### ISSUE TITLE
App bridge 3 - POS Toast no longer shows message content

### ISSUE THREAD

**Issue by alexdover** [Shopify/shopify-app-bridge#372]
## Describe the bug

I am using app bridge version 3.7.10 and we have noticed that Toast messages are no longer showing the `message` but instead are showing a blue dialog with just an exclamation mark, shown below:

![IMG_0362](https://github.com/Shopify/shopify-app-bridge/assets/1886367/dfd585f2-def1-4d92-a3bb-8cc52903fe68)

I'm not sure when this started, but I am unable to find a way to workaround it.

**Comment by vctrchu** [comment]
@alexdover We've added a fix into next POS version!
