### ISSUE TITLE
Cannot select when selecting a product then cancel or close.

### ISSUE THREAD

**Issue by minhduc17801** [Shopify/shopify-app-bridge#374]
## Describe the bug

When close or cancel after selecting a product with the resource picker popup, it will then become impossible to select the product when reopened.

### To Reproduce

Steps to reproduce the behaviour:

1. Open resource picker popup
2. Select a product
3. Close or cancel
4. Reopen
```
const selected = await shopify.resourcePicker({
      type: 'product',
      filter: {
        variants: false,
        archived: true,
        draft: true,
        hidden: true,
      },
    });
```

Video: [https://www.loom.com/share/859308c3dec44df2a8bc1d321582f89a?sid=4d90d573-aa32-4198-89cc-bbbe006e0711](url)

### Expected behaviour

Can select.

### Packages and versions

List the relevant packages you’re using, and their versions.

- `@shopify/app-bridge-react` @ `4.1.3`

**Comment by alfonso-noriega** [comment]
This bug has been fixed [here](https://github.com/Shopify/app-ui/issues/1286)
