### ISSUE TITLE
v2.0.0 does not recognize the shopOrigin when passed as a host in the new initialization

### ISSUE THREAD

**Issue by ctrlaltdylan** [Shopify/shopify-app-bridge#38]
## Describe the bug

When initializing the app bridge on the frontend after OAuth, the AppBridge Provider does not recognize when the shopOrigin is passed correctly:

![CleanShot 2021-04-01 at 13 36 45](https://user-images.githubusercontent.com/2694734/113332561-51137200-92ef-11eb-8ee1-e466bc5e9cd7.png)

### To Reproduce
```
  console.log(shopOrigin); // just verifying that the test.myshopify.com string is being passed
  const config = {
    apiKey: process.env.NEXT_PUBLIC_SHOPIFY_API_PUBLIC_KEY,
    host: shopOrigin,
    forceRedirect: true,
  };
```

### Expected behaviour

To be able to instantiate the app bridge according to the new `host` signature.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/next-app-js` @ 2.0.0 or 2.0.1
- `@shopify/app-bridge-utils` @ 2.0.0 or 2.0.1

## Platform

Any web browser

### Additional context

Using Next.JS

**Comment by ctrlaltdylan** [comment]
Welp. I feel dumb.

There's a new URL parameter that's actually called `host`. I wrongly assumed the `shopOrigin` == `host`. I'll update to match.

**Comment by hannachen** [comment]
> There's a new URL parameter that's actually called `host`. I wrongly assumed the `shopOrigin` == `host`. I'll update to match.

Hey @ctrlaltdylan thanks for the quick feedback! The `host` parameter is indeed different from `shop`, that's why it had to go into a major release of App Bridge. It looks like the migration guide should link to the full details here:  https://shopify.dev/tutorials/get-and-store-the-shop-origin so thanks for flagging this.

If you are already on App Bridge, you don't need to update to 2.0 right at this moment if you are not yet ready to update your application code.

**Comment by hannachen** [comment]
Closing this so we can direct additional open questions to the forums: https://community.shopify.com/c/Shopify-Community/ct-p/en

**Comment by overallduka** [comment]
> > I'm using Rails and JWT authentication, this is happening on splash/home(unauthenticated) page, how I can get/parse the host with JWT?
> 
> Hi @overallduka, is your app embedded at this point? Also, which area of the code is responsible for setting the cookie/session? With browsers dropping support for 3rd party cookies, you may need to manually pass this information into your page using the `GET` url parameter similar to what's being described in the tutorial: https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-shopify-app-bridge
> 
> Edit: if your Rails app uses the `shopify_app` gem, you may need to update that to the latest version if you haven't already done so.

Hey @hannachen,

Yes, my app is embedded using new JWT auth, and is using the `shopify_app` gem. By now I have just used the session in the view:

```
   <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      host: session[:shopify_domain],
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: @shop_origin || (@current_shopify_session.domain if @current_shopify_session),
      debug: Rails.env.development?,
      load_path: params[:return_to] || Rails.application.config.jwt_root_page
    } ) %>
```

I'm using version 16.1.0 of shopify_app, maybe this is the issue. I will try the latest release.

Thank you by now.
