### ISSUE TITLE
Fetch doesn't automatically inject auth token when request comes from <ui-modal /> 

### ISSUE THREAD

**Issue by vadym-perenesenko-moc** [Shopify/shopify-app-bridge#383]
## Describe the bug

Fetch doesn't automatically inject auth token when request comes from `<ui-modal /> `

### To Reproduce

Steps to reproduce this behaviour:

1. If request comes from the app iframe, it is automatically signed.

2. If request comes from the `<ui-modal />` iframe, the request is not signed. 

https://github.com/Shopify/shopify-app-bridge/assets/93665352/85a32144-f1b1-44a2-a69a-ca7215bda8d1

I also noticed that the global object in `window.shopify` does not have an idToken method if you look at the object of the iframe from `<ui-modal />`

<img width="1240" alt="SCR-20240620-pxaz" src="https://github.com/Shopify/shopify-app-bridge/assets/93665352/a7de7615-9f91-4ff3-88fe-1a02435c74bc">
<img width="1298" alt="SCR-20240620-pxqm" src="https://github.com/Shopify/shopify-app-bridge/assets/93665352/cf135d12-b355-424a-8dc3-519eb90d3039">

### Packages and versions

- app-bridge.js from CDN 

## Platform

- OS: [MacOS 
- OS Version: [14.4]
- App: [Chrome, Safari]

**Comment by vadym-perenesenko-moc** [comment]
If this is how it was intended, then tell us how to properly sign the requests that come from `<ui-modal /> `we really need it. We render in` <ui-modal />` new page using the src.

**Comment by vadym-perenesenko-moc** [comment]
@lmtNoLimit thanks, it helped me. I can now get the idToken from the app iframe and personally sign the necessary requests

**Comment by charlesdobson** [comment]
Hi @vadym-perenesenko-moc,

We've just shipped a fix so calling `fetch` directly from your modal now gets the appropriate header. @lmtNoLimit is correct here but you no longer need to call `window.opener` as we're proxying the calls.

I'll close this out for now. Please let me know if that doesn't work for you!
