### ISSUE TITLE
Unexpected attributes on <ui-nav-menu>

### ISSUE THREAD

**Issue by mesija** [Shopify/shopify-app-bridge#388]
## Describe the bug

The `<ui-nav-menu>` component throws an error when unexpected attributes such as `wfd-invisible` and `bis_size` are added by third-party plugins. This issue causes the Shopify App Bridge to stop working, severely impacting our app's functionality.

Unfortunately, the exact plugins adding these attributes are unknown to us, as these errors occur on clients' setups, and we have not yet identified the specific plugins responsible. It appears to be a widespread issue, potentially involving multiple plugins.

### To Reproduce

Steps to reproduce the behaviour:
1. Open the app from the Shopify admin.
2. During the loading process, some browser plugins seem to add their own attributes to the `<ui-nav-menu>` component.
3. See error in the console indicating unexpected attributes.

![image](https://github.com/Shopify/shopify-app-bridge/assets/7571188/7b8ba6b1-0fd0-4082-aa2a-e93cdc5387b8)

### Expected behaviour

The Shopify App Bridge should ignore unexpected attributes and issue warnings instead of errors. This would prevent third-party plugins from breaking the app.

### Additional Notes

It is recommended to adjust the validation for all Shopify App Bridge components globally. Since navigation is the first component to load, if attribute validation is not corrected across all components, this issue is likely to appear elsewhere in the app.

### Packages and versions

- `@shopify/app-bridge` @ `4`
- `@shopify/app-bridge-react` @ `4.1.3`
- `@shopify/polaris` @ `13.5.0`

## Platform

The errors have been observed on both Windows and MacOS, as well as in Chromium-based browsers and Mozilla Firefox. The provided example is just one instance, and the issue is not tied to any specific browser or operating system.

- OS: MacOS, Windows
- Browsers: Chrome, Firefox

### Additional context

Other relevant dependencies in our project include:
- `@reduxjs/toolkit` @ `2.2.5`
- `@sentry/react` @ `8.10.0`
- `react` @ `18.3.1`
- `react-dom` @ `18.3.1`
- `redux` @ `5.0.1`
- and more (full list can be provided if necessary).

This issue has significant impact as it affects core functionality of our app, which relies heavily on the Shopify App Bridge for various features.

**Comment by quard8** [comment]
I have the same errors, but I don't see the impact on functionality. It's more annoying.

**Comment by mesija** [comment]
Reference: One of our clients has also reported this issue in their GitHub issue #389: [Metafield Save button disappear](https://github.com/Shopify/shopify-app-bridge/issues/389).

**Comment by mesija** [comment]
Hey @charlesdobson,

Thank you for addressing the issue. Your solution to console.error() instead of throw() sounds like a great alternative. Logging the error is indeed necessary, but the key point is that it won't break the client's functionality anymore.

Thanks again for resolving this!

**Comment by tomaszhkob** [comment]
Hi @charlesdobson ,

I’m encountering an issue in my app that seems to break the Polaris components using App Bridge (Popup and Tooltip). I’ve tried several approaches to resolve it, but so far no luck. It also happens randomly, so I’m not sure what’s causing it. Do you have any idea why this would cause the Polaris components to stop working?
