### ISSUE TITLE
Error when using nested app bridge modal 

### ISSUE THREAD

**Issue by tienct01** [Shopify/shopify-app-bridge#395]
## Describe the bug

Hi guys, I used app bridge max modal on my app.
The issue when I use another app bridge modal, it show error a.show() or a.hide() is not a function.

### To Reproduce

Steps to reproduce the behaviour:

1. Use nested modal in Tabs Component Polaris in Max Modal
2. Navigate to another tabs has <Modal />  component
3. See error
![image](https://github.com/Shopify/shopify-app-bridge/assets/64533003/6ec1f1a1-9a57-4430-b22c-ba841b149d39)

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `4x`
- `@shopify/app-bridge-react` @ `^4.1.3`
- `@shopify/polaris` @ `^12.0.0`

## Platform

- OS: windows
- OS Version: 10
- App: Microsoft Edge, Chrome

**Comment by charlesdobson** [comment]
Hey @tienct01,

When you use a nested modal inside a max modal, you need to define it beside that max modal, rather than inside of it.

So, for example, like this:

```
function NestedModal() {
  const shopify = useAppBridge();

  function handlePrimaryAction() {
    shopify.modal.show('max-modal-nested');
  }

  return (
    <>
      <button onClick={handlePrimaryAction}>
        Show Max Modal with nested modal
      </button>
      <Modal id="max-modal-nested" variant="max">
        <button onClick={() => shopify.modal.show('nested-modal')}>
          Open nested modal
        </button>
      </Modal>
      <Modal variant="small" id="nested-modal">
        <p>test</p>
      </Modal>
    </>
  );
}
```

That will open the nested modal inside of it. If you're using a `src` max modal, that works too, you'll just need to use `window.opener.shopify.modal.show('nested-modal')` inside the max modal instead.

---

Can you try that out and let me know if you're still experiencing the issue?

**Comment by tienct01** [comment]
Thank you for your response. Using this method makes the modal work smoothly, but doing so will separate the logic of the component, making the code harder to read. Can you adjust it so that it is possible to render a modal within a modal?

**Comment by YevhenTarashchyk** [comment]
Sorry, but in my case (max-modal case) it means that I need to change a HUGE chunk of code just to make this work modal inside modal work... this kind of lame. Devs needs to figure out how to manage this

**Comment by YevhenTarashchyk** [comment]
This is not only regarding modals inside modals ... sometimes I am getting the same error just using SaveBar conditionally somewhere inside modal.
