### ISSUE TITLE
open several max modals

### ISSUE THREAD

**Issue by YevhenTarashchyk** [Shopify/shopify-app-bridge#397]
I am experiencing one problem. I open max modal where I have opportunity to open another max modal and when I am trying to do that second modal doesn't open. Can somebody explain why is that ? 
Expected: Modal 2 lies on top of modal 1
Actual: Modal 2 is not displayed

**Comment by charlesdobson** [comment]
Hi @YevhenTarashchyk,

This is intentional to ensure users don't lose context. You can open a `small`, `base`, or `large` modal from a `max` modal, but you can't open another `max` modal.

**Comment by YevhenTarashchyk** [comment]
@charlesdobson morning, is there any information about this in docs ? Cause I end up in situation when I spent a lot of time on a feature that actually will no longer work in v4
