### ISSUE TITLE
Pos.Action.CLOSE ignored on iOS POS

### ISSUE THREAD

**Issue by FezVrasta** [Shopify/shopify-app-bridge#40]
## Describe the bug

I'd like to close my app modal automatically after the user finished using my app on the Shopify POS app on iOS.

The documentation says I should initialize a `pos` instance with `Pos.create(app)` and then call `pos.dispatch(Pos.Action.CLOSE)` when I want to close the page.

Unfortunately this doesn't seem to work, the page stays open after I dispatch the action.

### To Reproduce

Steps to reproduce the behaviour:

1. Launch Shopify POS
2. Click on my App tile
3. My app dispatches the `Pos.Action.CLOSE` action
4. The page is not closed

### Expected behaviour

The App page should automatically close.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `1.30.0`
- `@shopify/app-bridge-react` @ `1.30.0`
- `@shopify/polaris` @ `6.2.1`

## Platform

- OS: iOS 
- OS Version: 14.4.2
- App: Shopify POS 6.39.0

**Comment by derrickrc** [comment]
@FezVrasta this should work, I use it in my apps just fine. Can you share the relevant code? If you're on a mac and connect your iPad, and then open Mac Console and filter for App Bridge, do you see any additional errors logged?

**Comment by FezVrasta** [comment]
Hi @derrickrc, how do you inspect web views inside the Shopify POS app? When I connect the iPhone to my Mac and open a web view of my app it doesn't show up in the Safari Developer Tools.

**Comment by derrickrc** [comment]
Please follow the instructions in my previous comment, you use the Console
application in OSX and then filter for "App Bridge"

**Comment by FezVrasta** [comment]
I do see this message that looks suspicious to me though:

```log
Optional Params: [{"group":"Features","type":"APP::FEATURES::UPDATE","payload":{"Modal":{"Share":{"SHOW":{"Subscribe":true,"Dispatch":true},"CLOSE":{"Subscribe":true,"Dispatch":false}},"Cart":{"UPDATE":{"Subscribe":true,"Dispatch":true},"REMOVE_LINE_ITEM_DISCOUNT":{"Subscribe":true,"Dispatch":true},"FETCH":{"Subscribe":true,"Dispatch":true},"REMOVE_PROPERTIES":{"Subscribe":true,"Dispatch":true},"ADD_LINE_ITEM":{"Subscribe":true,"Dispatch":true},"REMOVE_LINE_ITEM_PROPERTIES":{"Subscribe":true,"Dispatch":true},"REMOVE_DISCOUNT":{"Subscribe":true,"Dispatch":true},"REMOVE_LINE_ITEM":{"Subscribe":true,"Dispatch":true},"SET_LINE_ITEM_PROPERTIES":{"Subscribe":true,"Dispatch":true},"ADD_CUSTOMER_ADDRESS":{"Subscribe":true,"Dispatch":true},"CLEAR":{"Subscribe":true,"Dispatch":true},"SET_DISCOUNT":{"Subscribe":true,"Dispatch":true},"SET_PROPERTIES":{"Subscribe":true,"Dispatch":true},"UPDATE_LINE_ITEM":{"Subscribe":true,"Dispatch":true<…>
```

It lists `CLOSE` with `{"Subscribe":true,"Dispatch":false}`, does it mean I don't have access to the dispatch action?

**Comment by derrickrc** [comment]
Try this:
````

<!DOCTYPE html>
<script src="https://unpkg.com/@shopify/app-bridge@1.30.0/umd/index.js"></script>
<script>
const AppBridge = window['app-bridge'];
const params = new URL(window.location.href).searchParams;
const shop = params.get('shop');
console.log('shop is ' + shop)
var createApp = AppBridge.default;
app = createApp({
      apiKey: 'yours',
      shopOrigin: shop
    });

var actions = AppBridge.actions;
var Pos = actions.Pos;
var pos = Pos.create(app); 
pos.dispatch(Pos.ActionType.CLOSE);                    

</script>
<style>
html, body {
  background-color: #f6f6f7;
}
img {
  max-width: 50vw;
  margin: auto;
  margin-top: 10vh;
  display: block;
  filter: drop-shadow(0 10px 10px rgba(0,0,0,.2));
}
</style>
<img src="/assets/print-done.svg" alt="Done!" />

**Comment by FezVrasta** [comment]
Oh, thanks! The documentation is wrong then 🤦 it's `Pos.ActionType.CLOSE`, not `Pos.Action.CLOSE`

https://shopify.dev/tools/app-bridge/actions/pos#close-an-app-embedded-in-shopify-pos

**Comment by derrickrc** [comment]
@andrewapperley looks like the documentation was never actually updated: https://community.shopify.com/c/Shopify-APIs-SDKs/App-Bridge-Close-cart-Pos-action-only-available-with-Android-v5/m-p/771273#M50922

**Comment by andrewapperley** [comment]
Thanks for bringing this up. I will follow up with the docs team to get this fixed. Really frustrating.

**Comment by alexdover** [comment]
So glad I just discovered this thread! The docs are still wrong and suggest `Pos.Action.CLOSE`

**Comment by andra-la** [comment]
Sorry to hear the problem was with the docs! Thanks for following up on this. ❤️ 
@andrewapperley @derrickrc @joeyfreund In the future, anyone can flag the dev docs teams by opening a GH issue here: https://github.com/Shopify/shopify-dev/issues/new/choose
