### ISSUE TITLE
App Bridge Resource Picker on Mobile App Single Variant Bug

### ISSUE THREAD

**Issue by charles-tyler** [Shopify/shopify-app-bridge#418]
## Describe the bug

When using the App Bridge Resource Picker on the iOS or Andriod Shopify Mobile App (set to `type` = `variant`) it does not return "Single variant product" variant information.

This is only on the Mobile version of App Bridge, not on web. This is a new bug - first alerted to us towards the end of last week. It is happening on all of our apps.

For a visual comparison of the resource picker data between web and mobile, please refer to:
- https://www.diffchecker.com/v51jHpJB/ (Web data on left, Mobile data on right)

- https://shopify.dev/docs/api/app-bridge-library/apis/resource-picker

**Issue:**

- Single-variant products fail to add when selected through the resource picker.
- Root cause: The variants field is received as an empty array on mobile.
- Impact: Single-variant products or those with ‘hasOnlyDefaultVariant: true’ cannot be added to the table list.
- This issue is specific to mobile apps; the web version functions correctly.

### To Reproduce

1. Launch an embedded app from within the Shopify Mobile App
2. Open the Product Resource Picker set to `type` = `variant`
3. Select a product that is ‘hasOnlyDefaultVariant: true’ 
4. Product variant information doesn't get passed from the API

For example in our app EasyScan.

https://github.com/user-attachments/assets/a8edbdbc-cc2c-42eb-8fbe-f23127f202dd

### Expected behavior

To return the product variant information as shown in the Web version above.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `^3.7.9`
- `@shopify/app-bridge-react` @ `^3.7.9`
- `@shopify/polaris` @ `10.50.1`

## Platform

- OS: iOS, Android
- OS Version: Both most recent
- App: Shopify Mobile App

**Comment by henrytao-me** [comment]
A fix for this will be merged soon. For clarification, I think the query you did should be for `product` query with `filter.variants: false`, not `type: variant`

```
shopify.resourcePicker({
    type: 'product',
    action: 'add',
    multiple: 10,
    filter: {
      hidden: true,
      variants: false,
      draft: true,
      archived: true,
    },
})
```

**Comment by henrytao-me** [comment]
Yes. I am on it.
