### ISSUE TITLE
Pressing back button on mobile to cancel resource picker selection prevents opening again

### ISSUE THREAD

**Issue by TheSecurityDev** [Shopify/shopify-app-bridge#444]
## Describe the bug

On the Shopify mobile app with App Bridge v4 resource picker, if you press the back button it closes the picker. However, the promise is not resolved and the picker cannot be opened again. This seems to happen only when no items are selected.

Also, when selecting collections, pressing the X button to cancel the selection causes the same issue.

### To Reproduce

On the Shopify mobile app, run:
```ts
await shopify.resourcePicker({
        type: "collection",
        multiple: true,
        action: "select"
}
```

Then press the back button to cancel, or X if type is "collection". Then observe that the promise is not fulfilled and you can't open the picker again.

### Expected behaviour

App Bridge should handle canceling the selection and allow opening again.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- App Bridge v4 (CDN)
- `@shopify/app-bridge-react` @ `4.1.3`,
- `@shopify/polaris` @ `10.50.3`

## Platform

- OS: Android
- OS Version: 10
- App: Shopify mobile app

### Additional context

- NodeJS 20
- NextJS 14

**Comment by henrytao-me** [comment]
I found the bug. This should be fixed in the new Shopify Mobile build next week.
