### ISSUE TITLE
Resource picker unable to select multiple options, if filter query is set

### ISSUE THREAD

**Issue by cupnoodle** [Shopify/shopify-app-bridge#459]
## Describe the bug

The resource picker is unable to select more than one option, despite `multiple: true` is being set, when the filter query is set.

Example : `shopify.resourcePicker({type: 'variant', action: 'select', multiple: true, filter: { query: "product_id:123456" } })`

### To Reproduce

Steps to reproduce the behaviour:

1. Initialize the Resource Picker as above and create a button to open it.
2. See that only one variant option is selectable, despite "multiple" is set to true.

### Expected behaviour

Multiple variant options should be selectable, instead of limiting to just one

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

@shopify/app-bridge :  App bridge CDN version, Admin Extension version unstable and 2024-10, 2025-01

## Platform

Replicable at all OS, Shopify Admin

**Comment by MitchLillie** [comment]
Hi @cupnoodle - I'm not able to reproduce on my end. Can you share some more details about the specific product you're filtering for and the store you're using? You can DM me on the Partners Slack if that's easier.

**Comment by cupnoodle** [comment]
Sorry @MitchLillie  , I just realized it was from Admin Action extension (https://shopify.dev/docs/api/admin-extensions/unstable/api/resource-picker) , not the App Bridge ones, I will create issue on the extension repository.
