### ISSUE TITLE
Embedded App Navigation shows wrong active tab when used with RoutePropagator, ClientRouter, along with react-router

### ISSUE THREAD

**Issue by ManasN** [Shopify/shopify-app-bridge#46]
## Describe the bug

As the title states, Embedded App Navigation shows wrong active tab when used with RoutePropagator, ClientRouter, along with react-router.

### To Reproduce

Steps to reproduce the behaviour:

1. Create a new embedded app / Modify existing one to include an "Embedded Navigation" bar
2. Have internal app routing set to react-router default, which is browserURL
3. Setup <RoutePropagator /> and <ClientRouter /> so your embedded  app won't refresh the whole page.
4. Add navigation items in Embedded Navigation 
5. Clicking on the Embedded Navigation will work but active navigation tab doesn't change. 

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `1.30.0`
- `@shopify/app-bridge-react` @ `1.30.0`
- `@shopify/polaris` @ `6.3.0`

## Platform

- Windows; Shopify App

### Additional context

Using React with React Router

**Comment by hannachen** [comment]
Thanks for your patience everyone, there were a few hiccups in attempting to ship the fix. It should be in as of Friday June 4th, please let me know if you are still experiencing the bug.

**Comment by hirokia45** [comment]
@hannachen 
I'm still having this bug. I'm using the most recent version.
- @shopify/app-bridge @2.0.3
- @shopify/app-bridge-react @2.0.3

I'm wondering if others are still having the bug.

**Comment by redareda9** [comment]
As of August, there is nothing to fix this.

**Comment by RishabhTayal** [comment]
Any update on this? Is there any fix for this issue?

**Comment by RishabhTayal** [comment]
@henrytao-me Tried it just now and it works. 👍 

Earlier I had it like this and it didn't work

`<NavigationMenu navigationLinks={[...]} matcher={(link, location) => link.destination === location.pathname } />`

**Comment by henrytao-me** [comment]
We fixed the nav issue here https://github.com/Shopify/shopify-app-bridge/issues/198. So, it should work with the customer matcher. 🙇
