### ISSUE TITLE
HTML formatting within modal content?

### ISSUE THREAD

**Issue by axis80** [Shopify/shopify-app-bridge#5]
Is there any way to include HTML formatting within the contents of a Modal, other than by loading the contents from an external URL?

In my case, I need to bold the name of a resource in a delete confirmation modal, in this manner:

![image](https://user-images.githubusercontent.com/6088477/90347019-918ddc00-dffb-11ea-807a-34e73bc80031.png)

I have not been able to find any way to do that using the Shopify App Bridge React component implementation of the modal.  The value that I supply to the `message` prop always gets HTML-encoded when displayed.

**Comment by iainmcampbell** [comment]
Hi @axis80, message modals only support plain text content. If you need formatting, you’ll have to use an iframe modal.
