### ISSUE TITLE
Can the resource picker preserve the user's selection order?

### ISSUE THREAD

**Issue by macdonaldr93** [Shopify/shopify-app-bridge#51]
### Describe the feature you’d like

When a user selects resources in the resource picker, they are returned in the order that they are displayed.  Ideally, the order of the selected resources would be returned in the order that the user selected them in.

### Describe alternatives you've considered

The only alternative I have right now is to rebuild the product picker in my app.

### Additional context

The selected resources get returned in the `onSelection` callback. This is where the order is not preserved.

**Comment by iwoodruff** [comment]
hey @macdonaldr93 this is a great suggestion – i appreciate the input & have taken a note for when we revisit pickers
