### ISSUE TITLE
"New" Shopify POS for Android - can't get Cart ADD_LINE_ITEM to work with existing variantId

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#58]
I am testing some things on the new Android POS and for some reason I can't get this to work: https://shopify.dev/tools/app-bridge/actions/cart#add-line-item. 

It works when adding a Quick Sale line item, but when I pass the `variantId` it simply doesn't work. I have tried both `int` and `string` data types for the variantId and no joy. The same code works on new Shopify POS for iOS. Is this broken or am I missing something?

**Comment by MikeEmery** [comment]
Adding on to this, I have some code that works fine on iOS but does not work on Android and seems to be the same issue:
```
  checkOut() {
    const app = this.context;
    const pos = Pos.create(app);
    const cart = Cart.create(app);
    const orders = this.props.focusedCustomerOrders;

    cart.dispatch(Cart.Action.CLEAR);

    orders.forEach(order => {
      const data = {
        variantId: this.extractVariantId(order.variantId),
        title: order.title
      };

      cart.dispatch(Cart.Action.ADD_LINE_ITEM, {
        data
      });
    })

    pos.dispatch(Pos.ActionType.CLOSE);
  }
  ```

**Comment by michael-visualsquares** [comment]
I also got the same issue on Android. Quick sale payload is working but existing variant Id is not.

```
  // Not working
  async testaddtocart() {
    const variantId = '39440334913667';
    var unsubscriber = this.cartApp.subscribe(Cart.Action.UPDATE, (payload) => {
      // closeApp(this.app);
      unsubscriber();
      this.loadingAddProduct = false;
    });

    const lineItemPayload = {
      variantId: parseInt(variantId),
      quantity: 1,
    };
    this.cartApp.dispatch(Cart.Action.ADD_LINE_ITEM, {
      data: lineItemPayload,
    });
  }

  // Working
  async testaddtocart2() {
    var unsubscriber = this.cartApp.subscribe(Cart.Action.UPDATE, (payload) => {
      // closeApp(this.app);
      unsubscriber();
      this.loadingAddProduct = false;
    });

    const lineItemPayload = {
      price: 20,
      quantity: 1,
      title: 'Bab Low - Blue Jay // White Soles',
      taxable: true,
    };
    this.cartApp.dispatch(Cart.Action.ADD_LINE_ITEM, {
      data: lineItemPayload,
    });
  }
  ```

**Comment by andrewapperley** [comment]
@derrickrc Is this still happening with POS Android? Can you post any errors you receive when running your code?

**Comment by derrickrc** [comment]
I don't recall there being any errors, it just doesn't work.

**Comment by andrewapperley** [comment]
Getting this issue in front of the Retail team. Will post back with any information I gather.

**Comment by dsounded** [comment]
For me it's still the same for POS app (IOS).
The error says:
1 product couldn't be found and was removed.

variantId is valid, it also does work with custom items...

**Comment by dsounded** [comment]
Okay, solved this, needed to convert `variantId` to int (with `parseInt`), silly mistake but I would leave it here just in case
