### ISSUE TITLE
[Feature request] Google Analytics Action

### ISSUE THREAD

**Issue by camelmasa** [Shopify/shopify-app-bridge#6]
### Describe the feature you’d like

We want to integrate Google Analytics using App Bridge.

### Describe alternatives you've considered

Like this.

```ts
import createApp from '@shopify/app-bridge';
import { GoogleAnalytics } from '@shopify/app-bridge/actions';

const app = createApp({
  apiKey: '12345',
  shopOrigin: shopOrigin,
});

const myGoogleAnalytics = GoogleAnalytics.create(app, { id: "UA-141100770-4" });
myGoogleAnalytics.dispatch(location.pathname)
```

### Additional context

Perhaps we can't use Google Analytics in an iframe.
Please tell me if you made a mistake.

**Comment by iainmcampbell** [comment]
hmm, there shouldn't be anything preventing you from using Google Analytics in your embedded app. App Bridge is focused on providing Shopify features to apps. If you want to use other platforms or tools in your app, you're free to do so. It's your iframe ;)

**Comment by camelmasa** [comment]
Thanks for responding.
I thought this feature is useful but I think "App Bridge is focused on providing Shopify features to apps." is right.

We'' try to use [universal-analytics](https://github.com/peaksandpies/universal-analytics) npm.
