### ISSUE TITLE
multiple resource

### ISSUE THREAD

**Issue by mjds666** [Shopify/shopify-app-bridge#63]
### Describe the feature you’d like

A clear and concise description of what you’d like to be able to do with Shopify App Bridge.

### Describe alternatives you've considered

A clear and concise description of any alternative solutions or workarounds you've considered.

### Additional context

Add any other context about the feature request here.

**Comment by elanalynn** [comment]
@mjds666 Can you please add some more context to this issue?

**Comment by elanalynn** [comment]
Closing this because there is not enough context to take action.
