### ISSUE TITLE
Limit selection of products in ResourcePicker

### ISSUE THREAD

**Issue by ivorpad** [Shopify/shopify-app-bridge#7]
It would be nice if we could pass a `limit` option to the `ResourcePicker`. I know I can pass a `selectMultiple` option as `false` but I currently have the need to limit the selection of products to cross sell and it's not possible to limit the number of selections. It's either 1 or many. I would like more flexibility here :)

**Comment by iainmcampbell** [comment]
We’ve added an overload to the `selectMultiple` option as of `1.28.0`: you can now pass in a number to limit the selection to that number of items.

More info:
- https://shopify.dev/tools/app-bridge/actions/resourcepicker#options
- https://shopify.dev/tools/app-bridge/react-components/resourcepicker#props
