### ISSUE TITLE
Slow Shopify-app-bridge together with the use of ngrok

### ISSUE THREAD

**Issue by Draccano** [Shopify/shopify-app-bridge#73]
I've been developing an app using the Shopify CLI pre-built demo app. The ngrok is set up correctly; development seemed to work fine. However, if the user navigates to an already installed app, it takes up to 30s to be visible in the embedded window of the Shopify app. The same problem is if a user navigates between routes. I use ngrok located in the EU region, and my internet connection is fast:). 

Is that normal for all other developers? Thanks.

**Comment by TheSecurityDev** [comment]
This occurs when `NODE_ENV` is set to `development`. If you run as `production` it should make it faster.
