### ISSUE TITLE
Increased reports of APP::ERROR::FAILED_AUTHENTICATION: Failed to retrieve a session token (possibly on non-Chrome browsers?)

### ISSUE THREAD

**Issue by ascherkus** [Shopify/shopify-app-bridge#74]
## Describe the bug

Our session token code has been running reliably in production for months however starting on Aug 16, 2021 we started seeing reports across of the getSessionToken() call failing with APP::ERROR::FAILED_AUTHENTICATION: Failed to retrieve a session token.

This has been happening consistently since for the last few weeks. The error message doesn't give us much to go on nor an appropriate way to handle the error (e.g., is it due to connectivity? is it due to being logged out? is it safe to retry? if so, how many times before giving up? do we just re-use the old token add more slack when verifying the timestamps?)

### To Reproduce

Sadly I don't have a consistent way to reproduce it other than having a widely deployed application that constantly is refreshing tokens while having some client-side Javascript error logging framework installed.

### Expected behaviour

Ideally root cause the issue and revert back to the previous behaviour where we didn't see this issue pop up (again, we didn't see this for months).

Failing that, much more informative error messages and recommended best practices for handling this error.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:
"@shopify/app-bridge": "^1.28.0",
"@shopify/app-bridge-utils": "^1.28.0",
"@shopify/polaris": "^6.2.1",

## Platform

This is where there may be some clues ... we've only logged the error on Mac/iPhone/Safari-based browsers and all our Windows reports come from Firefox (i.e., we have 0 reports of it happening on any version of Chrome).

My initial inclination would be that a change was made that relies on some Chrome-specific behaviour because given the popularity of Chrome and Android among our users it's extremely suspicious to have zero reports of this error.

Hope that helps.

### Additional context

We are a React based app.

**Comment by taketsu** [comment]
I have encountered this error with the following browsers.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

**Comment by Rafi993** [comment]
This issue still is there? Is there any reliable solution for this?
