### ISSUE TITLE
ResourcePicker missing checkboxes on occasion (Australia / regional related?)

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#79]
I have a merchant using our app who reports instances of checkboxes being missing when using the ResourcePicker (see below) - this has happened on multiple occasions. Usually closing the embedded app and re-entering it works. The merchant is not using an older iPad. I am wondering if this is something regionally-related because they're in Australia? 

![image1](https://user-images.githubusercontent.com/46724607/142344487-b8a55b7c-4be3-4577-8721-37bb0c7f78cc.png)

**Comment by derrickrc** [comment]
Thanks Trish! Let me ask her if that's what she's done unwittingly, I appreciate the quick response.

**Comment by derrickrc** [comment]
@vividviolet merchant confirms no, in this case she does not have a box checked (as caused by `selectMultiple:false`). The behavior is something going on with ResourcePicker itself.

**Comment by vividviolet** [comment]
@derrickrc from the screenshot above she does have something selected as it says `1/1 selected`. This indicates that the max selectable item is 1 and there's already something selected.

![image](https://user-images.githubusercontent.com/29458473/142515332-a25c35aa-27ce-44a5-8a05-884ad0672a54.png)

Are you sure you're not setting `selectMultiple: 1` which would limit the selection to a single item? See the docs here: https://shopify.dev/apps/tools/app-bridge/actions/resourcepicker#selectmultiple

**Comment by derrickrc** [comment]
@vividviolet ah good catch. OK I will ask her next time to backspace her additional search filter to see if she can truly confirm no single checkbox is checked, thank you.

**Comment by vividviolet** [comment]
Closing for now - feel free to reopen if you see this happening again
