### ISSUE TITLE
Axios with App Bridge

### ISSUE THREAD

**Issue by issamwahbi** [Shopify/shopify-app-bridge#85]
## Describe the bug

I follow the documentation to set up an interceptor with Axios to get the token. As per the documentation we need to use getSessionToken by passing window.app

import axios from "axios";
import { getSessionToken } from "@shopify/app-bridge-utils";
import { useAppBridge } from "@shopify/app-bridge-react";
const axiosInstance = axios.create();

// Intercept all requests on this Axios instance
axiosInstance.interceptors.request.use(function (config) {
  return getSessionToken(window.app) // requires a Shopify App Bridge instance
    .then((token) => {
      // Append your request headers with an authenticated token
      config.headers["Authorization"] = `Bearer ${token}`;
      return config;
    });
});
// Export your Axios instance to use within your app
export default axiosInstance;

But window.app always returns undefined. I cannot use the useAppBridge hook to get an app instance since it's not allowded in this sport. 

### To Reproduce

Steps to reproduce the behaviour:

1. Launch the app from '...'
2. Click on '...'
3. See error

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `1.23.0`
- `@shopify/app-bridge-react` @ `1.23.0`
- `@shopify/polaris` @ `4.26.0`

## Platform

- OS: [for example MacOS, Windows, iOS, Android]
- OS Version: [for example 10.15.5]
- App: [for example Shopify Mobile, Shopify POS, Chrome, Safari, Firefox]

### Additional context

Add any other context about the problem here, such as your app’s configuration (Node, Next.js, Rails).

**Comment by henrytao-me** [comment]
I believe you need to create new App Bridge `app` instance yourself. `window.app` (+ the comment) in the example is just a placeholder. Follow this docs https://shopify.dev/apps/tools/app-bridge/getting-started#initialize-shopify-app-bridge-in-your-app
