### ISSUE TITLE
Cart feature detection bug on AppBridge 2.0

### ISSUE THREAD

**Issue by rmtngh** [Shopify/shopify-app-bridge#87]
## Describe the bug
Following the [documentation](https://shopify.dev/apps/tools/app-bridge/actions/cart#feature-detection), `state.Cart` object is expected to have keys defined in `app-bridge/actions/Cart`, but they keys are different resulting in error and never successfully detecting the cart feature.

```
app.featuresAvailable(Group.Cart).then(function (state) {
  var _ref = state.Cart && state.Cart[Cart.Action.FETCH], // <---------
  Dispatch = _ref.Dispatch;
...
});
```
 _ref is `undefined`, value of Cart.Action.FETCH from "@shopify/app-bridge": "2.0.5" is: 
`APP::CART::FETCH`
while in the returned value from `featuresAvailable` the object key is:
`FETCH`

**Actual result:**
`FETCH: { Subscribe: true, Dispatch: true }`

**Expected result:** 
`"APP::CART::FETCH": { Subscribe: true, Dispatch: true }`

### To Reproduce

Steps to reproduce the behaviour:

1. Follow feature detection instructions from [here](https://shopify.dev/apps/tools/app-bridge/actions/cart#feature-detection) with the latest version of `@shopify/app-bridge`
2. Launch app on Shopify POS  app v6.71.0 
3. Cart feature is not available

### Expected behaviour

Cart feature needs to be returned as available when an app is launched from Home view on Shopify POS

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `2.0.5`
- `@shopify/app-bridge-react` @ `2.0.5`
- `@shopify/polaris` @ `6.0.1`

## Platform

- OS: iOS
- OS Version: 14.3
- App: Shopify POS v6.71.0 (Build 1004)

**Comment by ZainManji** [comment]
I noticed this as well... As for now, I hardcoded the keys in the code, e.g. "FETCH", instead of using Cart.ActionType.FETCH (which translated to APP::CART::FETCH)
