### ISSUE TITLE
Cart ADD_LINE_ITEM with existing variantId - item is not included in subscriber's payload 

### ISSUE THREAD

**Issue by MohamedWagih** [Shopify/shopify-app-bridge#96]
I'm trying to add a line item with `variant Id` and it's added successfully but it is not included in the subscriber's payload
on the other hand, when adding a `quick sale line item` it's working correctly and it's included in the subscriber's payload.

The expected is that added line item to be included in both cases

Here is how I use the action, is it a problem or am I missing something?

```
var unsubscriber = cart.subscribe(Cart.Action.UPDATE, function (payload) {
  console.log('[Client] addLineItem', payload);
  unsubscriber();
});
cart.dispatch(Cart.Action.ADD_LINE_ITEM, {
  data: {
    variantId: variantId,
    quantity: 1,
  }
});
```

**Comment by dsounded** [comment]
@MohamedWagih hello, have you solved it?

**Comment by henrytao-me** [comment]
Did you see any error (see [here](https://shopify.dev/apps/tools/app-bridge/debugging) for debugging)? `variantId` needs to be a number, not string. I suspect you are passing string. I will close this issue for now.
