### ISSUE TITLE
App bridge barcode scanner not returning payload on Android Shopify Mobile app

### ISSUE THREAD

**Issue by pramodparanthaman** [Shopify/shopify-app-bridge#97]
## Describe the bug

Since the recent update to the Shopify Mobile app for Android on February 9th, the App-bridge Scanner is not returning the captured barcode on Android Shopify Mobile. The same scanning code works fine on Android Shopify POS and the iOS Shopify Mobile/POS apps.

### To Reproduce

1. Add the following code to your app.

```
var scanner = Scanner.create(app);
var features = Features.create(app);
features.subscribe(Features.Action.REQUEST_UPDATE, function (payload) {
  if (payload?.feature[Scanner.Action.OPEN_CAMERA]) {
    let available = payload.feature[Scanner.Action.OPEN_CAMERA].Dispatch;
    if (available) {
      // CAMERA SCANNER OPENS CORRECTLY AND BEEPS WHEN BARCODE IS SCANNED
      scanner.dispatch(Scanner.Action.OPEN_CAMERA);
    }
  }
});

app.subscribe(Scanner.Action.CAPTURE, (payload) => {
  // THIS CODE IS NEVER CALLED AFTER THE BARCODE IS SCANNED
  // ON THE SHOPIFY MOBILE APP FOR ANDROID
  console.log("payload = " + JSON.stringify(payload));
  alert("payload = " + JSON.stringify(payload));
});

// Dispatch an action to request camera permission
features.dispatch(Features.Action.REQUEST, {
  feature: Group.Scanner,
  action: Scanner.Action.OPEN_CAMERA,
});
```
2. Open the app on Shopify Mobile for Android.
3. Scan a barcode and notice that there is no alert message or console log message after the barcode is captured.

### Expected behaviour

Try the same app on Shopify POS for Android or iOS and scan a barcode to see the expected output.

![Alert](https://user-images.githubusercontent.com/66479545/154828443-7a9ff418-681a-4775-82ad-ff3e4dd3d43f.jpg)

### Packages and versions

- `@shopify/app-bridge` @ `2.0.11` (also fails on `1.30.0`)

## Platform

- OS: Android
- OS Version: 12
- App: Shopify Mobile

**Comment by charles-tyler** [comment]
Any update on a fix for this?

**Comment by henrytao-me** [comment]
Hi @charles-tyler, a fix should be up by end of tomorrow 🙇

**Comment by AaronSpringut** [comment]
Hi, 
We have identified that this bug is actually still present in production. It's possible that this bug will not occur if the application requests access to the camera after checking access the first time. We have identified a fix for the issue and it should be deployed in approximately two weeks.

If you have any questions please feel free to reach out.

Best,
Aaron

**Comment by pramodparanthaman** [comment]
You're right, the Android camera scanner fails after scanning the first barcode with scanner.subscribe().

But scanner.subscribe() has been broken for quite some time on iOS and we stopped using it.
See https://github.com/Shopify/shopify-app-bridge/issues/50#issuecomment-835552196

So, as a workaround we have been using app.subscribe(), which works on both iOS and Android:
```
app.subscribe(Scanner.Action.CAPTURE, function(payload) {
  // The payload will contain `scanData`, a string representation of the data scanned.
});
```

app.subscribe() works correctly and scans multiple barcodes with no problem after yesterdays Android Shopify Mobile update. 

Just putting it out there incase anyone needs a working barcode scanner on Android Shopify Mobile.

@AaronSpringut please let the iOS team also know, so they can fix this, I would prefer using the same code (scanner.subscribe) on all 4 version of app-bridge (iOS / Android on both Shopify Mobile and POS).

**Comment by henrytao-me** [comment]
Hi @pramodparanthaman I just verified on both iOS (production) and Android (upcoming build), doing subscribe in scanner works just fine 

```ts
    scanner.subscribe(AppBridge.Scanner.Action.CAPTURE, (payload) => {
      toast.set({message: `Scanned: ${payload.data.scanData}`});
      toast.dispatch(AppBridge.Toast.Action.SHOW);
    });
```

**Comment by henrytao-me** [comment]
The main different between `scanner.subscribe` and `app.subscribe` is that `scanner.subscribe` only subscribe to specific id from the `scanner` object when it's created. So, if you are using React, make sure you don't re-create the `scanner` object which I suspect it happens in your app. Can you check it and let me know please? 🙇

**Comment by neatbyte-vnobis** [comment]
@henrytao-me 
I have tried to check scanner object recreation as you have suggested.
While it may be an issue (as I am using a React functional components) looks like `scanner.subscribe` is not working.
Here is a code I am trying to use:
```js
...
  const app = useAppBridge();
  const features = Features.create(app);
  const cart = Cart.create(app);

  const { show } = useToast();

  const scanWithPhone = useCallback(() => {
    const scanner = Scanner.create(app);

    scanner.subscribe(Scanner.Action.CAPTURE, function (payload) {
      try {
        // do smth here

        show(`Added to the cart`);
      } catch (err) {
        show(err.message, { isError: true });
      }
    });

    scanner.dispatch(Scanner.Action.OPEN_CAMERA);
  }, [app, show]);
...
```
As you can see scanner object is created inside `scanWithPhone` callback (used as button onclick callback).
It is the only place where I have a `Scanner.create(app)` and `scanner.subscribe` callback is not executed.
Please advice.

**Comment by henrytao-me** [comment]
I see the issue. Apparently, there is another fixed which was merged to main branch but somehow didn't get in the 7.0.3 release. I will let POS team know. Thanks for reporting this 🙇

**Comment by henrytao-me** [comment]
A workaround for now is having camera permission allowed from Shopify POS before opening embedded app. For example: click on the barcode scanner in the home screen search bar.

**Comment by neatbyte-vnobis** [comment]
@henrytao-me 
I my case I have Shopify POS app with camera permission for around a year... So I am not sure if it is related to described issue.
Maybe inner state inside Shopify POS is fixed by scanning from home screen search bar.
Have you tried to close/open Shopify POS app after that? And trying to scan from embedded app again.

**Comment by henrytao-me** [comment]
@neatbyte-vnobis I understand your scenario. There are major changes in POS 7.0.3. So, I imagine if you toggle the camera permission, it might work. Can you try and let me know?
